# This file is auto-generated by aws_resource_validator.generator.pipeline_b.
# Do not edit manually; run `arv-generate pipeline-b` to refresh it.
from datetime import datetime
from decimal import Decimal
from typing import (
    Annotated,
    Any,
    Callable,
    Dict,
    FrozenSet,
    IO,
    List,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    Union,
)

from botocore.client import BaseClient
from botocore.response import StreamingBody
from pydantic import Field

from aws_resource_validator.core.base_validator_model import BaseValidatorModel, EventStream
from aws_resource_validator.core.pattern_validation import aws_field_pattern as _aws_pattern
from aws_resource_validator.pydantic_models.amp.amp_constants import *  # noqa: F401,F403

# Optional boto3 symbols — imported lazily so services that don't need them
# aren't forced to pull in boto3 at import time.
try:
    from boto3.dynamodb.conditions import ConditionBase  # noqa: F401
except ImportError:  # pragma: no cover
    ConditionBase = Any  # type: ignore[assignment,misc]
try:
    from boto3.s3.transfer import TransferConfig  # noqa: F401
except ImportError:  # pragma: no cover
    TransferConfig = Any  # type: ignore[assignment,misc]


class AlertManagerDefinitionStatusTypeDef(BaseValidatorModel):
    statusCode: AlertManagerDefinitionStatusCodeType
    statusReason: Optional[str] = None


class AmpConfigurationTypeDef(BaseValidatorModel):
    workspaceArn: Annotated[str, _aws_pattern("Amp", "WorkspaceArn")]


class AnomalyDetectorMissingDataActionTypeDef(BaseValidatorModel):
    markAsAnomaly: Optional[bool] = None
    skip: Optional[bool] = None


class AnomalyDetectorStatusTypeDef(BaseValidatorModel):
    statusCode: AnomalyDetectorStatusCodeType
    statusReason: Optional[str] = None


BlobTypeDef = Union[IO[Any], StreamingBody, bytes, str]


class CloudWatchLogDestinationTypeDef(BaseValidatorModel):
    logGroupArn: Annotated[str, _aws_pattern("Amp", "LogGroupArn")]


class ComponentConfigOutputTypeDef(BaseValidatorModel):
    options: Optional[Dict[str, str]] = None


class ComponentConfigTypeDef(BaseValidatorModel):
    options: Optional[Dict[str, str]] = None


class ResponseMetadataTypeDef(BaseValidatorModel):
    RequestId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, str]
    RetryAttempts: int
    HostId: Optional[str] = None


# This class is the input for the 'create_logging_configuration' function.
class CreateLoggingConfigurationRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    logGroupArn: Annotated[str, _aws_pattern("Amp", "LogGroupArn")]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


class LoggingConfigurationStatusTypeDef(BaseValidatorModel):
    statusCode: LoggingConfigurationStatusCodeType
    statusReason: Optional[str] = None


class QueryLoggingConfigurationStatusTypeDef(BaseValidatorModel):
    statusCode: QueryLoggingConfigurationStatusCodeType
    statusReason: Optional[str] = None


class RuleGroupsNamespaceStatusTypeDef(BaseValidatorModel):
    statusCode: RuleGroupsNamespaceStatusCodeType
    statusReason: Optional[str] = None


class RoleConfigurationTypeDef(BaseValidatorModel):
    sourceRoleArn: Optional[Annotated[str, _aws_pattern("Amp", "IamRoleArn")]] = None
    targetRoleArn: Optional[Annotated[str, _aws_pattern("Amp", "IamRoleArn")]] = None


class ScraperStatusTypeDef(BaseValidatorModel):
    statusCode: ScraperStatusCodeType


# This class is the input for the 'create_workspace' function.
class CreateWorkspaceRequestTypeDef(BaseValidatorModel):
    alias: Optional[str] = None
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None
    tags: Optional[Dict[str, str]] = None
    kmsKeyArn: Optional[Annotated[str, _aws_pattern("Amp", "KmsKeyArn")]] = None


class WorkspaceStatusTypeDef(BaseValidatorModel):
    statusCode: WorkspaceStatusCodeType


# This class is the input for the 'delete_alert_manager_definition' function.
class DeleteAlertManagerDefinitionRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


# This class is the input for the 'delete_anomaly_detector' function.
class DeleteAnomalyDetectorRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    anomalyDetectorId: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorId")]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


# This class is the input for the 'delete_logging_configuration' function.
class DeleteLoggingConfigurationRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


# This class is the input for the 'delete_query_logging_configuration' function.
class DeleteQueryLoggingConfigurationRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


# This class is the input for the 'delete_resource_policy' function.
class DeleteResourcePolicyRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None
    revisionId: Optional[str] = None


# This class is the input for the 'delete_rule_groups_namespace' function.
class DeleteRuleGroupsNamespaceRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    name: Annotated[str, _aws_pattern("Amp", "RuleGroupsNamespaceName")]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


# This class is the input for the 'delete_scraper_logging_configuration' function.
class DeleteScraperLoggingConfigurationRequestTypeDef(BaseValidatorModel):
    scraperId: Annotated[str, _aws_pattern("Amp", "ScraperId")]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


# This class is the input for the 'delete_scraper' function.
class DeleteScraperRequestTypeDef(BaseValidatorModel):
    scraperId: Annotated[str, _aws_pattern("Amp", "ScraperId")]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


# This class is the input for the 'delete_workspace' function.
class DeleteWorkspaceRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


# This class is the input for the 'describe_alert_manager_definition' function.
class DescribeAlertManagerDefinitionRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]


# This class is the input for the 'describe_anomaly_detector' function.
class DescribeAnomalyDetectorRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    anomalyDetectorId: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorId")]


class WaiterConfigTypeDef(BaseValidatorModel):
    Delay: Optional[int] = None
    MaxAttempts: Optional[int] = None


# This class is the input for the 'describe_logging_configuration' function.
class DescribeLoggingConfigurationRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]


# This class is the input for the 'describe_query_logging_configuration' function.
class DescribeQueryLoggingConfigurationRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]


# This class is the input for the 'describe_resource_policy' function.
class DescribeResourcePolicyRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]


# This class is the input for the 'describe_rule_groups_namespace' function.
class DescribeRuleGroupsNamespaceRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    name: Annotated[str, _aws_pattern("Amp", "RuleGroupsNamespaceName")]


# This class is the input for the 'describe_scraper_logging_configuration' function.
class DescribeScraperLoggingConfigurationRequestTypeDef(BaseValidatorModel):
    scraperId: Annotated[str, _aws_pattern("Amp", "ScraperId")]


class ScraperLoggingConfigurationStatusTypeDef(BaseValidatorModel):
    statusCode: ScraperLoggingConfigurationStatusCodeType
    statusReason: Optional[str] = None


# This class is the input for the 'describe_scraper' function.
class DescribeScraperRequestTypeDef(BaseValidatorModel):
    scraperId: Annotated[str, _aws_pattern("Amp", "ScraperId")]


# This class is the input for the 'describe_workspace_configuration' function.
class DescribeWorkspaceConfigurationRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]


# This class is the input for the 'describe_workspace' function.
class DescribeWorkspaceRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]


class EksConfigurationOutputTypeDef(BaseValidatorModel):
    clusterArn: str
    subnetIds: List[str]
    securityGroupIds: Optional[List[str]] = None


class EksConfigurationTypeDef(BaseValidatorModel):
    clusterArn: Annotated[str, _aws_pattern("Amp", "ClusterArn")]
    subnetIds: List[Annotated[str, _aws_pattern("Amp", "SubnetId")]]
    securityGroupIds: Optional[List[Annotated[str, _aws_pattern("Amp", "SecurityGroupId")]]] = None


class IgnoreNearExpectedTypeDef(BaseValidatorModel):
    amount: Optional[float] = None
    ratio: Optional[float] = None


class LimitsPerLabelSetEntryTypeDef(BaseValidatorModel):
    maxSeries: Optional[int] = None


class PaginatorConfigTypeDef(BaseValidatorModel):
    MaxItems: Optional[int] = None
    PageSize: Optional[int] = None
    StartingToken: Optional[str] = None


# This class is the input for the 'list_anomaly_detectors' function.
class ListAnomalyDetectorsRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    alias: Optional[Annotated[str, _aws_pattern("Amp", "AnomalyDetectorAlias")]] = None
    maxResults: Optional[int] = None
    nextToken: Optional[str] = None


# This class is the input for the 'list_rule_groups_namespaces' function.
class ListRuleGroupsNamespacesRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    name: Optional[Annotated[str, _aws_pattern("Amp", "RuleGroupsNamespaceName")]] = None
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_scrapers' function.
class ListScrapersRequestTypeDef(BaseValidatorModel):
    filters: Optional[Dict[str, List[str]]] = None
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_tags_for_resource' function.
class ListTagsForResourceRequestTypeDef(BaseValidatorModel):
    resourceArn: str


# This class is the input for the 'list_workspaces' function.
class ListWorkspacesRequestTypeDef(BaseValidatorModel):
    nextToken: Optional[str] = None
    alias: Optional[str] = None
    maxResults: Optional[int] = None


class LoggingFilterTypeDef(BaseValidatorModel):
    qspThreshold: int


# This class is the input for the 'put_resource_policy' function.
class PutResourcePolicyRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    policyDocument: str
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None
    revisionId: Optional[str] = None


class ScrapeConfigurationOutputTypeDef(BaseValidatorModel):
    configurationBlob: Optional[bytes] = None


class VpcConfigurationOutputTypeDef(BaseValidatorModel):
    securityGroupIds: List[str]
    subnetIds: List[str]


class VpcConfigurationTypeDef(BaseValidatorModel):
    securityGroupIds: List[Annotated[str, _aws_pattern("Amp", "SecurityGroupId")]]
    subnetIds: List[Annotated[str, _aws_pattern("Amp", "SubnetId")]]


class TagResourceRequestTypeDef(BaseValidatorModel):
    resourceArn: str
    tags: Dict[str, str]


class UntagResourceRequestTypeDef(BaseValidatorModel):
    resourceArn: str
    tagKeys: List[Annotated[str, _aws_pattern("Amp", "TagKey")]]


# This class is the input for the 'update_logging_configuration' function.
class UpdateLoggingConfigurationRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    logGroupArn: Annotated[str, _aws_pattern("Amp", "LogGroupArn")]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


# This class is the input for the 'update_workspace_alias' function.
class UpdateWorkspaceAliasRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    alias: Optional[str] = None
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


class WorkspaceConfigurationStatusTypeDef(BaseValidatorModel):
    statusCode: WorkspaceConfigurationStatusCodeType
    statusReason: Optional[str] = None


class AlertManagerDefinitionDescriptionTypeDef(BaseValidatorModel):
    status: AlertManagerDefinitionStatusTypeDef
    data: bytes
    createdAt: datetime
    modifiedAt: datetime


class DestinationTypeDef(BaseValidatorModel):
    ampConfiguration: Optional[AmpConfigurationTypeDef] = None


class AnomalyDetectorSummaryTypeDef(BaseValidatorModel):
    arn: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorArn")]
    anomalyDetectorId: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorId")]
    alias: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorAlias")]
    status: AnomalyDetectorStatusTypeDef
    createdAt: datetime
    modifiedAt: datetime
    tags: Optional[Dict[str, str]] = None


# This class is the input for the 'create_alert_manager_definition' function.
class CreateAlertManagerDefinitionRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    data: BlobTypeDef
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


# This class is the input for the 'create_rule_groups_namespace' function.
class CreateRuleGroupsNamespaceRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    name: Annotated[str, _aws_pattern("Amp", "RuleGroupsNamespaceName")]
    data: BlobTypeDef
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None
    tags: Optional[Dict[str, str]] = None


# This class is the input for the 'put_alert_manager_definition' function.
class PutAlertManagerDefinitionRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    data: BlobTypeDef
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


# This class is the input for the 'put_rule_groups_namespace' function.
class PutRuleGroupsNamespaceRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    name: Annotated[str, _aws_pattern("Amp", "RuleGroupsNamespaceName")]
    data: BlobTypeDef
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


class ScrapeConfigurationTypeDef(BaseValidatorModel):
    configurationBlob: Optional[BlobTypeDef] = None


class ScraperLoggingDestinationTypeDef(BaseValidatorModel):
    cloudWatchLogs: Optional[CloudWatchLogDestinationTypeDef] = None


class ScraperComponentOutputTypeDef(BaseValidatorModel):
    type: ScraperComponentTypeType
    config: Optional[ComponentConfigOutputTypeDef] = None


ComponentConfigUnionTypeDef = Union[ComponentConfigOutputTypeDef, ComponentConfigTypeDef]


# This class is the output for the 'create_alert_manager_definition' function.
class CreateAlertManagerDefinitionResponseTypeDef(BaseValidatorModel):
    status: AlertManagerDefinitionStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_anomaly_detector' function.
class CreateAnomalyDetectorResponseTypeDef(BaseValidatorModel):
    anomalyDetectorId: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorId")]
    arn: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorArn")]
    status: AnomalyDetectorStatusTypeDef
    tags: Dict[str, str]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_resource_policy' function.
class DescribeResourcePolicyResponseTypeDef(BaseValidatorModel):
    policyDocument: str
    policyStatus: WorkspacePolicyStatusCodeType
    revisionId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_alert_manager_definition' function.
class EmptyResponseMetadataTypeDef(BaseValidatorModel):
    ResponseMetadata: ResponseMetadataTypeDef


class GetDefaultScraperConfigurationResponseTypeDef(BaseValidatorModel):
    configuration: bytes
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_tags_for_resource' function.
class ListTagsForResourceResponseTypeDef(BaseValidatorModel):
    tags: Dict[str, str]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'put_alert_manager_definition' function.
class PutAlertManagerDefinitionResponseTypeDef(BaseValidatorModel):
    status: AlertManagerDefinitionStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'put_anomaly_detector' function.
class PutAnomalyDetectorResponseTypeDef(BaseValidatorModel):
    anomalyDetectorId: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorId")]
    arn: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorArn")]
    status: AnomalyDetectorStatusTypeDef
    tags: Dict[str, str]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'put_resource_policy' function.
class PutResourcePolicyResponseTypeDef(BaseValidatorModel):
    policyStatus: WorkspacePolicyStatusCodeType
    revisionId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_logging_configuration' function.
class CreateLoggingConfigurationResponseTypeDef(BaseValidatorModel):
    status: LoggingConfigurationStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class LoggingConfigurationMetadataTypeDef(BaseValidatorModel):
    status: LoggingConfigurationStatusTypeDef
    workspace: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    logGroupArn: Annotated[str, _aws_pattern("Amp", "LogGroupArn")]
    createdAt: datetime
    modifiedAt: datetime


# This class is the output for the 'update_logging_configuration' function.
class UpdateLoggingConfigurationResponseTypeDef(BaseValidatorModel):
    status: LoggingConfigurationStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_query_logging_configuration' function.
class CreateQueryLoggingConfigurationResponseTypeDef(BaseValidatorModel):
    status: QueryLoggingConfigurationStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_query_logging_configuration' function.
class UpdateQueryLoggingConfigurationResponseTypeDef(BaseValidatorModel):
    status: QueryLoggingConfigurationStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_rule_groups_namespace' function.
class CreateRuleGroupsNamespaceResponseTypeDef(BaseValidatorModel):
    name: Annotated[str, _aws_pattern("Amp", "RuleGroupsNamespaceName")]
    arn: str
    status: RuleGroupsNamespaceStatusTypeDef
    tags: Dict[str, str]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'put_rule_groups_namespace' function.
class PutRuleGroupsNamespaceResponseTypeDef(BaseValidatorModel):
    name: Annotated[str, _aws_pattern("Amp", "RuleGroupsNamespaceName")]
    arn: str
    status: RuleGroupsNamespaceStatusTypeDef
    tags: Dict[str, str]
    ResponseMetadata: ResponseMetadataTypeDef


class RuleGroupsNamespaceDescriptionTypeDef(BaseValidatorModel):
    arn: str
    name: Annotated[str, _aws_pattern("Amp", "RuleGroupsNamespaceName")]
    status: RuleGroupsNamespaceStatusTypeDef
    data: bytes
    createdAt: datetime
    modifiedAt: datetime
    tags: Optional[Dict[str, str]] = None


class RuleGroupsNamespaceSummaryTypeDef(BaseValidatorModel):
    arn: str
    name: Annotated[str, _aws_pattern("Amp", "RuleGroupsNamespaceName")]
    status: RuleGroupsNamespaceStatusTypeDef
    createdAt: datetime
    modifiedAt: datetime
    tags: Optional[Dict[str, str]] = None


# This class is the output for the 'create_scraper' function.
class CreateScraperResponseTypeDef(BaseValidatorModel):
    scraperId: Annotated[str, _aws_pattern("Amp", "ScraperId")]
    arn: str
    status: ScraperStatusTypeDef
    tags: Dict[str, str]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_scraper' function.
class DeleteScraperResponseTypeDef(BaseValidatorModel):
    scraperId: Annotated[str, _aws_pattern("Amp", "ScraperId")]
    status: ScraperStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_scraper' function.
class UpdateScraperResponseTypeDef(BaseValidatorModel):
    scraperId: Annotated[str, _aws_pattern("Amp", "ScraperId")]
    arn: str
    status: ScraperStatusTypeDef
    tags: Dict[str, str]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_workspace' function.
class CreateWorkspaceResponseTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    arn: Annotated[str, _aws_pattern("Amp", "WorkspaceArn")]
    status: WorkspaceStatusTypeDef
    tags: Dict[str, str]
    kmsKeyArn: Annotated[str, _aws_pattern("Amp", "KmsKeyArn")]
    ResponseMetadata: ResponseMetadataTypeDef


class WorkspaceDescriptionTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    arn: Annotated[str, _aws_pattern("Amp", "WorkspaceArn")]
    status: WorkspaceStatusTypeDef
    createdAt: datetime
    alias: Optional[str] = None
    prometheusEndpoint: Optional[str] = None
    tags: Optional[Dict[str, str]] = None
    kmsKeyArn: Optional[Annotated[str, _aws_pattern("Amp", "KmsKeyArn")]] = None


class WorkspaceSummaryTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    arn: Annotated[str, _aws_pattern("Amp", "WorkspaceArn")]
    status: WorkspaceStatusTypeDef
    createdAt: datetime
    alias: Optional[str] = None
    tags: Optional[Dict[str, str]] = None
    kmsKeyArn: Optional[Annotated[str, _aws_pattern("Amp", "KmsKeyArn")]] = None


class DescribeAnomalyDetectorRequestWaitExtraTypeDef(BaseValidatorModel):
    workspaceId: str
    anomalyDetectorId: str
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


class DescribeAnomalyDetectorRequestWaitTypeDef(BaseValidatorModel):
    workspaceId: str
    anomalyDetectorId: str
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


class DescribeScraperRequestWaitExtraTypeDef(BaseValidatorModel):
    scraperId: str
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


class DescribeScraperRequestWaitTypeDef(BaseValidatorModel):
    scraperId: str
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


class DescribeWorkspaceRequestWaitExtraTypeDef(BaseValidatorModel):
    workspaceId: str
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


class DescribeWorkspaceRequestWaitTypeDef(BaseValidatorModel):
    workspaceId: str
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


# This class is the output for the 'update_scraper_logging_configuration' function.
class UpdateScraperLoggingConfigurationResponseTypeDef(BaseValidatorModel):
    status: ScraperLoggingConfigurationStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class RandomCutForestConfigurationTypeDef(BaseValidatorModel):
    query: str
    shingleSize: Optional[int] = None
    sampleSize: Optional[int] = None
    ignoreNearExpectedFromAbove: Optional[IgnoreNearExpectedTypeDef] = None
    ignoreNearExpectedFromBelow: Optional[IgnoreNearExpectedTypeDef] = None


class LimitsPerLabelSetOutputTypeDef(BaseValidatorModel):
    limits: LimitsPerLabelSetEntryTypeDef
    labelSet: Dict[str, str]


class LimitsPerLabelSetTypeDef(BaseValidatorModel):
    limits: LimitsPerLabelSetEntryTypeDef
    labelSet: Dict[str, str]


class ListAnomalyDetectorsRequestPaginateTypeDef(BaseValidatorModel):
    workspaceId: str
    alias: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListRuleGroupsNamespacesRequestPaginateTypeDef(BaseValidatorModel):
    workspaceId: str
    name: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListScrapersRequestPaginateTypeDef(BaseValidatorModel):
    filters: Optional[Dict[str, List[str]]] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListWorkspacesRequestPaginateTypeDef(BaseValidatorModel):
    alias: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class LoggingDestinationTypeDef(BaseValidatorModel):
    cloudWatchLogs: CloudWatchLogDestinationTypeDef
    filters: LoggingFilterTypeDef


class SourceOutputTypeDef(BaseValidatorModel):
    eksConfiguration: Optional[EksConfigurationOutputTypeDef] = None
    vpcConfiguration: Optional[VpcConfigurationOutputTypeDef] = None


class SourceTypeDef(BaseValidatorModel):
    eksConfiguration: Optional[EksConfigurationTypeDef] = None
    vpcConfiguration: Optional[VpcConfigurationTypeDef] = None


# This class is the output for the 'update_workspace_configuration' function.
class UpdateWorkspaceConfigurationResponseTypeDef(BaseValidatorModel):
    status: WorkspaceConfigurationStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_alert_manager_definition' function.
class DescribeAlertManagerDefinitionResponseTypeDef(BaseValidatorModel):
    alertManagerDefinition: AlertManagerDefinitionDescriptionTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_anomaly_detectors' function.
class ListAnomalyDetectorsResponseTypeDef(BaseValidatorModel):
    anomalyDetectors: List[AnomalyDetectorSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


ScrapeConfigurationUnionTypeDef = Union[ScrapeConfigurationOutputTypeDef, ScrapeConfigurationTypeDef]


# This class is the output for the 'describe_scraper_logging_configuration' function.
class DescribeScraperLoggingConfigurationResponseTypeDef(BaseValidatorModel):
    status: ScraperLoggingConfigurationStatusTypeDef
    scraperId: Annotated[str, _aws_pattern("Amp", "ScraperId")]
    loggingDestination: ScraperLoggingDestinationTypeDef
    scraperComponents: List[ScraperComponentOutputTypeDef]
    modifiedAt: datetime
    ResponseMetadata: ResponseMetadataTypeDef


class ScraperComponentTypeDef(BaseValidatorModel):
    type: ScraperComponentTypeType
    config: Optional[ComponentConfigUnionTypeDef] = None


# This class is the output for the 'describe_logging_configuration' function.
class DescribeLoggingConfigurationResponseTypeDef(BaseValidatorModel):
    loggingConfiguration: LoggingConfigurationMetadataTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_rule_groups_namespace' function.
class DescribeRuleGroupsNamespaceResponseTypeDef(BaseValidatorModel):
    ruleGroupsNamespace: RuleGroupsNamespaceDescriptionTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_rule_groups_namespaces' function.
class ListRuleGroupsNamespacesResponseTypeDef(BaseValidatorModel):
    ruleGroupsNamespaces: List[RuleGroupsNamespaceSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'describe_workspace' function.
class DescribeWorkspaceResponseTypeDef(BaseValidatorModel):
    workspace: WorkspaceDescriptionTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_workspaces' function.
class ListWorkspacesResponseTypeDef(BaseValidatorModel):
    workspaces: List[WorkspaceSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class AnomalyDetectorConfigurationTypeDef(BaseValidatorModel):
    randomCutForest: Optional[RandomCutForestConfigurationTypeDef] = None


class WorkspaceConfigurationDescriptionTypeDef(BaseValidatorModel):
    status: WorkspaceConfigurationStatusTypeDef
    limitsPerLabelSet: Optional[List[LimitsPerLabelSetOutputTypeDef]] = None
    retentionPeriodInDays: Optional[int] = None


LimitsPerLabelSetUnionTypeDef = Union[LimitsPerLabelSetOutputTypeDef, LimitsPerLabelSetTypeDef]


# This class is the input for the 'create_query_logging_configuration' function.
class CreateQueryLoggingConfigurationRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    destinations: List[LoggingDestinationTypeDef]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


class QueryLoggingConfigurationMetadataTypeDef(BaseValidatorModel):
    status: QueryLoggingConfigurationStatusTypeDef
    workspace: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    destinations: List[LoggingDestinationTypeDef]
    createdAt: datetime
    modifiedAt: datetime


# This class is the input for the 'update_query_logging_configuration' function.
class UpdateQueryLoggingConfigurationRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    destinations: List[LoggingDestinationTypeDef]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


class ScraperDescriptionTypeDef(BaseValidatorModel):
    scraperId: Annotated[str, _aws_pattern("Amp", "ScraperId")]
    arn: str
    roleArn: Annotated[str, _aws_pattern("Amp", "IamRoleArn")]
    status: ScraperStatusTypeDef
    createdAt: datetime
    lastModifiedAt: datetime
    scrapeConfiguration: ScrapeConfigurationOutputTypeDef
    source: SourceOutputTypeDef
    destination: DestinationTypeDef
    alias: Optional[Annotated[str, _aws_pattern("Amp", "ScraperAlias")]] = None
    tags: Optional[Dict[str, str]] = None
    statusReason: Optional[str] = None
    roleConfiguration: Optional[RoleConfigurationTypeDef] = None


class ScraperSummaryTypeDef(BaseValidatorModel):
    scraperId: Annotated[str, _aws_pattern("Amp", "ScraperId")]
    arn: str
    roleArn: Annotated[str, _aws_pattern("Amp", "IamRoleArn")]
    status: ScraperStatusTypeDef
    createdAt: datetime
    lastModifiedAt: datetime
    source: SourceOutputTypeDef
    destination: DestinationTypeDef
    alias: Optional[Annotated[str, _aws_pattern("Amp", "ScraperAlias")]] = None
    tags: Optional[Dict[str, str]] = None
    statusReason: Optional[str] = None
    roleConfiguration: Optional[RoleConfigurationTypeDef] = None


SourceUnionTypeDef = Union[SourceOutputTypeDef, SourceTypeDef]


# This class is the input for the 'update_scraper' function.
class UpdateScraperRequestTypeDef(BaseValidatorModel):
    scraperId: Annotated[str, _aws_pattern("Amp", "ScraperId")]
    alias: Optional[Annotated[str, _aws_pattern("Amp", "ScraperAlias")]] = None
    scrapeConfiguration: Optional[ScrapeConfigurationUnionTypeDef] = None
    destination: Optional[DestinationTypeDef] = None
    roleConfiguration: Optional[RoleConfigurationTypeDef] = None
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


ScraperComponentUnionTypeDef = Union[ScraperComponentOutputTypeDef, ScraperComponentTypeDef]


class AnomalyDetectorDescriptionTypeDef(BaseValidatorModel):
    arn: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorArn")]
    anomalyDetectorId: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorId")]
    alias: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorAlias")]
    status: AnomalyDetectorStatusTypeDef
    createdAt: datetime
    modifiedAt: datetime
    evaluationIntervalInSeconds: Optional[int] = None
    missingDataAction: Optional[AnomalyDetectorMissingDataActionTypeDef] = None
    configuration: Optional[AnomalyDetectorConfigurationTypeDef] = None
    labels: Optional[Dict[str, str]] = None
    tags: Optional[Dict[str, str]] = None


# This class is the input for the 'create_anomaly_detector' function.
class CreateAnomalyDetectorRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    alias: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorAlias")]
    configuration: AnomalyDetectorConfigurationTypeDef
    evaluationIntervalInSeconds: Optional[int] = None
    missingDataAction: Optional[AnomalyDetectorMissingDataActionTypeDef] = None
    labels: Optional[Dict[str, str]] = None
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None
    tags: Optional[Dict[str, str]] = None


# This class is the input for the 'put_anomaly_detector' function.
class PutAnomalyDetectorRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    anomalyDetectorId: Annotated[str, _aws_pattern("Amp", "AnomalyDetectorId")]
    configuration: AnomalyDetectorConfigurationTypeDef
    evaluationIntervalInSeconds: Optional[int] = None
    missingDataAction: Optional[AnomalyDetectorMissingDataActionTypeDef] = None
    labels: Optional[Dict[str, str]] = None
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None


# This class is the output for the 'describe_workspace_configuration' function.
class DescribeWorkspaceConfigurationResponseTypeDef(BaseValidatorModel):
    workspaceConfiguration: WorkspaceConfigurationDescriptionTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'update_workspace_configuration' function.
class UpdateWorkspaceConfigurationRequestTypeDef(BaseValidatorModel):
    workspaceId: Annotated[str, _aws_pattern("Amp", "WorkspaceId")]
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None
    limitsPerLabelSet: Optional[List[LimitsPerLabelSetUnionTypeDef]] = None
    retentionPeriodInDays: Optional[int] = None


# This class is the output for the 'describe_query_logging_configuration' function.
class DescribeQueryLoggingConfigurationResponseTypeDef(BaseValidatorModel):
    queryLoggingConfiguration: QueryLoggingConfigurationMetadataTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_scraper' function.
class DescribeScraperResponseTypeDef(BaseValidatorModel):
    scraper: ScraperDescriptionTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_scrapers' function.
class ListScrapersResponseTypeDef(BaseValidatorModel):
    scrapers: List[ScraperSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the input for the 'create_scraper' function.
class CreateScraperRequestTypeDef(BaseValidatorModel):
    scrapeConfiguration: ScrapeConfigurationUnionTypeDef
    source: SourceUnionTypeDef
    destination: DestinationTypeDef
    alias: Optional[Annotated[str, _aws_pattern("Amp", "ScraperAlias")]] = None
    roleConfiguration: Optional[RoleConfigurationTypeDef] = None
    clientToken: Optional[Annotated[str, _aws_pattern("Amp", "IdempotencyToken")]] = None
    tags: Optional[Dict[str, str]] = None


# This class is the input for the 'update_scraper_logging_configuration' function.
class UpdateScraperLoggingConfigurationRequestTypeDef(BaseValidatorModel):
    scraperId: Annotated[str, _aws_pattern("Amp", "ScraperId")]
    loggingDestination: ScraperLoggingDestinationTypeDef
    scraperComponents: Optional[List[ScraperComponentUnionTypeDef]] = None


# This class is the output for the 'describe_anomaly_detector' function.
class DescribeAnomalyDetectorResponseTypeDef(BaseValidatorModel):
    anomalyDetector: AnomalyDetectorDescriptionTypeDef
    ResponseMetadata: ResponseMetadataTypeDef
