site_name: AWS Resource Validator Documentation
site_description: AWS Resource Validator Documentation
site_author: Yafit Tupman
site_url: https://coreoxide.github.io/aws_resource_validator/
edit_uri: edit/main/docs

plugins:
  - search
  - render_swagger
  - macros
  - awesome-pages

theme:
  name: material
  logo: images/icon.png
  favicon: images/icon.png
  font:
    text: Ubuntu
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.path
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - content.code.annotate
    - toc.integrate
    - toc.follow

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/CoreOxide/aws_resource_validator
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yafit-tupman/
    - icon: fontawesome/brands/linkedin
      link: http://www.linkedin.com/in/alexygrabov
    - icon: fontawesome/brands/medium
      link: https://medium.com/@alexy-grabov

copyright: Copyright &copy; 2024 Yafit Tupman
