[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry]
name = "aws-resource-validator"
version = "0.4.1"
description = "Validate, get validation patterns and generate valid AWS resource names (for testing \\ mocks)"
authors = ["Alexy Grabov <alexy.grabov@gmail.com>", "Yafit Tupman <ytupman@gmail.com>"]
license = "Apache License 2.0"
readme = "README.md"
packages = [
    {include = "aws_resource_validator/class_definitions.py", from = "."},
    {include = "aws_resource_validator/models.py", from = "."},
    {include = "aws_resource_validator/pydantic_models", from = "."}
]

[tool.poetry.dependencies]
python = "^3.9 || ^3.12 || ^3.13"
exrex = "*"
pydantic = "^2.8.2"
botocore = "*"

[tool.poetry.dev-dependencies]
requests = "*"
boto3-stubs = { extras = ["all"], version = "*" }
ruamel-yaml = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
