# This file is auto-generated by aws_resource_validator.generator.pipeline_b.
# Do not edit manually; run `arv-generate pipeline-b` to refresh it.
from datetime import datetime
from decimal import Decimal
from typing import (
    Any,
    Callable,
    Dict,
    FrozenSet,
    IO,
    List,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    Union,
)

from botocore.client import BaseClient
from botocore.response import StreamingBody
from pydantic import Field

from aws_resource_validator.core.base_validator_model import BaseValidatorModel, EventStream
from aws_resource_validator.pydantic_models.appconfig.appconfig_constants import *  # noqa: F401,F403

# Optional boto3 symbols — imported lazily so services that don't need them
# aren't forced to pull in boto3 at import time.
try:
    from boto3.dynamodb.conditions import ConditionBase  # noqa: F401
except ImportError:  # pragma: no cover
    ConditionBase = Any  # type: ignore[assignment,misc]
try:
    from boto3.s3.transfer import TransferConfig  # noqa: F401
except ImportError:  # pragma: no cover
    TransferConfig = Any  # type: ignore[assignment,misc]


class DeletionProtectionSettingsTypeDef(BaseValidatorModel):
    Enabled: Optional[bool] = None
    ProtectionPeriodInMinutes: Optional[int] = None


class ResponseMetadataTypeDef(BaseValidatorModel):
    RequestId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, str]
    RetryAttempts: int
    HostId: Optional[str] = None


class ActionInvocationTypeDef(BaseValidatorModel):
    ExtensionIdentifier: Optional[str] = None
    ActionName: Optional[str] = None
    Uri: Optional[str] = None
    RoleArn: Optional[str] = None
    ErrorMessage: Optional[str] = None
    ErrorCode: Optional[str] = None
    InvocationId: Optional[str] = None


class ActionTypeDef(BaseValidatorModel):
    Name: Optional[str] = None
    Description: Optional[str] = None
    Uri: Optional[str] = None
    RoleArn: Optional[str] = None


class ApplicationTypeDef(BaseValidatorModel):
    Id: Optional[str] = None
    Name: Optional[str] = None
    Description: Optional[str] = None


class AppliedExtensionTypeDef(BaseValidatorModel):
    ExtensionId: Optional[str] = None
    ExtensionAssociationId: Optional[str] = None
    VersionNumber: Optional[int] = None
    Parameters: Optional[Dict[str, str]] = None


BlobTypeDef = Union[IO[Any], StreamingBody, bytes, str]


class ConfigurationProfileSummaryTypeDef(BaseValidatorModel):
    ApplicationId: Optional[str] = None
    Id: Optional[str] = None
    Name: Optional[str] = None
    LocationUri: Optional[str] = None
    ValidatorTypes: Optional[List[ValidatorTypeType]] = None
    Type: Optional[str] = None


class ValidatorTypeDef(BaseValidatorModel):
    Type: ValidatorTypeType
    Content: str


# This class is the input for the 'create_application' function.
class CreateApplicationRequestTypeDef(BaseValidatorModel):
    Name: str
    Description: Optional[str] = None
    Tags: Optional[Dict[str, str]] = None


# This class is the input for the 'create_deployment_strategy' function.
class CreateDeploymentStrategyRequestTypeDef(BaseValidatorModel):
    Name: str
    DeploymentDurationInMinutes: int
    GrowthFactor: float
    Description: Optional[str] = None
    FinalBakeTimeInMinutes: Optional[int] = None
    GrowthType: Optional[GrowthTypeType] = None
    ReplicateTo: Optional[ReplicateToType] = None
    Tags: Optional[Dict[str, str]] = None


class MonitorTypeDef(BaseValidatorModel):
    AlarmArn: str
    AlarmRoleArn: Optional[str] = None


# This class is the input for the 'create_extension_association' function.
class CreateExtensionAssociationRequestTypeDef(BaseValidatorModel):
    ExtensionIdentifier: str
    ResourceIdentifier: str
    ExtensionVersionNumber: Optional[int] = None
    Parameters: Optional[Dict[str, str]] = None
    Tags: Optional[Dict[str, str]] = None


class ParameterTypeDef(BaseValidatorModel):
    Description: Optional[str] = None
    Required: Optional[bool] = None
    Dynamic: Optional[bool] = None


# This class is the input for the 'delete_application' function.
class DeleteApplicationRequestTypeDef(BaseValidatorModel):
    ApplicationId: str


# This class is the input for the 'delete_configuration_profile' function.
class DeleteConfigurationProfileRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    ConfigurationProfileId: str
    DeletionProtectionCheck: Optional[DeletionProtectionCheckType] = None


# This class is the input for the 'delete_deployment_strategy' function.
class DeleteDeploymentStrategyRequestTypeDef(BaseValidatorModel):
    DeploymentStrategyId: str


# This class is the input for the 'delete_environment' function.
class DeleteEnvironmentRequestTypeDef(BaseValidatorModel):
    EnvironmentId: str
    ApplicationId: str
    DeletionProtectionCheck: Optional[DeletionProtectionCheckType] = None


# This class is the input for the 'delete_extension_association' function.
class DeleteExtensionAssociationRequestTypeDef(BaseValidatorModel):
    ExtensionAssociationId: str


# This class is the input for the 'delete_extension' function.
class DeleteExtensionRequestTypeDef(BaseValidatorModel):
    ExtensionIdentifier: str
    VersionNumber: Optional[int] = None


# This class is the input for the 'delete_hosted_configuration_version' function.
class DeleteHostedConfigurationVersionRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    ConfigurationProfileId: str
    VersionNumber: int


class DeploymentStrategyTypeDef(BaseValidatorModel):
    Id: Optional[str] = None
    Name: Optional[str] = None
    Description: Optional[str] = None
    DeploymentDurationInMinutes: Optional[int] = None
    GrowthType: Optional[GrowthTypeType] = None
    GrowthFactor: Optional[float] = None
    FinalBakeTimeInMinutes: Optional[int] = None
    ReplicateTo: Optional[ReplicateToType] = None


class DeploymentSummaryTypeDef(BaseValidatorModel):
    DeploymentNumber: Optional[int] = None
    ConfigurationName: Optional[str] = None
    ConfigurationVersion: Optional[str] = None
    DeploymentDurationInMinutes: Optional[int] = None
    GrowthType: Optional[GrowthTypeType] = None
    GrowthFactor: Optional[float] = None
    FinalBakeTimeInMinutes: Optional[int] = None
    State: Optional[DeploymentStateType] = None
    PercentageComplete: Optional[float] = None
    StartedAt: Optional[datetime] = None
    CompletedAt: Optional[datetime] = None
    VersionLabel: Optional[str] = None


class ExtensionAssociationSummaryTypeDef(BaseValidatorModel):
    Id: Optional[str] = None
    ExtensionArn: Optional[str] = None
    ResourceArn: Optional[str] = None


class ExtensionSummaryTypeDef(BaseValidatorModel):
    Id: Optional[str] = None
    Name: Optional[str] = None
    VersionNumber: Optional[int] = None
    Arn: Optional[str] = None
    Description: Optional[str] = None


# This class is the input for the 'get_application' function.
class GetApplicationRequestTypeDef(BaseValidatorModel):
    ApplicationId: str


# This class is the input for the 'get_configuration_profile' function.
class GetConfigurationProfileRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    ConfigurationProfileId: str


# This class is the input for the 'get_configuration' function.
class GetConfigurationRequestTypeDef(BaseValidatorModel):
    Application: str
    Environment: str
    Configuration: str
    ClientId: str
    ClientConfigurationVersion: Optional[str] = None


# This class is the input for the 'get_deployment' function.
class GetDeploymentRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    EnvironmentId: str
    DeploymentNumber: int


class WaiterConfigTypeDef(BaseValidatorModel):
    Delay: Optional[int] = None
    MaxAttempts: Optional[int] = None


# This class is the input for the 'get_deployment_strategy' function.
class GetDeploymentStrategyRequestTypeDef(BaseValidatorModel):
    DeploymentStrategyId: str


# This class is the input for the 'get_environment' function.
class GetEnvironmentRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    EnvironmentId: str


# This class is the input for the 'get_extension_association' function.
class GetExtensionAssociationRequestTypeDef(BaseValidatorModel):
    ExtensionAssociationId: str


# This class is the input for the 'get_extension' function.
class GetExtensionRequestTypeDef(BaseValidatorModel):
    ExtensionIdentifier: str
    VersionNumber: Optional[int] = None


# This class is the input for the 'get_hosted_configuration_version' function.
class GetHostedConfigurationVersionRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    ConfigurationProfileId: str
    VersionNumber: int


class HostedConfigurationVersionSummaryTypeDef(BaseValidatorModel):
    ApplicationId: Optional[str] = None
    ConfigurationProfileId: Optional[str] = None
    VersionNumber: Optional[int] = None
    Description: Optional[str] = None
    ContentType: Optional[str] = None
    VersionLabel: Optional[str] = None
    KmsKeyArn: Optional[str] = None


class PaginatorConfigTypeDef(BaseValidatorModel):
    MaxItems: Optional[int] = None
    PageSize: Optional[int] = None
    StartingToken: Optional[str] = None


# This class is the input for the 'list_applications' function.
class ListApplicationsRequestTypeDef(BaseValidatorModel):
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None


# This class is the input for the 'list_configuration_profiles' function.
class ListConfigurationProfilesRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None
    Type: Optional[str] = None


# This class is the input for the 'list_deployment_strategies' function.
class ListDeploymentStrategiesRequestTypeDef(BaseValidatorModel):
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None


# This class is the input for the 'list_deployments' function.
class ListDeploymentsRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    EnvironmentId: str
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None


# This class is the input for the 'list_environments' function.
class ListEnvironmentsRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None


# This class is the input for the 'list_extension_associations' function.
class ListExtensionAssociationsRequestTypeDef(BaseValidatorModel):
    ResourceIdentifier: Optional[str] = None
    ExtensionIdentifier: Optional[str] = None
    ExtensionVersionNumber: Optional[int] = None
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None


# This class is the input for the 'list_extensions' function.
class ListExtensionsRequestTypeDef(BaseValidatorModel):
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None
    Name: Optional[str] = None


# This class is the input for the 'list_hosted_configuration_versions' function.
class ListHostedConfigurationVersionsRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    ConfigurationProfileId: str
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None
    VersionLabel: Optional[str] = None


# This class is the input for the 'list_tags_for_resource' function.
class ListTagsForResourceRequestTypeDef(BaseValidatorModel):
    ResourceArn: str


# This class is the input for the 'start_deployment' function.
class StartDeploymentRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    EnvironmentId: str
    DeploymentStrategyId: str
    ConfigurationProfileId: str
    ConfigurationVersion: str
    Description: Optional[str] = None
    Tags: Optional[Dict[str, str]] = None
    KmsKeyIdentifier: Optional[str] = None
    DynamicExtensionParameters: Optional[Dict[str, str]] = None


# This class is the input for the 'stop_deployment' function.
class StopDeploymentRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    EnvironmentId: str
    DeploymentNumber: int
    AllowRevert: Optional[bool] = None


# This class is the input for the 'tag_resource' function.
class TagResourceRequestTypeDef(BaseValidatorModel):
    ResourceArn: str
    Tags: Dict[str, str]


# This class is the input for the 'untag_resource' function.
class UntagResourceRequestTypeDef(BaseValidatorModel):
    ResourceArn: str
    TagKeys: List[str]


# This class is the input for the 'update_application' function.
class UpdateApplicationRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    Name: Optional[str] = None
    Description: Optional[str] = None


# This class is the input for the 'update_deployment_strategy' function.
class UpdateDeploymentStrategyRequestTypeDef(BaseValidatorModel):
    DeploymentStrategyId: str
    Description: Optional[str] = None
    DeploymentDurationInMinutes: Optional[int] = None
    FinalBakeTimeInMinutes: Optional[int] = None
    GrowthFactor: Optional[float] = None
    GrowthType: Optional[GrowthTypeType] = None


# This class is the input for the 'update_extension_association' function.
class UpdateExtensionAssociationRequestTypeDef(BaseValidatorModel):
    ExtensionAssociationId: str
    Parameters: Optional[Dict[str, str]] = None


# This class is the input for the 'validate_configuration' function.
class ValidateConfigurationRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    ConfigurationProfileId: str
    ConfigurationVersion: str


# This class is the input for the 'update_account_settings' function.
class UpdateAccountSettingsRequestTypeDef(BaseValidatorModel):
    DeletionProtection: Optional[DeletionProtectionSettingsTypeDef] = None


# This class is the output for the 'update_account_settings' function.
class AccountSettingsTypeDef(BaseValidatorModel):
    DeletionProtection: DeletionProtectionSettingsTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_application' function.
class ApplicationResponseTypeDef(BaseValidatorModel):
    Id: str
    Name: str
    Description: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_configuration' function.
class ConfigurationTypeDef(BaseValidatorModel):
    Content: StreamingBody
    ConfigurationVersion: str
    ContentType: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_deployment_strategy' function.
class DeploymentStrategyResponseTypeDef(BaseValidatorModel):
    Id: str
    Name: str
    Description: str
    DeploymentDurationInMinutes: int
    GrowthType: GrowthTypeType
    GrowthFactor: float
    FinalBakeTimeInMinutes: int
    ReplicateTo: ReplicateToType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_application' function.
class EmptyResponseMetadataTypeDef(BaseValidatorModel):
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_extension_association' function.
class ExtensionAssociationTypeDef(BaseValidatorModel):
    Id: str
    ExtensionArn: str
    ResourceArn: str
    Arn: str
    Parameters: Dict[str, str]
    ExtensionVersionNumber: int
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_hosted_configuration_version' function.
class HostedConfigurationVersionTypeDef(BaseValidatorModel):
    ApplicationId: str
    ConfigurationProfileId: str
    VersionNumber: int
    Description: str
    Content: StreamingBody
    ContentType: str
    VersionLabel: str
    KmsKeyArn: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_tags_for_resource' function.
class ResourceTagsTypeDef(BaseValidatorModel):
    Tags: Dict[str, str]
    ResponseMetadata: ResponseMetadataTypeDef


class DeploymentEventTypeDef(BaseValidatorModel):
    EventType: Optional[DeploymentEventTypeType] = None
    TriggeredBy: Optional[TriggeredByType] = None
    Description: Optional[str] = None
    ActionInvocations: Optional[List[ActionInvocationTypeDef]] = None
    OccurredAt: Optional[datetime] = None


# This class is the output for the 'list_applications' function.
class ApplicationsTypeDef(BaseValidatorModel):
    Items: List[ApplicationTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the input for the 'create_hosted_configuration_version' function.
class CreateHostedConfigurationVersionRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    ConfigurationProfileId: str
    Content: BlobTypeDef
    ContentType: str
    Description: Optional[str] = None
    LatestVersionNumber: Optional[int] = None
    VersionLabel: Optional[str] = None


# This class is the output for the 'list_configuration_profiles' function.
class ConfigurationProfilesTypeDef(BaseValidatorModel):
    Items: List[ConfigurationProfileSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'create_configuration_profile' function.
class ConfigurationProfileTypeDef(BaseValidatorModel):
    ApplicationId: str
    Id: str
    Name: str
    Description: str
    LocationUri: str
    RetrievalRoleArn: str
    Validators: List[ValidatorTypeDef]
    Type: str
    KmsKeyArn: str
    KmsKeyIdentifier: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'create_configuration_profile' function.
class CreateConfigurationProfileRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    Name: str
    LocationUri: str
    Description: Optional[str] = None
    RetrievalRoleArn: Optional[str] = None
    Validators: Optional[List[ValidatorTypeDef]] = None
    Tags: Optional[Dict[str, str]] = None
    Type: Optional[str] = None
    KmsKeyIdentifier: Optional[str] = None


# This class is the input for the 'update_configuration_profile' function.
class UpdateConfigurationProfileRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    ConfigurationProfileId: str
    Name: Optional[str] = None
    Description: Optional[str] = None
    RetrievalRoleArn: Optional[str] = None
    Validators: Optional[List[ValidatorTypeDef]] = None
    KmsKeyIdentifier: Optional[str] = None


# This class is the input for the 'create_environment' function.
class CreateEnvironmentRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    Name: str
    Description: Optional[str] = None
    Monitors: Optional[List[MonitorTypeDef]] = None
    Tags: Optional[Dict[str, str]] = None


# This class is the output for the 'create_environment' function.
class EnvironmentResponseTypeDef(BaseValidatorModel):
    ApplicationId: str
    Id: str
    Name: str
    Description: str
    State: EnvironmentStateType
    Monitors: List[MonitorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class EnvironmentTypeDef(BaseValidatorModel):
    ApplicationId: Optional[str] = None
    Id: Optional[str] = None
    Name: Optional[str] = None
    Description: Optional[str] = None
    State: Optional[EnvironmentStateType] = None
    Monitors: Optional[List[MonitorTypeDef]] = None


# This class is the input for the 'update_environment' function.
class UpdateEnvironmentRequestTypeDef(BaseValidatorModel):
    ApplicationId: str
    EnvironmentId: str
    Name: Optional[str] = None
    Description: Optional[str] = None
    Monitors: Optional[List[MonitorTypeDef]] = None


# This class is the input for the 'create_extension' function.
class CreateExtensionRequestTypeDef(BaseValidatorModel):
    Name: str
    Actions: Dict[ActionPointType, List[ActionTypeDef]]
    Description: Optional[str] = None
    Parameters: Optional[Dict[str, ParameterTypeDef]] = None
    Tags: Optional[Dict[str, str]] = None
    LatestVersionNumber: Optional[int] = None


# This class is the output for the 'create_extension' function.
class ExtensionTypeDef(BaseValidatorModel):
    Id: str
    Name: str
    VersionNumber: int
    Arn: str
    Description: str
    Actions: Dict[ActionPointType, List[ActionTypeDef]]
    Parameters: Dict[str, ParameterTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'update_extension' function.
class UpdateExtensionRequestTypeDef(BaseValidatorModel):
    ExtensionIdentifier: str
    Description: Optional[str] = None
    Actions: Optional[Dict[ActionPointType, List[ActionTypeDef]]] = None
    Parameters: Optional[Dict[str, ParameterTypeDef]] = None
    VersionNumber: Optional[int] = None


# This class is the output for the 'list_deployment_strategies' function.
class DeploymentStrategiesTypeDef(BaseValidatorModel):
    Items: List[DeploymentStrategyTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'list_deployments' function.
class DeploymentsTypeDef(BaseValidatorModel):
    Items: List[DeploymentSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'list_extension_associations' function.
class ExtensionAssociationsTypeDef(BaseValidatorModel):
    Items: List[ExtensionAssociationSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'list_extensions' function.
class ExtensionsTypeDef(BaseValidatorModel):
    Items: List[ExtensionSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


class GetDeploymentRequestWaitTypeDef(BaseValidatorModel):
    ApplicationId: str
    EnvironmentId: str
    DeploymentNumber: int
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


class GetEnvironmentRequestWaitTypeDef(BaseValidatorModel):
    ApplicationId: str
    EnvironmentId: str
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


# This class is the output for the 'list_hosted_configuration_versions' function.
class HostedConfigurationVersionsTypeDef(BaseValidatorModel):
    Items: List[HostedConfigurationVersionSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


class ListApplicationsRequestPaginateTypeDef(BaseValidatorModel):
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListConfigurationProfilesRequestPaginateTypeDef(BaseValidatorModel):
    ApplicationId: str
    Type: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListDeploymentStrategiesRequestPaginateTypeDef(BaseValidatorModel):
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListDeploymentsRequestPaginateTypeDef(BaseValidatorModel):
    ApplicationId: str
    EnvironmentId: str
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListEnvironmentsRequestPaginateTypeDef(BaseValidatorModel):
    ApplicationId: str
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListExtensionAssociationsRequestPaginateTypeDef(BaseValidatorModel):
    ResourceIdentifier: Optional[str] = None
    ExtensionIdentifier: Optional[str] = None
    ExtensionVersionNumber: Optional[int] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListExtensionsRequestPaginateTypeDef(BaseValidatorModel):
    Name: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListHostedConfigurationVersionsRequestPaginateTypeDef(BaseValidatorModel):
    ApplicationId: str
    ConfigurationProfileId: str
    VersionLabel: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the output for the 'get_deployment' function.
class DeploymentTypeDef(BaseValidatorModel):
    ApplicationId: str
    EnvironmentId: str
    DeploymentStrategyId: str
    ConfigurationProfileId: str
    DeploymentNumber: int
    ConfigurationName: str
    ConfigurationLocationUri: str
    ConfigurationVersion: str
    Description: str
    DeploymentDurationInMinutes: int
    GrowthType: GrowthTypeType
    GrowthFactor: float
    FinalBakeTimeInMinutes: int
    State: DeploymentStateType
    EventLog: List[DeploymentEventTypeDef]
    PercentageComplete: float
    StartedAt: datetime
    CompletedAt: datetime
    AppliedExtensions: List[AppliedExtensionTypeDef]
    KmsKeyArn: str
    KmsKeyIdentifier: str
    VersionLabel: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_environments' function.
class EnvironmentsTypeDef(BaseValidatorModel):
    Items: List[EnvironmentTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None
