# This file is auto-generated by aws_resource_validator.generator.pipeline_b.
# Do not edit manually; run `arv-generate pipeline-b` to refresh it.
from datetime import datetime
from decimal import Decimal
from typing import (
    Any,
    Callable,
    Dict,
    FrozenSet,
    IO,
    List,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    Union,
)

from botocore.client import BaseClient
from botocore.response import StreamingBody
from pydantic import Field

from aws_resource_validator.core.base_validator_model import BaseValidatorModel, EventStream
from aws_resource_validator.pydantic_models.cognito_sync.cognito_sync_constants import *  # noqa: F401,F403

# Optional boto3 symbols — imported lazily so services that don't need them
# aren't forced to pull in boto3 at import time.
try:
    from boto3.dynamodb.conditions import ConditionBase  # noqa: F401
except ImportError:  # pragma: no cover
    ConditionBase = Any  # type: ignore[assignment,misc]
try:
    from boto3.s3.transfer import TransferConfig  # noqa: F401
except ImportError:  # pragma: no cover
    TransferConfig = Any  # type: ignore[assignment,misc]


# This class is the input for the 'bulk_publish' function.
class BulkPublishRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str


class ResponseMetadataTypeDef(BaseValidatorModel):
    RequestId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, str]
    RetryAttempts: int
    HostId: Optional[str] = None


class CognitoStreamsTypeDef(BaseValidatorModel):
    StreamName: Optional[str] = None
    RoleArn: Optional[str] = None
    StreamingStatus: Optional[StreamingStatusType] = None


class DatasetTypeDef(BaseValidatorModel):
    IdentityId: Optional[str] = None
    DatasetName: Optional[str] = None
    CreationDate: Optional[datetime] = None
    LastModifiedDate: Optional[datetime] = None
    LastModifiedBy: Optional[str] = None
    DataStorage: Optional[int] = None
    NumRecords: Optional[int] = None


# This class is the input for the 'delete_dataset' function.
class DeleteDatasetRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    IdentityId: str
    DatasetName: str


# This class is the input for the 'describe_dataset' function.
class DescribeDatasetRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    IdentityId: str
    DatasetName: str


# This class is the input for the 'describe_identity_pool_usage' function.
class DescribeIdentityPoolUsageRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str


class IdentityPoolUsageTypeDef(BaseValidatorModel):
    IdentityPoolId: Optional[str] = None
    SyncSessionsCount: Optional[int] = None
    DataStorage: Optional[int] = None
    LastModifiedDate: Optional[datetime] = None


# This class is the input for the 'describe_identity_usage' function.
class DescribeIdentityUsageRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    IdentityId: str


class IdentityUsageTypeDef(BaseValidatorModel):
    IdentityId: Optional[str] = None
    IdentityPoolId: Optional[str] = None
    LastModifiedDate: Optional[datetime] = None
    DatasetCount: Optional[int] = None
    DataStorage: Optional[int] = None


# This class is the input for the 'get_bulk_publish_details' function.
class GetBulkPublishDetailsRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str


# This class is the input for the 'get_cognito_events' function.
class GetCognitoEventsRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str


# This class is the input for the 'get_identity_pool_configuration' function.
class GetIdentityPoolConfigurationRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str


class PushSyncOutputTypeDef(BaseValidatorModel):
    ApplicationArns: Optional[List[str]] = None
    RoleArn: Optional[str] = None


# This class is the input for the 'list_datasets' function.
class ListDatasetsRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    IdentityId: str
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


# This class is the input for the 'list_identity_pool_usage' function.
class ListIdentityPoolUsageRequestTypeDef(BaseValidatorModel):
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


# This class is the input for the 'list_records' function.
class ListRecordsRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    IdentityId: str
    DatasetName: str
    LastSyncCount: Optional[int] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None
    SyncSessionToken: Optional[str] = None


class RecordTypeDef(BaseValidatorModel):
    Key: Optional[str] = None
    Value: Optional[str] = None
    SyncCount: Optional[int] = None
    LastModifiedDate: Optional[datetime] = None
    LastModifiedBy: Optional[str] = None
    DeviceLastModifiedDate: Optional[datetime] = None


class PushSyncTypeDef(BaseValidatorModel):
    ApplicationArns: Optional[List[str]] = None
    RoleArn: Optional[str] = None


TimestampTypeDef = Union[datetime, str]


# This class is the input for the 'register_device' function.
class RegisterDeviceRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    IdentityId: str
    Platform: PlatformType
    Token: str


# This class is the input for the 'set_cognito_events' function.
class SetCognitoEventsRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    Events: Dict[str, str]


class SubscribeToDatasetRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    IdentityId: str
    DatasetName: str
    DeviceId: str


class UnsubscribeFromDatasetRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    IdentityId: str
    DatasetName: str
    DeviceId: str


# This class is the output for the 'bulk_publish' function.
class BulkPublishResponseTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'set_cognito_events' function.
class EmptyResponseMetadataTypeDef(BaseValidatorModel):
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_bulk_publish_details' function.
class GetBulkPublishDetailsResponseTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    BulkPublishStartTime: datetime
    BulkPublishCompleteTime: datetime
    BulkPublishStatus: BulkPublishStatusType
    FailureMessage: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_cognito_events' function.
class GetCognitoEventsResponseTypeDef(BaseValidatorModel):
    Events: Dict[str, str]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'register_device' function.
class RegisterDeviceResponseTypeDef(BaseValidatorModel):
    DeviceId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_dataset' function.
class DeleteDatasetResponseTypeDef(BaseValidatorModel):
    Dataset: DatasetTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_dataset' function.
class DescribeDatasetResponseTypeDef(BaseValidatorModel):
    Dataset: DatasetTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_datasets' function.
class ListDatasetsResponseTypeDef(BaseValidatorModel):
    Datasets: List[DatasetTypeDef]
    Count: int
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'describe_identity_pool_usage' function.
class DescribeIdentityPoolUsageResponseTypeDef(BaseValidatorModel):
    IdentityPoolUsage: IdentityPoolUsageTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_identity_pool_usage' function.
class ListIdentityPoolUsageResponseTypeDef(BaseValidatorModel):
    IdentityPoolUsages: List[IdentityPoolUsageTypeDef]
    MaxResults: int
    Count: int
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'describe_identity_usage' function.
class DescribeIdentityUsageResponseTypeDef(BaseValidatorModel):
    IdentityUsage: IdentityUsageTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_identity_pool_configuration' function.
class GetIdentityPoolConfigurationResponseTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    PushSync: PushSyncOutputTypeDef
    CognitoStreams: CognitoStreamsTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'set_identity_pool_configuration' function.
class SetIdentityPoolConfigurationResponseTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    PushSync: PushSyncOutputTypeDef
    CognitoStreams: CognitoStreamsTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_records' function.
class ListRecordsResponseTypeDef(BaseValidatorModel):
    Records: List[RecordTypeDef]
    Count: int
    DatasetSyncCount: int
    LastModifiedBy: str
    MergedDatasetNames: List[str]
    DatasetExists: bool
    DatasetDeletedAfterRequestedSyncCount: bool
    SyncSessionToken: str
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'update_records' function.
class UpdateRecordsResponseTypeDef(BaseValidatorModel):
    Records: List[RecordTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


PushSyncUnionTypeDef = Union[PushSyncOutputTypeDef, PushSyncTypeDef]


class RecordPatchTypeDef(BaseValidatorModel):
    Op: OperationType
    Key: str
    SyncCount: int
    Value: Optional[str] = None
    DeviceLastModifiedDate: Optional[TimestampTypeDef] = None


# This class is the input for the 'set_identity_pool_configuration' function.
class SetIdentityPoolConfigurationRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    PushSync: Optional[PushSyncUnionTypeDef] = None
    CognitoStreams: Optional[CognitoStreamsTypeDef] = None


# This class is the input for the 'update_records' function.
class UpdateRecordsRequestTypeDef(BaseValidatorModel):
    IdentityPoolId: str
    IdentityId: str
    DatasetName: str
    SyncSessionToken: str
    DeviceId: Optional[str] = None
    RecordPatches: Optional[List[RecordPatchTypeDef]] = None
    ClientContext: Optional[str] = None
