# This file is auto-generated by aws_resource_validator.generator.pipeline_b.
# Do not edit manually; run `arv-generate pipeline-b` to refresh it.
from datetime import datetime
from decimal import Decimal
from typing import (
    Annotated,
    Any,
    Callable,
    Dict,
    FrozenSet,
    IO,
    List,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    Union,
)

from botocore.client import BaseClient
from botocore.response import StreamingBody
from pydantic import Field

from aws_resource_validator.core.base_validator_model import BaseValidatorModel, EventStream
from aws_resource_validator.core.pattern_validation import aws_field_pattern as _aws_pattern
from aws_resource_validator.pydantic_models.comprehend.comprehend_constants import *  # noqa: F401,F403

# Optional boto3 symbols — imported lazily so services that don't need them
# aren't forced to pull in boto3 at import time.
try:
    from boto3.dynamodb.conditions import ConditionBase  # noqa: F401
except ImportError:  # pragma: no cover
    ConditionBase = Any  # type: ignore[assignment,misc]
try:
    from boto3.s3.transfer import TransferConfig  # noqa: F401
except ImportError:  # pragma: no cover
    TransferConfig = Any  # type: ignore[assignment,misc]


class AugmentedManifestsListItemOutputTypeDef(BaseValidatorModel):
    S3Uri: str
    AttributeNames: List[str]
    Split: Optional[SplitType] = None
    AnnotationDataS3Uri: Optional[str] = None
    SourceDocumentsS3Uri: Optional[str] = None
    DocumentType: Optional[AugmentedManifestsDocumentTypeFormatType] = None


class AugmentedManifestsListItemTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("Comprehend", "S3Uri")]
    AttributeNames: List[Annotated[str, _aws_pattern("Comprehend", "AttributeNamesListItem")]]
    Split: Optional[SplitType] = None
    AnnotationDataS3Uri: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None
    SourceDocumentsS3Uri: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None
    DocumentType: Optional[AugmentedManifestsDocumentTypeFormatType] = None


class DominantLanguageTypeDef(BaseValidatorModel):
    LanguageCode: Optional[str] = None
    Score: Optional[float] = None


# This class is the input for the 'batch_detect_dominant_language' function.
class BatchDetectDominantLanguageRequestTypeDef(BaseValidatorModel):
    TextList: List[str]


class BatchItemErrorTypeDef(BaseValidatorModel):
    Index: Optional[int] = None
    ErrorCode: Optional[str] = None
    ErrorMessage: Optional[str] = None


class ResponseMetadataTypeDef(BaseValidatorModel):
    RequestId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, str]
    RetryAttempts: int
    HostId: Optional[str] = None


# This class is the input for the 'batch_detect_entities' function.
class BatchDetectEntitiesRequestTypeDef(BaseValidatorModel):
    TextList: List[str]
    LanguageCode: LanguageCodeType


class KeyPhraseTypeDef(BaseValidatorModel):
    Score: Optional[float] = None
    Text: Optional[str] = None
    BeginOffset: Optional[int] = None
    EndOffset: Optional[int] = None


# This class is the input for the 'batch_detect_key_phrases' function.
class BatchDetectKeyPhrasesRequestTypeDef(BaseValidatorModel):
    TextList: List[str]
    LanguageCode: LanguageCodeType


class SentimentScoreTypeDef(BaseValidatorModel):
    Positive: Optional[float] = None
    Negative: Optional[float] = None
    Neutral: Optional[float] = None
    Mixed: Optional[float] = None


# This class is the input for the 'batch_detect_sentiment' function.
class BatchDetectSentimentRequestTypeDef(BaseValidatorModel):
    TextList: List[str]
    LanguageCode: LanguageCodeType


# This class is the input for the 'batch_detect_syntax' function.
class BatchDetectSyntaxRequestTypeDef(BaseValidatorModel):
    TextList: List[str]
    LanguageCode: SyntaxLanguageCodeType


# This class is the input for the 'batch_detect_targeted_sentiment' function.
class BatchDetectTargetedSentimentRequestTypeDef(BaseValidatorModel):
    TextList: List[str]
    LanguageCode: LanguageCodeType


BlobTypeDef = Union[IO[Any], StreamingBody, bytes, str]


class ChildBlockTypeDef(BaseValidatorModel):
    ChildBlockId: Optional[str] = None
    BeginOffset: Optional[int] = None
    EndOffset: Optional[int] = None


class RelationshipsListItemTypeDef(BaseValidatorModel):
    Ids: Optional[List[str]] = None
    Type: Optional[Literal["CHILD"]] = None


class BoundingBoxTypeDef(BaseValidatorModel):
    Height: Optional[float] = None
    Left: Optional[float] = None
    Top: Optional[float] = None
    Width: Optional[float] = None


class ClassifierEvaluationMetricsTypeDef(BaseValidatorModel):
    Accuracy: Optional[float] = None
    Precision: Optional[float] = None
    Recall: Optional[float] = None
    F1Score: Optional[float] = None
    MicroPrecision: Optional[float] = None
    MicroRecall: Optional[float] = None
    MicroF1Score: Optional[float] = None
    HammingLoss: Optional[float] = None


class DocumentClassTypeDef(BaseValidatorModel):
    Name: Optional[str] = None
    Score: Optional[float] = None
    Page: Optional[int] = None


class DocumentLabelTypeDef(BaseValidatorModel):
    Name: Optional[str] = None
    Score: Optional[float] = None
    Page: Optional[int] = None


class DocumentTypeListItemTypeDef(BaseValidatorModel):
    Page: Optional[int] = None
    Type: Optional[DocumentTypeType] = None


class ErrorsListItemTypeDef(BaseValidatorModel):
    Page: Optional[int] = None
    ErrorCode: Optional[PageBasedErrorCodeType] = None
    ErrorMessage: Optional[str] = None


class WarningsListItemTypeDef(BaseValidatorModel):
    Page: Optional[int] = None
    WarnCode: Optional[PageBasedWarningCodeType] = None
    WarnMessage: Optional[str] = None


# This class is the input for the 'contains_pii_entities' function.
class ContainsPiiEntitiesRequestTypeDef(BaseValidatorModel):
    Text: str
    LanguageCode: LanguageCodeType


class EntityLabelTypeDef(BaseValidatorModel):
    Name: Optional[PiiEntityTypeType] = None
    Score: Optional[float] = None


class TagTypeDef(BaseValidatorModel):
    Key: str
    Value: Optional[str] = None


class DocumentClassifierOutputDataConfigTypeDef(BaseValidatorModel):
    S3Uri: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None
    KmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    FlywheelStatsS3Prefix: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None


class VpcConfigOutputTypeDef(BaseValidatorModel):
    SecurityGroupIds: List[str]
    Subnets: List[str]


class VpcConfigTypeDef(BaseValidatorModel):
    SecurityGroupIds: List[Annotated[str, _aws_pattern("Comprehend", "SecurityGroupId")]]
    Subnets: List[Annotated[str, _aws_pattern("Comprehend", "SubnetId")]]


class DatasetAugmentedManifestsListItemTypeDef(BaseValidatorModel):
    AttributeNames: List[Annotated[str, _aws_pattern("Comprehend", "AttributeNamesListItem")]]
    S3Uri: Annotated[str, _aws_pattern("Comprehend", "S3Uri")]
    AnnotationDataS3Uri: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None
    SourceDocumentsS3Uri: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None
    DocumentType: Optional[AugmentedManifestsDocumentTypeFormatType] = None


class DatasetDocumentClassifierInputDataConfigTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("Comprehend", "S3Uri")]
    LabelDelimiter: Optional[Annotated[str, _aws_pattern("Comprehend", "LabelDelimiter")]] = None


class DatasetEntityRecognizerAnnotationsTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("Comprehend", "S3Uri")]


class DatasetEntityRecognizerDocumentsTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("Comprehend", "S3Uri")]
    InputFormat: Optional[InputFormatType] = None


class DatasetEntityRecognizerEntityListTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("Comprehend", "S3Uri")]


TimestampTypeDef = Union[datetime, str]


class DatasetPropertiesTypeDef(BaseValidatorModel):
    DatasetArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendDatasetArn")]] = None
    DatasetName: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArnName")]] = None
    DatasetType: Optional[DatasetTypeType] = None
    DatasetS3Uri: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None
    Description: Optional[Annotated[str, _aws_pattern("Comprehend", "Description")]] = None
    Status: Optional[DatasetStatusType] = None
    Message: Optional[str] = None
    NumberOfDocuments: Optional[int] = None
    CreationTime: Optional[datetime] = None
    EndTime: Optional[datetime] = None


class DeleteDocumentClassifierRequestTypeDef(BaseValidatorModel):
    DocumentClassifierArn: Annotated[str, _aws_pattern("Comprehend", "DocumentClassifierArn")]


class DeleteEndpointRequestTypeDef(BaseValidatorModel):
    EndpointArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendEndpointArn")]


class DeleteEntityRecognizerRequestTypeDef(BaseValidatorModel):
    EntityRecognizerArn: Annotated[str, _aws_pattern("Comprehend", "EntityRecognizerArn")]


class DeleteFlywheelRequestTypeDef(BaseValidatorModel):
    FlywheelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]


class DeleteResourcePolicyRequestTypeDef(BaseValidatorModel):
    ResourceArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]
    PolicyRevisionId: Optional[Annotated[str, _aws_pattern("Comprehend", "PolicyRevisionId")]] = None


# This class is the input for the 'describe_dataset' function.
class DescribeDatasetRequestTypeDef(BaseValidatorModel):
    DatasetArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendDatasetArn")]


# This class is the input for the 'describe_document_classification_job' function.
class DescribeDocumentClassificationJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'describe_document_classifier' function.
class DescribeDocumentClassifierRequestTypeDef(BaseValidatorModel):
    DocumentClassifierArn: Annotated[str, _aws_pattern("Comprehend", "DocumentClassifierArn")]


# This class is the input for the 'describe_dominant_language_detection_job' function.
class DescribeDominantLanguageDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'describe_endpoint' function.
class DescribeEndpointRequestTypeDef(BaseValidatorModel):
    EndpointArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendEndpointArn")]


class EndpointPropertiesTypeDef(BaseValidatorModel):
    EndpointArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendEndpointArn")]] = None
    Status: Optional[EndpointStatusType] = None
    Message: Optional[str] = None
    ModelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]] = None
    DesiredModelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]] = None
    DesiredInferenceUnits: Optional[int] = None
    CurrentInferenceUnits: Optional[int] = None
    CreationTime: Optional[datetime] = None
    LastModifiedTime: Optional[datetime] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    DesiredDataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    FlywheelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]] = None


# This class is the input for the 'describe_entities_detection_job' function.
class DescribeEntitiesDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'describe_entity_recognizer' function.
class DescribeEntityRecognizerRequestTypeDef(BaseValidatorModel):
    EntityRecognizerArn: Annotated[str, _aws_pattern("Comprehend", "EntityRecognizerArn")]


# This class is the input for the 'describe_events_detection_job' function.
class DescribeEventsDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'describe_flywheel_iteration' function.
class DescribeFlywheelIterationRequestTypeDef(BaseValidatorModel):
    FlywheelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]
    FlywheelIterationId: Annotated[str, _aws_pattern("Comprehend", "FlywheelIterationId")]


# This class is the input for the 'describe_flywheel' function.
class DescribeFlywheelRequestTypeDef(BaseValidatorModel):
    FlywheelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]


# This class is the input for the 'describe_key_phrases_detection_job' function.
class DescribeKeyPhrasesDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'describe_pii_entities_detection_job' function.
class DescribePiiEntitiesDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'describe_resource_policy' function.
class DescribeResourcePolicyRequestTypeDef(BaseValidatorModel):
    ResourceArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]


# This class is the input for the 'describe_sentiment_detection_job' function.
class DescribeSentimentDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'describe_targeted_sentiment_detection_job' function.
class DescribeTargetedSentimentDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'describe_topics_detection_job' function.
class DescribeTopicsDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'detect_dominant_language' function.
class DetectDominantLanguageRequestTypeDef(BaseValidatorModel):
    Text: str


# This class is the input for the 'detect_key_phrases' function.
class DetectKeyPhrasesRequestTypeDef(BaseValidatorModel):
    Text: str
    LanguageCode: LanguageCodeType


# This class is the input for the 'detect_pii_entities' function.
class DetectPiiEntitiesRequestTypeDef(BaseValidatorModel):
    Text: str
    LanguageCode: LanguageCodeType


class PiiEntityTypeDef(BaseValidatorModel):
    Score: Optional[float] = None
    Type: Optional[PiiEntityTypeType] = None
    BeginOffset: Optional[int] = None
    EndOffset: Optional[int] = None


# This class is the input for the 'detect_sentiment' function.
class DetectSentimentRequestTypeDef(BaseValidatorModel):
    Text: str
    LanguageCode: LanguageCodeType


# This class is the input for the 'detect_syntax' function.
class DetectSyntaxRequestTypeDef(BaseValidatorModel):
    Text: str
    LanguageCode: SyntaxLanguageCodeType


# This class is the input for the 'detect_targeted_sentiment' function.
class DetectTargetedSentimentRequestTypeDef(BaseValidatorModel):
    Text: str
    LanguageCode: LanguageCodeType


class TextSegmentTypeDef(BaseValidatorModel):
    Text: str


class DocumentClassificationConfigOutputTypeDef(BaseValidatorModel):
    Mode: DocumentClassifierModeType
    Labels: Optional[List[str]] = None


class DocumentClassificationConfigTypeDef(BaseValidatorModel):
    Mode: DocumentClassifierModeType
    Labels: Optional[List[Annotated[str, _aws_pattern("Comprehend", "LabelListItem")]]] = None


class OutputDataConfigTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("Comprehend", "S3Uri")]
    KmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None


class DocumentClassifierDocumentsTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("Comprehend", "S3Uri")]
    TestS3Uri: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None


class DocumentReaderConfigOutputTypeDef(BaseValidatorModel):
    DocumentReadAction: DocumentReadActionType
    DocumentReadMode: Optional[DocumentReadModeType] = None
    FeatureTypes: Optional[List[DocumentReadFeatureTypesType]] = None


class DocumentReaderConfigTypeDef(BaseValidatorModel):
    DocumentReadAction: DocumentReadActionType
    DocumentReadMode: Optional[DocumentReadModeType] = None
    FeatureTypes: Optional[List[DocumentReadFeatureTypesType]] = None


class DocumentClassifierSummaryTypeDef(BaseValidatorModel):
    DocumentClassifierName: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArnName")]] = None
    NumberOfVersions: Optional[int] = None
    LatestVersionCreatedAt: Optional[datetime] = None
    LatestVersionName: Optional[Annotated[str, _aws_pattern("Comprehend", "VersionName")]] = None
    LatestVersionStatus: Optional[ModelStatusType] = None


class ExtractedCharactersListItemTypeDef(BaseValidatorModel):
    Page: Optional[int] = None
    Count: Optional[int] = None


class EntityTypesListItemTypeDef(BaseValidatorModel):
    Type: Annotated[str, _aws_pattern("Comprehend", "EntityTypeName")]


class EntityRecognizerAnnotationsTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("Comprehend", "S3Uri")]
    TestS3Uri: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None


class EntityRecognizerDocumentsTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("Comprehend", "S3Uri")]
    TestS3Uri: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None
    InputFormat: Optional[InputFormatType] = None


class EntityRecognizerEntityListTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("Comprehend", "S3Uri")]


class EntityRecognizerEvaluationMetricsTypeDef(BaseValidatorModel):
    Precision: Optional[float] = None
    Recall: Optional[float] = None
    F1Score: Optional[float] = None


class EntityTypesEvaluationMetricsTypeDef(BaseValidatorModel):
    Precision: Optional[float] = None
    Recall: Optional[float] = None
    F1Score: Optional[float] = None


class EntityRecognizerOutputDataConfigTypeDef(BaseValidatorModel):
    FlywheelStatsS3Prefix: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None


class EntityRecognizerSummaryTypeDef(BaseValidatorModel):
    RecognizerName: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArnName")]] = None
    NumberOfVersions: Optional[int] = None
    LatestVersionCreatedAt: Optional[datetime] = None
    LatestVersionName: Optional[Annotated[str, _aws_pattern("Comprehend", "VersionName")]] = None
    LatestVersionStatus: Optional[ModelStatusType] = None


class FlywheelModelEvaluationMetricsTypeDef(BaseValidatorModel):
    AverageF1Score: Optional[float] = None
    AveragePrecision: Optional[float] = None
    AverageRecall: Optional[float] = None
    AverageAccuracy: Optional[float] = None


class FlywheelSummaryTypeDef(BaseValidatorModel):
    FlywheelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]] = None
    ActiveModelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]] = None
    DataLakeS3Uri: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None
    Status: Optional[FlywheelStatusType] = None
    ModelType: Optional[ModelTypeType] = None
    Message: Optional[str] = None
    CreationTime: Optional[datetime] = None
    LastModifiedTime: Optional[datetime] = None
    LatestFlywheelIteration: Optional[Annotated[str, _aws_pattern("Comprehend", "FlywheelIterationId")]] = None


class PointTypeDef(BaseValidatorModel):
    X: Optional[float] = None
    Y: Optional[float] = None


class PaginatorConfigTypeDef(BaseValidatorModel):
    MaxItems: Optional[int] = None
    PageSize: Optional[int] = None
    StartingToken: Optional[str] = None


# This class is the input for the 'list_document_classifier_summaries' function.
class ListDocumentClassifierSummariesRequestTypeDef(BaseValidatorModel):
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


# This class is the input for the 'list_entity_recognizer_summaries' function.
class ListEntityRecognizerSummariesRequestTypeDef(BaseValidatorModel):
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


# This class is the input for the 'list_tags_for_resource' function.
class ListTagsForResourceRequestTypeDef(BaseValidatorModel):
    ResourceArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]


class PartOfSpeechTagTypeDef(BaseValidatorModel):
    Tag: Optional[PartOfSpeechTagTypeType] = None
    Score: Optional[float] = None


class PiiOutputDataConfigTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("Comprehend", "S3Uri")]
    KmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None


class RedactionConfigOutputTypeDef(BaseValidatorModel):
    PiiEntityTypes: Optional[List[PiiEntityTypeType]] = None
    MaskMode: Optional[PiiEntitiesDetectionMaskModeType] = None
    MaskCharacter: Optional[str] = None


# This class is the input for the 'put_resource_policy' function.
class PutResourcePolicyRequestTypeDef(BaseValidatorModel):
    ResourceArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]
    ResourcePolicy: Annotated[str, _aws_pattern("Comprehend", "Policy")]
    PolicyRevisionId: Optional[Annotated[str, _aws_pattern("Comprehend", "PolicyRevisionId")]] = None


class RedactionConfigTypeDef(BaseValidatorModel):
    PiiEntityTypes: Optional[List[PiiEntityTypeType]] = None
    MaskMode: Optional[PiiEntitiesDetectionMaskModeType] = None
    MaskCharacter: Optional[Annotated[str, _aws_pattern("Comprehend", "MaskCharacter")]] = None


# This class is the input for the 'start_flywheel_iteration' function.
class StartFlywheelIterationRequestTypeDef(BaseValidatorModel):
    FlywheelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None


# This class is the input for the 'stop_dominant_language_detection_job' function.
class StopDominantLanguageDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'stop_entities_detection_job' function.
class StopEntitiesDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'stop_events_detection_job' function.
class StopEventsDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'stop_key_phrases_detection_job' function.
class StopKeyPhrasesDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'stop_pii_entities_detection_job' function.
class StopPiiEntitiesDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'stop_sentiment_detection_job' function.
class StopSentimentDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


# This class is the input for the 'stop_targeted_sentiment_detection_job' function.
class StopTargetedSentimentDetectionJobRequestTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]


class StopTrainingDocumentClassifierRequestTypeDef(BaseValidatorModel):
    DocumentClassifierArn: Annotated[str, _aws_pattern("Comprehend", "DocumentClassifierArn")]


class StopTrainingEntityRecognizerRequestTypeDef(BaseValidatorModel):
    EntityRecognizerArn: Annotated[str, _aws_pattern("Comprehend", "EntityRecognizerArn")]


class ToxicContentTypeDef(BaseValidatorModel):
    Name: Optional[ToxicContentTypeType] = None
    Score: Optional[float] = None


class UntagResourceRequestTypeDef(BaseValidatorModel):
    ResourceArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]
    TagKeys: List[str]


# This class is the input for the 'update_endpoint' function.
class UpdateEndpointRequestTypeDef(BaseValidatorModel):
    EndpointArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendEndpointArn")]
    DesiredModelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]] = None
    DesiredInferenceUnits: Optional[int] = None
    DesiredDataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    FlywheelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]] = None


class BatchDetectDominantLanguageItemResultTypeDef(BaseValidatorModel):
    Index: Optional[int] = None
    Languages: Optional[List[DominantLanguageTypeDef]] = None


# This class is the output for the 'create_dataset' function.
class CreateDatasetResponseTypeDef(BaseValidatorModel):
    DatasetArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendDatasetArn")]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_document_classifier' function.
class CreateDocumentClassifierResponseTypeDef(BaseValidatorModel):
    DocumentClassifierArn: Annotated[str, _aws_pattern("Comprehend", "DocumentClassifierArn")]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_endpoint' function.
class CreateEndpointResponseTypeDef(BaseValidatorModel):
    EndpointArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendEndpointArn")]
    ModelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_entity_recognizer' function.
class CreateEntityRecognizerResponseTypeDef(BaseValidatorModel):
    EntityRecognizerArn: Annotated[str, _aws_pattern("Comprehend", "EntityRecognizerArn")]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_flywheel' function.
class CreateFlywheelResponseTypeDef(BaseValidatorModel):
    FlywheelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]
    ActiveModelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_resource_policy' function.
class DescribeResourcePolicyResponseTypeDef(BaseValidatorModel):
    ResourcePolicy: Annotated[str, _aws_pattern("Comprehend", "Policy")]
    CreationTime: datetime
    LastModifiedTime: datetime
    PolicyRevisionId: Annotated[str, _aws_pattern("Comprehend", "PolicyRevisionId")]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'detect_dominant_language' function.
class DetectDominantLanguageResponseTypeDef(BaseValidatorModel):
    Languages: List[DominantLanguageTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'import_model' function.
class ImportModelResponseTypeDef(BaseValidatorModel):
    ModelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'put_resource_policy' function.
class PutResourcePolicyResponseTypeDef(BaseValidatorModel):
    PolicyRevisionId: Annotated[str, _aws_pattern("Comprehend", "PolicyRevisionId")]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'start_document_classification_job' function.
class StartDocumentClassificationJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]
    JobStatus: JobStatusType
    DocumentClassifierArn: Annotated[str, _aws_pattern("Comprehend", "DocumentClassifierArn")]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'start_dominant_language_detection_job' function.
class StartDominantLanguageDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'start_entities_detection_job' function.
class StartEntitiesDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]
    JobStatus: JobStatusType
    EntityRecognizerArn: Annotated[str, _aws_pattern("Comprehend", "EntityRecognizerArn")]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'start_events_detection_job' function.
class StartEventsDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'start_flywheel_iteration' function.
class StartFlywheelIterationResponseTypeDef(BaseValidatorModel):
    FlywheelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]
    FlywheelIterationId: Annotated[str, _aws_pattern("Comprehend", "FlywheelIterationId")]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'start_key_phrases_detection_job' function.
class StartKeyPhrasesDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'start_pii_entities_detection_job' function.
class StartPiiEntitiesDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'start_sentiment_detection_job' function.
class StartSentimentDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'start_targeted_sentiment_detection_job' function.
class StartTargetedSentimentDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'start_topics_detection_job' function.
class StartTopicsDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'stop_dominant_language_detection_job' function.
class StopDominantLanguageDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'stop_entities_detection_job' function.
class StopEntitiesDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'stop_events_detection_job' function.
class StopEventsDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'stop_key_phrases_detection_job' function.
class StopKeyPhrasesDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'stop_pii_entities_detection_job' function.
class StopPiiEntitiesDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'stop_sentiment_detection_job' function.
class StopSentimentDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'stop_targeted_sentiment_detection_job' function.
class StopTargetedSentimentDetectionJobResponseTypeDef(BaseValidatorModel):
    JobId: Annotated[str, _aws_pattern("Comprehend", "JobId")]
    JobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_endpoint' function.
class UpdateEndpointResponseTypeDef(BaseValidatorModel):
    DesiredModelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]
    ResponseMetadata: ResponseMetadataTypeDef


class BatchDetectKeyPhrasesItemResultTypeDef(BaseValidatorModel):
    Index: Optional[int] = None
    KeyPhrases: Optional[List[KeyPhraseTypeDef]] = None


# This class is the output for the 'detect_key_phrases' function.
class DetectKeyPhrasesResponseTypeDef(BaseValidatorModel):
    KeyPhrases: List[KeyPhraseTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class BatchDetectSentimentItemResultTypeDef(BaseValidatorModel):
    Index: Optional[int] = None
    Sentiment: Optional[SentimentTypeType] = None
    SentimentScore: Optional[SentimentScoreTypeDef] = None


# This class is the output for the 'detect_sentiment' function.
class DetectSentimentResponseTypeDef(BaseValidatorModel):
    Sentiment: SentimentTypeType
    SentimentScore: SentimentScoreTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class MentionSentimentTypeDef(BaseValidatorModel):
    Sentiment: Optional[SentimentTypeType] = None
    SentimentScore: Optional[SentimentScoreTypeDef] = None


class BlockReferenceTypeDef(BaseValidatorModel):
    BlockId: Optional[str] = None
    BeginOffset: Optional[int] = None
    EndOffset: Optional[int] = None
    ChildBlocks: Optional[List[ChildBlockTypeDef]] = None


class ClassifierMetadataTypeDef(BaseValidatorModel):
    NumberOfLabels: Optional[int] = None
    NumberOfTrainedDocuments: Optional[int] = None
    NumberOfTestDocuments: Optional[int] = None
    EvaluationMetrics: Optional[ClassifierEvaluationMetricsTypeDef] = None


# This class is the output for the 'contains_pii_entities' function.
class ContainsPiiEntitiesResponseTypeDef(BaseValidatorModel):
    Labels: List[EntityLabelTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'create_endpoint' function.
class CreateEndpointRequestTypeDef(BaseValidatorModel):
    EndpointName: Annotated[str, _aws_pattern("Comprehend", "ComprehendEndpointName")]
    DesiredInferenceUnits: int
    ModelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    Tags: Optional[List[TagTypeDef]] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    FlywheelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]] = None


# This class is the input for the 'import_model' function.
class ImportModelRequestTypeDef(BaseValidatorModel):
    SourceModelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]
    ModelName: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArnName")]] = None
    VersionName: Optional[Annotated[str, _aws_pattern("Comprehend", "VersionName")]] = None
    ModelKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    Tags: Optional[List[TagTypeDef]] = None


# This class is the output for the 'list_tags_for_resource' function.
class ListTagsForResourceResponseTypeDef(BaseValidatorModel):
    ResourceArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]
    Tags: List[TagTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class TagResourceRequestTypeDef(BaseValidatorModel):
    ResourceArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]
    Tags: List[TagTypeDef]


class DataSecurityConfigOutputTypeDef(BaseValidatorModel):
    ModelKmsKeyId: Optional[str] = None
    VolumeKmsKeyId: Optional[str] = None
    DataLakeKmsKeyId: Optional[str] = None
    VpcConfig: Optional[VpcConfigOutputTypeDef] = None


class DataSecurityConfigTypeDef(BaseValidatorModel):
    ModelKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    DataLakeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigTypeDef] = None


VpcConfigUnionTypeDef = Union[VpcConfigOutputTypeDef, VpcConfigTypeDef]


class DatasetEntityRecognizerInputDataConfigTypeDef(BaseValidatorModel):
    Documents: DatasetEntityRecognizerDocumentsTypeDef
    Annotations: Optional[DatasetEntityRecognizerAnnotationsTypeDef] = None
    EntityList: Optional[DatasetEntityRecognizerEntityListTypeDef] = None


class DatasetFilterTypeDef(BaseValidatorModel):
    Status: Optional[DatasetStatusType] = None
    DatasetType: Optional[DatasetTypeType] = None
    CreationTimeAfter: Optional[TimestampTypeDef] = None
    CreationTimeBefore: Optional[TimestampTypeDef] = None


class DocumentClassificationJobFilterTypeDef(BaseValidatorModel):
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    SubmitTimeBefore: Optional[TimestampTypeDef] = None
    SubmitTimeAfter: Optional[TimestampTypeDef] = None


class DocumentClassifierFilterTypeDef(BaseValidatorModel):
    Status: Optional[ModelStatusType] = None
    DocumentClassifierName: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArnName")]] = None
    SubmitTimeBefore: Optional[TimestampTypeDef] = None
    SubmitTimeAfter: Optional[TimestampTypeDef] = None


class DominantLanguageDetectionJobFilterTypeDef(BaseValidatorModel):
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    SubmitTimeBefore: Optional[TimestampTypeDef] = None
    SubmitTimeAfter: Optional[TimestampTypeDef] = None


class EndpointFilterTypeDef(BaseValidatorModel):
    ModelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]] = None
    Status: Optional[EndpointStatusType] = None
    CreationTimeBefore: Optional[TimestampTypeDef] = None
    CreationTimeAfter: Optional[TimestampTypeDef] = None


class EntitiesDetectionJobFilterTypeDef(BaseValidatorModel):
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    SubmitTimeBefore: Optional[TimestampTypeDef] = None
    SubmitTimeAfter: Optional[TimestampTypeDef] = None


class EntityRecognizerFilterTypeDef(BaseValidatorModel):
    Status: Optional[ModelStatusType] = None
    RecognizerName: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArnName")]] = None
    SubmitTimeBefore: Optional[TimestampTypeDef] = None
    SubmitTimeAfter: Optional[TimestampTypeDef] = None


class EventsDetectionJobFilterTypeDef(BaseValidatorModel):
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    SubmitTimeBefore: Optional[TimestampTypeDef] = None
    SubmitTimeAfter: Optional[TimestampTypeDef] = None


class FlywheelFilterTypeDef(BaseValidatorModel):
    Status: Optional[FlywheelStatusType] = None
    CreationTimeAfter: Optional[TimestampTypeDef] = None
    CreationTimeBefore: Optional[TimestampTypeDef] = None


class FlywheelIterationFilterTypeDef(BaseValidatorModel):
    CreationTimeAfter: Optional[TimestampTypeDef] = None
    CreationTimeBefore: Optional[TimestampTypeDef] = None


class KeyPhrasesDetectionJobFilterTypeDef(BaseValidatorModel):
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    SubmitTimeBefore: Optional[TimestampTypeDef] = None
    SubmitTimeAfter: Optional[TimestampTypeDef] = None


class PiiEntitiesDetectionJobFilterTypeDef(BaseValidatorModel):
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    SubmitTimeBefore: Optional[TimestampTypeDef] = None
    SubmitTimeAfter: Optional[TimestampTypeDef] = None


class SentimentDetectionJobFilterTypeDef(BaseValidatorModel):
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    SubmitTimeBefore: Optional[TimestampTypeDef] = None
    SubmitTimeAfter: Optional[TimestampTypeDef] = None


class TargetedSentimentDetectionJobFilterTypeDef(BaseValidatorModel):
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    SubmitTimeBefore: Optional[TimestampTypeDef] = None
    SubmitTimeAfter: Optional[TimestampTypeDef] = None


class TopicsDetectionJobFilterTypeDef(BaseValidatorModel):
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    SubmitTimeBefore: Optional[TimestampTypeDef] = None
    SubmitTimeAfter: Optional[TimestampTypeDef] = None


# This class is the output for the 'describe_dataset' function.
class DescribeDatasetResponseTypeDef(BaseValidatorModel):
    DatasetProperties: DatasetPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_datasets' function.
class ListDatasetsResponseTypeDef(BaseValidatorModel):
    DatasetPropertiesList: List[DatasetPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'describe_endpoint' function.
class DescribeEndpointResponseTypeDef(BaseValidatorModel):
    EndpointProperties: EndpointPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_endpoints' function.
class ListEndpointsResponseTypeDef(BaseValidatorModel):
    EndpointPropertiesList: List[EndpointPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'detect_pii_entities' function.
class DetectPiiEntitiesResponseTypeDef(BaseValidatorModel):
    Entities: List[PiiEntityTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'detect_toxic_content' function.
class DetectToxicContentRequestTypeDef(BaseValidatorModel):
    TextSegments: List[TextSegmentTypeDef]
    LanguageCode: LanguageCodeType


class DocumentClassifierInputDataConfigOutputTypeDef(BaseValidatorModel):
    DataFormat: Optional[DocumentClassifierDataFormatType] = None
    S3Uri: Optional[str] = None
    TestS3Uri: Optional[str] = None
    LabelDelimiter: Optional[str] = None
    AugmentedManifests: Optional[List[AugmentedManifestsListItemOutputTypeDef]] = None
    DocumentType: Optional[DocumentClassifierDocumentTypeFormatType] = None
    Documents: Optional[DocumentClassifierDocumentsTypeDef] = None
    DocumentReaderConfig: Optional[DocumentReaderConfigOutputTypeDef] = None


class InputDataConfigOutputTypeDef(BaseValidatorModel):
    S3Uri: str
    InputFormat: Optional[InputFormatType] = None
    DocumentReaderConfig: Optional[DocumentReaderConfigOutputTypeDef] = None


class DocumentClassifierInputDataConfigTypeDef(BaseValidatorModel):
    DataFormat: Optional[DocumentClassifierDataFormatType] = None
    S3Uri: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None
    TestS3Uri: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None
    LabelDelimiter: Optional[Annotated[str, _aws_pattern("Comprehend", "LabelDelimiter")]] = None
    AugmentedManifests: Optional[List[AugmentedManifestsListItemTypeDef]] = None
    DocumentType: Optional[DocumentClassifierDocumentTypeFormatType] = None
    Documents: Optional[DocumentClassifierDocumentsTypeDef] = None
    DocumentReaderConfig: Optional[DocumentReaderConfigTypeDef] = None


DocumentReaderConfigUnionTypeDef = Union[DocumentReaderConfigOutputTypeDef, DocumentReaderConfigTypeDef]


class InputDataConfigTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("Comprehend", "S3Uri")]
    InputFormat: Optional[InputFormatType] = None
    DocumentReaderConfig: Optional[DocumentReaderConfigTypeDef] = None


# This class is the output for the 'list_document_classifier_summaries' function.
class ListDocumentClassifierSummariesResponseTypeDef(BaseValidatorModel):
    DocumentClassifierSummariesList: List[DocumentClassifierSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


class DocumentMetadataTypeDef(BaseValidatorModel):
    Pages: Optional[int] = None
    ExtractedCharacters: Optional[List[ExtractedCharactersListItemTypeDef]] = None


class EntityRecognitionConfigOutputTypeDef(BaseValidatorModel):
    EntityTypes: List[EntityTypesListItemTypeDef]


class EntityRecognitionConfigTypeDef(BaseValidatorModel):
    EntityTypes: List[EntityTypesListItemTypeDef]


class EntityRecognizerInputDataConfigOutputTypeDef(BaseValidatorModel):
    EntityTypes: List[EntityTypesListItemTypeDef]
    DataFormat: Optional[EntityRecognizerDataFormatType] = None
    Documents: Optional[EntityRecognizerDocumentsTypeDef] = None
    Annotations: Optional[EntityRecognizerAnnotationsTypeDef] = None
    EntityList: Optional[EntityRecognizerEntityListTypeDef] = None
    AugmentedManifests: Optional[List[AugmentedManifestsListItemOutputTypeDef]] = None


class EntityRecognizerInputDataConfigTypeDef(BaseValidatorModel):
    EntityTypes: List[EntityTypesListItemTypeDef]
    DataFormat: Optional[EntityRecognizerDataFormatType] = None
    Documents: Optional[EntityRecognizerDocumentsTypeDef] = None
    Annotations: Optional[EntityRecognizerAnnotationsTypeDef] = None
    EntityList: Optional[EntityRecognizerEntityListTypeDef] = None
    AugmentedManifests: Optional[List[AugmentedManifestsListItemTypeDef]] = None


class EntityRecognizerMetadataEntityTypesListItemTypeDef(BaseValidatorModel):
    Type: Optional[str] = None
    EvaluationMetrics: Optional[EntityTypesEvaluationMetricsTypeDef] = None
    NumberOfTrainMentions: Optional[int] = None


# This class is the output for the 'list_entity_recognizer_summaries' function.
class ListEntityRecognizerSummariesResponseTypeDef(BaseValidatorModel):
    EntityRecognizerSummariesList: List[EntityRecognizerSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


class FlywheelIterationPropertiesTypeDef(BaseValidatorModel):
    FlywheelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]] = None
    FlywheelIterationId: Optional[Annotated[str, _aws_pattern("Comprehend", "FlywheelIterationId")]] = None
    CreationTime: Optional[datetime] = None
    EndTime: Optional[datetime] = None
    Status: Optional[FlywheelIterationStatusType] = None
    Message: Optional[str] = None
    EvaluatedModelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]] = None
    EvaluatedModelMetrics: Optional[FlywheelModelEvaluationMetricsTypeDef] = None
    TrainedModelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]] = None
    TrainedModelMetrics: Optional[FlywheelModelEvaluationMetricsTypeDef] = None
    EvaluationManifestS3Prefix: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None


# This class is the output for the 'list_flywheels' function.
class ListFlywheelsResponseTypeDef(BaseValidatorModel):
    FlywheelSummaryList: List[FlywheelSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


class GeometryTypeDef(BaseValidatorModel):
    BoundingBox: Optional[BoundingBoxTypeDef] = None
    Polygon: Optional[List[PointTypeDef]] = None


class SyntaxTokenTypeDef(BaseValidatorModel):
    TokenId: Optional[int] = None
    Text: Optional[str] = None
    BeginOffset: Optional[int] = None
    EndOffset: Optional[int] = None
    PartOfSpeech: Optional[PartOfSpeechTagTypeDef] = None


RedactionConfigUnionTypeDef = Union[RedactionConfigOutputTypeDef, RedactionConfigTypeDef]


class ToxicLabelsTypeDef(BaseValidatorModel):
    Labels: Optional[List[ToxicContentTypeDef]] = None
    Toxicity: Optional[float] = None


# This class is the output for the 'batch_detect_dominant_language' function.
class BatchDetectDominantLanguageResponseTypeDef(BaseValidatorModel):
    ResultList: List[BatchDetectDominantLanguageItemResultTypeDef]
    ErrorList: List[BatchItemErrorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'batch_detect_key_phrases' function.
class BatchDetectKeyPhrasesResponseTypeDef(BaseValidatorModel):
    ResultList: List[BatchDetectKeyPhrasesItemResultTypeDef]
    ErrorList: List[BatchItemErrorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'batch_detect_sentiment' function.
class BatchDetectSentimentResponseTypeDef(BaseValidatorModel):
    ResultList: List[BatchDetectSentimentItemResultTypeDef]
    ErrorList: List[BatchItemErrorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class TargetedSentimentMentionTypeDef(BaseValidatorModel):
    Score: Optional[float] = None
    GroupScore: Optional[float] = None
    Text: Optional[str] = None
    Type: Optional[TargetedSentimentEntityTypeType] = None
    MentionSentiment: Optional[MentionSentimentTypeDef] = None
    BeginOffset: Optional[int] = None
    EndOffset: Optional[int] = None


class EntityTypeDef(BaseValidatorModel):
    Score: Optional[float] = None
    Type: Optional[EntityTypeType] = None
    Text: Optional[str] = None
    BeginOffset: Optional[int] = None
    EndOffset: Optional[int] = None
    BlockReferences: Optional[List[BlockReferenceTypeDef]] = None


DataSecurityConfigUnionTypeDef = Union[DataSecurityConfigOutputTypeDef, DataSecurityConfigTypeDef]


class UpdateDataSecurityConfigTypeDef(BaseValidatorModel):
    ModelKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigUnionTypeDef] = None


class DatasetInputDataConfigTypeDef(BaseValidatorModel):
    AugmentedManifests: Optional[List[DatasetAugmentedManifestsListItemTypeDef]] = None
    DataFormat: Optional[DatasetDataFormatType] = None
    DocumentClassifierInputDataConfig: Optional[DatasetDocumentClassifierInputDataConfigTypeDef] = None
    EntityRecognizerInputDataConfig: Optional[DatasetEntityRecognizerInputDataConfigTypeDef] = None


# This class is the input for the 'list_datasets' function.
class ListDatasetsRequestTypeDef(BaseValidatorModel):
    FlywheelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]] = None
    Filter: Optional[DatasetFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


class ListDocumentClassificationJobsRequestPaginateTypeDef(BaseValidatorModel):
    Filter: Optional[DocumentClassificationJobFilterTypeDef] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the input for the 'list_document_classification_jobs' function.
class ListDocumentClassificationJobsRequestTypeDef(BaseValidatorModel):
    Filter: Optional[DocumentClassificationJobFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


class ListDocumentClassifiersRequestPaginateTypeDef(BaseValidatorModel):
    Filter: Optional[DocumentClassifierFilterTypeDef] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the input for the 'list_document_classifiers' function.
class ListDocumentClassifiersRequestTypeDef(BaseValidatorModel):
    Filter: Optional[DocumentClassifierFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


class ListDominantLanguageDetectionJobsRequestPaginateTypeDef(BaseValidatorModel):
    Filter: Optional[DominantLanguageDetectionJobFilterTypeDef] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the input for the 'list_dominant_language_detection_jobs' function.
class ListDominantLanguageDetectionJobsRequestTypeDef(BaseValidatorModel):
    Filter: Optional[DominantLanguageDetectionJobFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


class ListEndpointsRequestPaginateTypeDef(BaseValidatorModel):
    Filter: Optional[EndpointFilterTypeDef] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the input for the 'list_endpoints' function.
class ListEndpointsRequestTypeDef(BaseValidatorModel):
    Filter: Optional[EndpointFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


class ListEntitiesDetectionJobsRequestPaginateTypeDef(BaseValidatorModel):
    Filter: Optional[EntitiesDetectionJobFilterTypeDef] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the input for the 'list_entities_detection_jobs' function.
class ListEntitiesDetectionJobsRequestTypeDef(BaseValidatorModel):
    Filter: Optional[EntitiesDetectionJobFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


class ListEntityRecognizersRequestPaginateTypeDef(BaseValidatorModel):
    Filter: Optional[EntityRecognizerFilterTypeDef] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the input for the 'list_entity_recognizers' function.
class ListEntityRecognizersRequestTypeDef(BaseValidatorModel):
    Filter: Optional[EntityRecognizerFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


# This class is the input for the 'list_events_detection_jobs' function.
class ListEventsDetectionJobsRequestTypeDef(BaseValidatorModel):
    Filter: Optional[EventsDetectionJobFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


# This class is the input for the 'list_flywheels' function.
class ListFlywheelsRequestTypeDef(BaseValidatorModel):
    Filter: Optional[FlywheelFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


# This class is the input for the 'list_flywheel_iteration_history' function.
class ListFlywheelIterationHistoryRequestTypeDef(BaseValidatorModel):
    FlywheelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]
    Filter: Optional[FlywheelIterationFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


class ListKeyPhrasesDetectionJobsRequestPaginateTypeDef(BaseValidatorModel):
    Filter: Optional[KeyPhrasesDetectionJobFilterTypeDef] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the input for the 'list_key_phrases_detection_jobs' function.
class ListKeyPhrasesDetectionJobsRequestTypeDef(BaseValidatorModel):
    Filter: Optional[KeyPhrasesDetectionJobFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


class ListPiiEntitiesDetectionJobsRequestPaginateTypeDef(BaseValidatorModel):
    Filter: Optional[PiiEntitiesDetectionJobFilterTypeDef] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the input for the 'list_pii_entities_detection_jobs' function.
class ListPiiEntitiesDetectionJobsRequestTypeDef(BaseValidatorModel):
    Filter: Optional[PiiEntitiesDetectionJobFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


class ListSentimentDetectionJobsRequestPaginateTypeDef(BaseValidatorModel):
    Filter: Optional[SentimentDetectionJobFilterTypeDef] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the input for the 'list_sentiment_detection_jobs' function.
class ListSentimentDetectionJobsRequestTypeDef(BaseValidatorModel):
    Filter: Optional[SentimentDetectionJobFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


# This class is the input for the 'list_targeted_sentiment_detection_jobs' function.
class ListTargetedSentimentDetectionJobsRequestTypeDef(BaseValidatorModel):
    Filter: Optional[TargetedSentimentDetectionJobFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


class ListTopicsDetectionJobsRequestPaginateTypeDef(BaseValidatorModel):
    Filter: Optional[TopicsDetectionJobFilterTypeDef] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the input for the 'list_topics_detection_jobs' function.
class ListTopicsDetectionJobsRequestTypeDef(BaseValidatorModel):
    Filter: Optional[TopicsDetectionJobFilterTypeDef] = None
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


class DocumentClassifierPropertiesTypeDef(BaseValidatorModel):
    DocumentClassifierArn: Optional[Annotated[str, _aws_pattern("Comprehend", "DocumentClassifierArn")]] = None
    LanguageCode: Optional[LanguageCodeType] = None
    Status: Optional[ModelStatusType] = None
    Message: Optional[str] = None
    SubmitTime: Optional[datetime] = None
    EndTime: Optional[datetime] = None
    TrainingStartTime: Optional[datetime] = None
    TrainingEndTime: Optional[datetime] = None
    InputDataConfig: Optional[DocumentClassifierInputDataConfigOutputTypeDef] = None
    OutputDataConfig: Optional[DocumentClassifierOutputDataConfigTypeDef] = None
    ClassifierMetadata: Optional[ClassifierMetadataTypeDef] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigOutputTypeDef] = None
    Mode: Optional[DocumentClassifierModeType] = None
    ModelKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VersionName: Optional[Annotated[str, _aws_pattern("Comprehend", "VersionName")]] = None
    SourceModelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "DocumentClassifierArn")]] = None
    FlywheelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]] = None


class DocumentClassificationJobPropertiesTypeDef(BaseValidatorModel):
    JobId: Optional[Annotated[str, _aws_pattern("Comprehend", "JobId")]] = None
    JobArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    Message: Optional[str] = None
    SubmitTime: Optional[datetime] = None
    EndTime: Optional[datetime] = None
    DocumentClassifierArn: Optional[Annotated[str, _aws_pattern("Comprehend", "DocumentClassifierArn")]] = None
    InputDataConfig: Optional[InputDataConfigOutputTypeDef] = None
    OutputDataConfig: Optional[OutputDataConfigTypeDef] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigOutputTypeDef] = None
    FlywheelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]] = None


class DominantLanguageDetectionJobPropertiesTypeDef(BaseValidatorModel):
    JobId: Optional[Annotated[str, _aws_pattern("Comprehend", "JobId")]] = None
    JobArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    Message: Optional[str] = None
    SubmitTime: Optional[datetime] = None
    EndTime: Optional[datetime] = None
    InputDataConfig: Optional[InputDataConfigOutputTypeDef] = None
    OutputDataConfig: Optional[OutputDataConfigTypeDef] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigOutputTypeDef] = None


class EntitiesDetectionJobPropertiesTypeDef(BaseValidatorModel):
    JobId: Optional[Annotated[str, _aws_pattern("Comprehend", "JobId")]] = None
    JobArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    Message: Optional[str] = None
    SubmitTime: Optional[datetime] = None
    EndTime: Optional[datetime] = None
    EntityRecognizerArn: Optional[Annotated[str, _aws_pattern("Comprehend", "EntityRecognizerArn")]] = None
    InputDataConfig: Optional[InputDataConfigOutputTypeDef] = None
    OutputDataConfig: Optional[OutputDataConfigTypeDef] = None
    LanguageCode: Optional[LanguageCodeType] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigOutputTypeDef] = None
    FlywheelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]] = None


class EventsDetectionJobPropertiesTypeDef(BaseValidatorModel):
    JobId: Optional[Annotated[str, _aws_pattern("Comprehend", "JobId")]] = None
    JobArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    Message: Optional[str] = None
    SubmitTime: Optional[datetime] = None
    EndTime: Optional[datetime] = None
    InputDataConfig: Optional[InputDataConfigOutputTypeDef] = None
    OutputDataConfig: Optional[OutputDataConfigTypeDef] = None
    LanguageCode: Optional[LanguageCodeType] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    TargetEventTypes: Optional[List[Annotated[str, _aws_pattern("Comprehend", "EventTypeString")]]] = None


class KeyPhrasesDetectionJobPropertiesTypeDef(BaseValidatorModel):
    JobId: Optional[Annotated[str, _aws_pattern("Comprehend", "JobId")]] = None
    JobArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    Message: Optional[str] = None
    SubmitTime: Optional[datetime] = None
    EndTime: Optional[datetime] = None
    InputDataConfig: Optional[InputDataConfigOutputTypeDef] = None
    OutputDataConfig: Optional[OutputDataConfigTypeDef] = None
    LanguageCode: Optional[LanguageCodeType] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigOutputTypeDef] = None


class PiiEntitiesDetectionJobPropertiesTypeDef(BaseValidatorModel):
    JobId: Optional[Annotated[str, _aws_pattern("Comprehend", "JobId")]] = None
    JobArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    Message: Optional[str] = None
    SubmitTime: Optional[datetime] = None
    EndTime: Optional[datetime] = None
    InputDataConfig: Optional[InputDataConfigOutputTypeDef] = None
    OutputDataConfig: Optional[PiiOutputDataConfigTypeDef] = None
    RedactionConfig: Optional[RedactionConfigOutputTypeDef] = None
    LanguageCode: Optional[LanguageCodeType] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    Mode: Optional[PiiEntitiesDetectionModeType] = None


class SentimentDetectionJobPropertiesTypeDef(BaseValidatorModel):
    JobId: Optional[Annotated[str, _aws_pattern("Comprehend", "JobId")]] = None
    JobArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    Message: Optional[str] = None
    SubmitTime: Optional[datetime] = None
    EndTime: Optional[datetime] = None
    InputDataConfig: Optional[InputDataConfigOutputTypeDef] = None
    OutputDataConfig: Optional[OutputDataConfigTypeDef] = None
    LanguageCode: Optional[LanguageCodeType] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigOutputTypeDef] = None


class TargetedSentimentDetectionJobPropertiesTypeDef(BaseValidatorModel):
    JobId: Optional[Annotated[str, _aws_pattern("Comprehend", "JobId")]] = None
    JobArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    Message: Optional[str] = None
    SubmitTime: Optional[datetime] = None
    EndTime: Optional[datetime] = None
    InputDataConfig: Optional[InputDataConfigOutputTypeDef] = None
    OutputDataConfig: Optional[OutputDataConfigTypeDef] = None
    LanguageCode: Optional[LanguageCodeType] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigOutputTypeDef] = None


class TopicsDetectionJobPropertiesTypeDef(BaseValidatorModel):
    JobId: Optional[Annotated[str, _aws_pattern("Comprehend", "JobId")]] = None
    JobArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendArn")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    JobStatus: Optional[JobStatusType] = None
    Message: Optional[str] = None
    SubmitTime: Optional[datetime] = None
    EndTime: Optional[datetime] = None
    InputDataConfig: Optional[InputDataConfigOutputTypeDef] = None
    OutputDataConfig: Optional[OutputDataConfigTypeDef] = None
    NumberOfTopics: Optional[int] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigOutputTypeDef] = None


DocumentClassifierInputDataConfigUnionTypeDef = Union[
    DocumentClassifierInputDataConfigOutputTypeDef, DocumentClassifierInputDataConfigTypeDef
]


# This class is the input for the 'classify_document' function.
class ClassifyDocumentRequestTypeDef(BaseValidatorModel):
    EndpointArn: Annotated[str, _aws_pattern("Comprehend", "DocumentClassifierEndpointArn")]
    Text: Optional[str] = None
    Bytes: Optional[BlobTypeDef] = None
    DocumentReaderConfig: Optional[DocumentReaderConfigUnionTypeDef] = None


# This class is the input for the 'detect_entities' function.
class DetectEntitiesRequestTypeDef(BaseValidatorModel):
    Text: Optional[str] = None
    LanguageCode: Optional[LanguageCodeType] = None
    EndpointArn: Optional[Annotated[str, _aws_pattern("Comprehend", "EntityRecognizerEndpointArn")]] = None
    Bytes: Optional[BlobTypeDef] = None
    DocumentReaderConfig: Optional[DocumentReaderConfigUnionTypeDef] = None


InputDataConfigUnionTypeDef = Union[InputDataConfigOutputTypeDef, InputDataConfigTypeDef]


# This class is the output for the 'classify_document' function.
class ClassifyDocumentResponseTypeDef(BaseValidatorModel):
    Classes: List[DocumentClassTypeDef]
    Labels: List[DocumentLabelTypeDef]
    DocumentMetadata: DocumentMetadataTypeDef
    DocumentType: List[DocumentTypeListItemTypeDef]
    Errors: List[ErrorsListItemTypeDef]
    Warnings: List[WarningsListItemTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class TaskConfigOutputTypeDef(BaseValidatorModel):
    LanguageCode: LanguageCodeType
    DocumentClassificationConfig: Optional[DocumentClassificationConfigOutputTypeDef] = None
    EntityRecognitionConfig: Optional[EntityRecognitionConfigOutputTypeDef] = None


class TaskConfigTypeDef(BaseValidatorModel):
    LanguageCode: LanguageCodeType
    DocumentClassificationConfig: Optional[DocumentClassificationConfigTypeDef] = None
    EntityRecognitionConfig: Optional[EntityRecognitionConfigTypeDef] = None


EntityRecognizerInputDataConfigUnionTypeDef = Union[
    EntityRecognizerInputDataConfigOutputTypeDef, EntityRecognizerInputDataConfigTypeDef
]


class EntityRecognizerMetadataTypeDef(BaseValidatorModel):
    NumberOfTrainedDocuments: Optional[int] = None
    NumberOfTestDocuments: Optional[int] = None
    EvaluationMetrics: Optional[EntityRecognizerEvaluationMetricsTypeDef] = None
    EntityTypes: Optional[List[EntityRecognizerMetadataEntityTypesListItemTypeDef]] = None


# This class is the output for the 'describe_flywheel_iteration' function.
class DescribeFlywheelIterationResponseTypeDef(BaseValidatorModel):
    FlywheelIterationProperties: FlywheelIterationPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_flywheel_iteration_history' function.
class ListFlywheelIterationHistoryResponseTypeDef(BaseValidatorModel):
    FlywheelIterationPropertiesList: List[FlywheelIterationPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


class BlockTypeDef(BaseValidatorModel):
    Id: Optional[str] = None
    BlockType: Optional[BlockTypeType] = None
    Text: Optional[str] = None
    Page: Optional[int] = None
    Geometry: Optional[GeometryTypeDef] = None
    Relationships: Optional[List[RelationshipsListItemTypeDef]] = None


class BatchDetectSyntaxItemResultTypeDef(BaseValidatorModel):
    Index: Optional[int] = None
    SyntaxTokens: Optional[List[SyntaxTokenTypeDef]] = None


# This class is the output for the 'detect_syntax' function.
class DetectSyntaxResponseTypeDef(BaseValidatorModel):
    SyntaxTokens: List[SyntaxTokenTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'detect_toxic_content' function.
class DetectToxicContentResponseTypeDef(BaseValidatorModel):
    ResultList: List[ToxicLabelsTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class TargetedSentimentEntityTypeDef(BaseValidatorModel):
    DescriptiveMentionIndex: Optional[List[int]] = None
    Mentions: Optional[List[TargetedSentimentMentionTypeDef]] = None


class BatchDetectEntitiesItemResultTypeDef(BaseValidatorModel):
    Index: Optional[int] = None
    Entities: Optional[List[EntityTypeDef]] = None


# This class is the input for the 'update_flywheel' function.
class UpdateFlywheelRequestTypeDef(BaseValidatorModel):
    FlywheelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]
    ActiveModelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    DataSecurityConfig: Optional[UpdateDataSecurityConfigTypeDef] = None


# This class is the input for the 'create_dataset' function.
class CreateDatasetRequestTypeDef(BaseValidatorModel):
    FlywheelArn: Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]
    DatasetName: Annotated[str, _aws_pattern("Comprehend", "ComprehendArnName")]
    InputDataConfig: DatasetInputDataConfigTypeDef
    DatasetType: Optional[DatasetTypeType] = None
    Description: Optional[Annotated[str, _aws_pattern("Comprehend", "Description")]] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    Tags: Optional[List[TagTypeDef]] = None


# This class is the output for the 'describe_document_classifier' function.
class DescribeDocumentClassifierResponseTypeDef(BaseValidatorModel):
    DocumentClassifierProperties: DocumentClassifierPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_document_classifiers' function.
class ListDocumentClassifiersResponseTypeDef(BaseValidatorModel):
    DocumentClassifierPropertiesList: List[DocumentClassifierPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'describe_document_classification_job' function.
class DescribeDocumentClassificationJobResponseTypeDef(BaseValidatorModel):
    DocumentClassificationJobProperties: DocumentClassificationJobPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_document_classification_jobs' function.
class ListDocumentClassificationJobsResponseTypeDef(BaseValidatorModel):
    DocumentClassificationJobPropertiesList: List[DocumentClassificationJobPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'describe_dominant_language_detection_job' function.
class DescribeDominantLanguageDetectionJobResponseTypeDef(BaseValidatorModel):
    DominantLanguageDetectionJobProperties: DominantLanguageDetectionJobPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_dominant_language_detection_jobs' function.
class ListDominantLanguageDetectionJobsResponseTypeDef(BaseValidatorModel):
    DominantLanguageDetectionJobPropertiesList: List[DominantLanguageDetectionJobPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'describe_entities_detection_job' function.
class DescribeEntitiesDetectionJobResponseTypeDef(BaseValidatorModel):
    EntitiesDetectionJobProperties: EntitiesDetectionJobPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_entities_detection_jobs' function.
class ListEntitiesDetectionJobsResponseTypeDef(BaseValidatorModel):
    EntitiesDetectionJobPropertiesList: List[EntitiesDetectionJobPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'describe_events_detection_job' function.
class DescribeEventsDetectionJobResponseTypeDef(BaseValidatorModel):
    EventsDetectionJobProperties: EventsDetectionJobPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_events_detection_jobs' function.
class ListEventsDetectionJobsResponseTypeDef(BaseValidatorModel):
    EventsDetectionJobPropertiesList: List[EventsDetectionJobPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'describe_key_phrases_detection_job' function.
class DescribeKeyPhrasesDetectionJobResponseTypeDef(BaseValidatorModel):
    KeyPhrasesDetectionJobProperties: KeyPhrasesDetectionJobPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_key_phrases_detection_jobs' function.
class ListKeyPhrasesDetectionJobsResponseTypeDef(BaseValidatorModel):
    KeyPhrasesDetectionJobPropertiesList: List[KeyPhrasesDetectionJobPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'describe_pii_entities_detection_job' function.
class DescribePiiEntitiesDetectionJobResponseTypeDef(BaseValidatorModel):
    PiiEntitiesDetectionJobProperties: PiiEntitiesDetectionJobPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_pii_entities_detection_jobs' function.
class ListPiiEntitiesDetectionJobsResponseTypeDef(BaseValidatorModel):
    PiiEntitiesDetectionJobPropertiesList: List[PiiEntitiesDetectionJobPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'describe_sentiment_detection_job' function.
class DescribeSentimentDetectionJobResponseTypeDef(BaseValidatorModel):
    SentimentDetectionJobProperties: SentimentDetectionJobPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_sentiment_detection_jobs' function.
class ListSentimentDetectionJobsResponseTypeDef(BaseValidatorModel):
    SentimentDetectionJobPropertiesList: List[SentimentDetectionJobPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'describe_targeted_sentiment_detection_job' function.
class DescribeTargetedSentimentDetectionJobResponseTypeDef(BaseValidatorModel):
    TargetedSentimentDetectionJobProperties: TargetedSentimentDetectionJobPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_targeted_sentiment_detection_jobs' function.
class ListTargetedSentimentDetectionJobsResponseTypeDef(BaseValidatorModel):
    TargetedSentimentDetectionJobPropertiesList: List[TargetedSentimentDetectionJobPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'describe_topics_detection_job' function.
class DescribeTopicsDetectionJobResponseTypeDef(BaseValidatorModel):
    TopicsDetectionJobProperties: TopicsDetectionJobPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_topics_detection_jobs' function.
class ListTopicsDetectionJobsResponseTypeDef(BaseValidatorModel):
    TopicsDetectionJobPropertiesList: List[TopicsDetectionJobPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the input for the 'create_document_classifier' function.
class CreateDocumentClassifierRequestTypeDef(BaseValidatorModel):
    DocumentClassifierName: Annotated[str, _aws_pattern("Comprehend", "ComprehendArnName")]
    DataAccessRoleArn: Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]
    InputDataConfig: DocumentClassifierInputDataConfigUnionTypeDef
    LanguageCode: LanguageCodeType
    VersionName: Optional[Annotated[str, _aws_pattern("Comprehend", "VersionName")]] = None
    Tags: Optional[List[TagTypeDef]] = None
    OutputDataConfig: Optional[DocumentClassifierOutputDataConfigTypeDef] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigUnionTypeDef] = None
    Mode: Optional[DocumentClassifierModeType] = None
    ModelKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    ModelPolicy: Optional[Annotated[str, _aws_pattern("Comprehend", "Policy")]] = None


# This class is the input for the 'start_document_classification_job' function.
class StartDocumentClassificationJobRequestTypeDef(BaseValidatorModel):
    InputDataConfig: InputDataConfigUnionTypeDef
    OutputDataConfig: OutputDataConfigTypeDef
    DataAccessRoleArn: Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    DocumentClassifierArn: Optional[Annotated[str, _aws_pattern("Comprehend", "DocumentClassifierArn")]] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigUnionTypeDef] = None
    Tags: Optional[List[TagTypeDef]] = None
    FlywheelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]] = None


# This class is the input for the 'start_dominant_language_detection_job' function.
class StartDominantLanguageDetectionJobRequestTypeDef(BaseValidatorModel):
    InputDataConfig: InputDataConfigUnionTypeDef
    OutputDataConfig: OutputDataConfigTypeDef
    DataAccessRoleArn: Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigUnionTypeDef] = None
    Tags: Optional[List[TagTypeDef]] = None


# This class is the input for the 'start_entities_detection_job' function.
class StartEntitiesDetectionJobRequestTypeDef(BaseValidatorModel):
    InputDataConfig: InputDataConfigUnionTypeDef
    OutputDataConfig: OutputDataConfigTypeDef
    DataAccessRoleArn: Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]
    LanguageCode: LanguageCodeType
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    EntityRecognizerArn: Optional[Annotated[str, _aws_pattern("Comprehend", "EntityRecognizerArn")]] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigUnionTypeDef] = None
    Tags: Optional[List[TagTypeDef]] = None
    FlywheelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]] = None


# This class is the input for the 'start_events_detection_job' function.
class StartEventsDetectionJobRequestTypeDef(BaseValidatorModel):
    InputDataConfig: InputDataConfigUnionTypeDef
    OutputDataConfig: OutputDataConfigTypeDef
    DataAccessRoleArn: Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]
    LanguageCode: LanguageCodeType
    TargetEventTypes: List[Annotated[str, _aws_pattern("Comprehend", "EventTypeString")]]
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    Tags: Optional[List[TagTypeDef]] = None


# This class is the input for the 'start_key_phrases_detection_job' function.
class StartKeyPhrasesDetectionJobRequestTypeDef(BaseValidatorModel):
    InputDataConfig: InputDataConfigUnionTypeDef
    OutputDataConfig: OutputDataConfigTypeDef
    DataAccessRoleArn: Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]
    LanguageCode: LanguageCodeType
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigUnionTypeDef] = None
    Tags: Optional[List[TagTypeDef]] = None


# This class is the input for the 'start_pii_entities_detection_job' function.
class StartPiiEntitiesDetectionJobRequestTypeDef(BaseValidatorModel):
    InputDataConfig: InputDataConfigUnionTypeDef
    OutputDataConfig: OutputDataConfigTypeDef
    Mode: PiiEntitiesDetectionModeType
    DataAccessRoleArn: Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]
    LanguageCode: LanguageCodeType
    RedactionConfig: Optional[RedactionConfigUnionTypeDef] = None
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    Tags: Optional[List[TagTypeDef]] = None


# This class is the input for the 'start_sentiment_detection_job' function.
class StartSentimentDetectionJobRequestTypeDef(BaseValidatorModel):
    InputDataConfig: InputDataConfigUnionTypeDef
    OutputDataConfig: OutputDataConfigTypeDef
    DataAccessRoleArn: Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]
    LanguageCode: LanguageCodeType
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigUnionTypeDef] = None
    Tags: Optional[List[TagTypeDef]] = None


# This class is the input for the 'start_targeted_sentiment_detection_job' function.
class StartTargetedSentimentDetectionJobRequestTypeDef(BaseValidatorModel):
    InputDataConfig: InputDataConfigUnionTypeDef
    OutputDataConfig: OutputDataConfigTypeDef
    DataAccessRoleArn: Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]
    LanguageCode: LanguageCodeType
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigUnionTypeDef] = None
    Tags: Optional[List[TagTypeDef]] = None


# This class is the input for the 'start_topics_detection_job' function.
class StartTopicsDetectionJobRequestTypeDef(BaseValidatorModel):
    InputDataConfig: InputDataConfigUnionTypeDef
    OutputDataConfig: OutputDataConfigTypeDef
    DataAccessRoleArn: Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]
    JobName: Optional[Annotated[str, _aws_pattern("Comprehend", "JobName")]] = None
    NumberOfTopics: Optional[int] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigUnionTypeDef] = None
    Tags: Optional[List[TagTypeDef]] = None


class FlywheelPropertiesTypeDef(BaseValidatorModel):
    FlywheelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]] = None
    ActiveModelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    TaskConfig: Optional[TaskConfigOutputTypeDef] = None
    DataLakeS3Uri: Optional[Annotated[str, _aws_pattern("Comprehend", "S3Uri")]] = None
    DataSecurityConfig: Optional[DataSecurityConfigOutputTypeDef] = None
    Status: Optional[FlywheelStatusType] = None
    ModelType: Optional[ModelTypeType] = None
    Message: Optional[str] = None
    CreationTime: Optional[datetime] = None
    LastModifiedTime: Optional[datetime] = None
    LatestFlywheelIteration: Optional[Annotated[str, _aws_pattern("Comprehend", "FlywheelIterationId")]] = None


TaskConfigUnionTypeDef = Union[TaskConfigOutputTypeDef, TaskConfigTypeDef]


# This class is the input for the 'create_entity_recognizer' function.
class CreateEntityRecognizerRequestTypeDef(BaseValidatorModel):
    RecognizerName: Annotated[str, _aws_pattern("Comprehend", "ComprehendArnName")]
    DataAccessRoleArn: Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]
    InputDataConfig: EntityRecognizerInputDataConfigUnionTypeDef
    LanguageCode: LanguageCodeType
    VersionName: Optional[Annotated[str, _aws_pattern("Comprehend", "VersionName")]] = None
    Tags: Optional[List[TagTypeDef]] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigUnionTypeDef] = None
    ModelKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    ModelPolicy: Optional[Annotated[str, _aws_pattern("Comprehend", "Policy")]] = None


class EntityRecognizerPropertiesTypeDef(BaseValidatorModel):
    EntityRecognizerArn: Optional[Annotated[str, _aws_pattern("Comprehend", "EntityRecognizerArn")]] = None
    LanguageCode: Optional[LanguageCodeType] = None
    Status: Optional[ModelStatusType] = None
    Message: Optional[str] = None
    SubmitTime: Optional[datetime] = None
    EndTime: Optional[datetime] = None
    TrainingStartTime: Optional[datetime] = None
    TrainingEndTime: Optional[datetime] = None
    InputDataConfig: Optional[EntityRecognizerInputDataConfigOutputTypeDef] = None
    RecognizerMetadata: Optional[EntityRecognizerMetadataTypeDef] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]] = None
    VolumeKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VpcConfig: Optional[VpcConfigOutputTypeDef] = None
    ModelKmsKeyId: Optional[Annotated[str, _aws_pattern("Comprehend", "KmsKeyId")]] = None
    VersionName: Optional[Annotated[str, _aws_pattern("Comprehend", "VersionName")]] = None
    SourceModelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "EntityRecognizerArn")]] = None
    FlywheelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendFlywheelArn")]] = None
    OutputDataConfig: Optional[EntityRecognizerOutputDataConfigTypeDef] = None


# This class is the output for the 'detect_entities' function.
class DetectEntitiesResponseTypeDef(BaseValidatorModel):
    Entities: List[EntityTypeDef]
    DocumentMetadata: DocumentMetadataTypeDef
    DocumentType: List[DocumentTypeListItemTypeDef]
    Blocks: List[BlockTypeDef]
    Errors: List[ErrorsListItemTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'batch_detect_syntax' function.
class BatchDetectSyntaxResponseTypeDef(BaseValidatorModel):
    ResultList: List[BatchDetectSyntaxItemResultTypeDef]
    ErrorList: List[BatchItemErrorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class BatchDetectTargetedSentimentItemResultTypeDef(BaseValidatorModel):
    Index: Optional[int] = None
    Entities: Optional[List[TargetedSentimentEntityTypeDef]] = None


# This class is the output for the 'detect_targeted_sentiment' function.
class DetectTargetedSentimentResponseTypeDef(BaseValidatorModel):
    Entities: List[TargetedSentimentEntityTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'batch_detect_entities' function.
class BatchDetectEntitiesResponseTypeDef(BaseValidatorModel):
    ResultList: List[BatchDetectEntitiesItemResultTypeDef]
    ErrorList: List[BatchItemErrorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_flywheel' function.
class DescribeFlywheelResponseTypeDef(BaseValidatorModel):
    FlywheelProperties: FlywheelPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_flywheel' function.
class UpdateFlywheelResponseTypeDef(BaseValidatorModel):
    FlywheelProperties: FlywheelPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'create_flywheel' function.
class CreateFlywheelRequestTypeDef(BaseValidatorModel):
    FlywheelName: Annotated[str, _aws_pattern("Comprehend", "ComprehendArnName")]
    DataAccessRoleArn: Annotated[str, _aws_pattern("Comprehend", "IamRoleArn")]
    DataLakeS3Uri: Annotated[str, _aws_pattern("Comprehend", "FlywheelS3Uri")]
    ActiveModelArn: Optional[Annotated[str, _aws_pattern("Comprehend", "ComprehendModelArn")]] = None
    TaskConfig: Optional[TaskConfigUnionTypeDef] = None
    ModelType: Optional[ModelTypeType] = None
    DataSecurityConfig: Optional[DataSecurityConfigUnionTypeDef] = None
    ClientRequestToken: Optional[Annotated[str, _aws_pattern("Comprehend", "ClientRequestTokenString")]] = None
    Tags: Optional[List[TagTypeDef]] = None


# This class is the output for the 'describe_entity_recognizer' function.
class DescribeEntityRecognizerResponseTypeDef(BaseValidatorModel):
    EntityRecognizerProperties: EntityRecognizerPropertiesTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_entity_recognizers' function.
class ListEntityRecognizersResponseTypeDef(BaseValidatorModel):
    EntityRecognizerPropertiesList: List[EntityRecognizerPropertiesTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'batch_detect_targeted_sentiment' function.
class BatchDetectTargetedSentimentResponseTypeDef(BaseValidatorModel):
    ResultList: List[BatchDetectTargetedSentimentItemResultTypeDef]
    ErrorList: List[BatchItemErrorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
