# This file is auto-generated by aws_resource_validator.generator.pipeline_b.
# Do not edit manually; run `arv-generate pipeline-b` to refresh it.
from datetime import datetime
from decimal import Decimal
from typing import (
    Annotated,
    Any,
    Callable,
    Dict,
    FrozenSet,
    IO,
    List,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    Union,
)

from botocore.client import BaseClient
from botocore.response import StreamingBody
from pydantic import Field

from aws_resource_validator.core.base_validator_model import BaseValidatorModel, EventStream
from aws_resource_validator.core.pattern_validation import aws_field_pattern as _aws_pattern
from aws_resource_validator.pydantic_models.bcm_recommended_actions.bcm_recommended_actions_constants import *  # noqa: F401,F403

# Optional boto3 symbols — imported lazily so services that don't need them
# aren't forced to pull in boto3 at import time.
try:
    from boto3.dynamodb.conditions import ConditionBase  # noqa: F401
except ImportError:  # pragma: no cover
    ConditionBase = Any  # type: ignore[assignment,misc]
try:
    from boto3.s3.transfer import TransferConfig  # noqa: F401
except ImportError:  # pragma: no cover
    TransferConfig = Any  # type: ignore[assignment,misc]


class ActionFilterTypeDef(BaseValidatorModel):
    key: FilterNameType
    matchOption: MatchOptionType
    values: List[Annotated[str, _aws_pattern("BcmRecommendedActions", "FilterValue")]]


class PaginatorConfigTypeDef(BaseValidatorModel):
    MaxItems: Optional[int] = None
    PageSize: Optional[int] = None
    StartingToken: Optional[str] = None


class RecommendedActionTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    type: Optional[ActionTypeType] = None
    accountId: Optional[Annotated[str, _aws_pattern("BcmRecommendedActions", "AccountId")]] = None
    severity: Optional[SeverityType] = None
    feature: Optional[FeatureType] = None
    context: Optional[Dict[str, str]] = None
    nextSteps: Optional[List[str]] = None
    lastUpdatedTimeStamp: Optional[str] = None


class ResponseMetadataTypeDef(BaseValidatorModel):
    RequestId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, str]
    RetryAttempts: int
    HostId: Optional[str] = None


class RequestFilterTypeDef(BaseValidatorModel):
    actions: Optional[List[ActionFilterTypeDef]] = None


# This class is the output for the 'list_recommended_actions' function.
class ListRecommendedActionsResponseTypeDef(BaseValidatorModel):
    recommendedActions: List[RecommendedActionTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[Annotated[str, _aws_pattern("BcmRecommendedActions", "NextToken")]] = None


class ListRecommendedActionsRequestPaginateTypeDef(BaseValidatorModel):
    filter: Optional[RequestFilterTypeDef] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the input for the 'list_recommended_actions' function.
class ListRecommendedActionsRequestTypeDef(BaseValidatorModel):
    filter: Optional[RequestFilterTypeDef] = None
    maxResults: Optional[int] = None
    nextToken: Optional[Annotated[str, _aws_pattern("BcmRecommendedActions", "NextToken")]] = None
