# This file is auto-generated by aws_resource_validator.generator.pipeline_b.
# Do not edit manually; run `arv-generate pipeline-b` to refresh it.
from datetime import datetime
from decimal import Decimal
from typing import (
    Any,
    Callable,
    Dict,
    FrozenSet,
    IO,
    List,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    Union,
)

from botocore.client import BaseClient
from botocore.response import StreamingBody
from pydantic import Field

from aws_resource_validator.core.base_validator_model import BaseValidatorModel, EventStream
from aws_resource_validator.pydantic_models.auditmanager.auditmanager_constants import *  # noqa: F401,F403

# Optional boto3 symbols — imported lazily so services that don't need them
# aren't forced to pull in boto3 at import time.
try:
    from boto3.dynamodb.conditions import ConditionBase  # noqa: F401
except ImportError:  # pragma: no cover
    ConditionBase = Any  # type: ignore[assignment,misc]
try:
    from boto3.s3.transfer import TransferConfig  # noqa: F401
except ImportError:  # pragma: no cover
    TransferConfig = Any  # type: ignore[assignment,misc]


class AWSAccountTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    emailAddress: Optional[str] = None
    name: Optional[str] = None


class AWSServiceTypeDef(BaseValidatorModel):
    serviceName: Optional[str] = None


class DelegationTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    assessmentName: Optional[str] = None
    assessmentId: Optional[str] = None
    status: Optional[DelegationStatusType] = None
    roleArn: Optional[str] = None
    roleType: Optional[RoleTypeType] = None
    creationTime: Optional[datetime] = None
    lastUpdated: Optional[datetime] = None
    controlSetId: Optional[str] = None
    comment: Optional[str] = None
    createdBy: Optional[str] = None


class RoleTypeDef(BaseValidatorModel):
    roleType: RoleTypeType
    roleArn: str


class ControlCommentTypeDef(BaseValidatorModel):
    authorName: Optional[str] = None
    commentBody: Optional[str] = None
    postedDate: Optional[datetime] = None


class AssessmentEvidenceFolderTypeDef(BaseValidatorModel):
    name: Optional[str] = None
    date: Optional[datetime] = None
    assessmentId: Optional[str] = None
    controlSetId: Optional[str] = None
    controlId: Optional[str] = None
    id: Optional[str] = None
    dataSource: Optional[str] = None
    author: Optional[str] = None
    totalEvidence: Optional[int] = None
    assessmentReportSelectionCount: Optional[int] = None
    controlName: Optional[str] = None
    evidenceResourcesIncludedCount: Optional[int] = None
    evidenceByTypeConfigurationDataCount: Optional[int] = None
    evidenceByTypeManualCount: Optional[int] = None
    evidenceByTypeComplianceCheckCount: Optional[int] = None
    evidenceByTypeComplianceCheckIssuesCount: Optional[int] = None
    evidenceByTypeUserActivityCount: Optional[int] = None
    evidenceAwsServiceSourceCount: Optional[int] = None


class AssessmentFrameworkMetadataTypeDef(BaseValidatorModel):
    arn: Optional[str] = None
    id: Optional[str] = None
    type: Optional[FrameworkTypeType] = None
    name: Optional[str] = None
    description: Optional[str] = None
    logo: Optional[str] = None
    complianceType: Optional[str] = None
    controlsCount: Optional[int] = None
    controlSetsCount: Optional[int] = None
    createdAt: Optional[datetime] = None
    lastUpdatedAt: Optional[datetime] = None


class AssessmentFrameworkShareRequestTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    frameworkId: Optional[str] = None
    frameworkName: Optional[str] = None
    frameworkDescription: Optional[str] = None
    status: Optional[ShareRequestStatusType] = None
    sourceAccount: Optional[str] = None
    destinationAccount: Optional[str] = None
    destinationRegion: Optional[str] = None
    expirationTime: Optional[datetime] = None
    creationTime: Optional[datetime] = None
    lastUpdated: Optional[datetime] = None
    comment: Optional[str] = None
    standardControlsCount: Optional[int] = None
    customControlsCount: Optional[int] = None
    complianceType: Optional[str] = None


class FrameworkMetadataTypeDef(BaseValidatorModel):
    name: Optional[str] = None
    description: Optional[str] = None
    logo: Optional[str] = None
    complianceType: Optional[str] = None


class AssessmentReportsDestinationTypeDef(BaseValidatorModel):
    destinationType: Optional[Literal["S3"]] = None
    destination: Optional[str] = None


class AssessmentReportEvidenceErrorTypeDef(BaseValidatorModel):
    evidenceId: Optional[str] = None
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None


class AssessmentReportMetadataTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    assessmentId: Optional[str] = None
    assessmentName: Optional[str] = None
    author: Optional[str] = None
    status: Optional[AssessmentReportStatusType] = None
    creationTime: Optional[datetime] = None


class AssessmentReportTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    awsAccountId: Optional[str] = None
    assessmentId: Optional[str] = None
    assessmentName: Optional[str] = None
    author: Optional[str] = None
    status: Optional[AssessmentReportStatusType] = None
    creationTime: Optional[datetime] = None


class AssociateAssessmentReportEvidenceFolderRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    evidenceFolderId: str


# This class is the input for the 'batch_associate_assessment_report_evidence' function.
class BatchAssociateAssessmentReportEvidenceRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    evidenceFolderId: str
    evidenceIds: List[str]


class ResponseMetadataTypeDef(BaseValidatorModel):
    RequestId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, str]
    RetryAttempts: int
    HostId: Optional[str] = None


class CreateDelegationRequestTypeDef(BaseValidatorModel):
    comment: Optional[str] = None
    controlSetId: Optional[str] = None
    roleArn: Optional[str] = None
    roleType: Optional[RoleTypeType] = None


class BatchDeleteDelegationByAssessmentErrorTypeDef(BaseValidatorModel):
    delegationId: Optional[str] = None
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None


# This class is the input for the 'batch_delete_delegation_by_assessment' function.
class BatchDeleteDelegationByAssessmentRequestTypeDef(BaseValidatorModel):
    delegationIds: List[str]
    assessmentId: str


# This class is the input for the 'batch_disassociate_assessment_report_evidence' function.
class BatchDisassociateAssessmentReportEvidenceRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    evidenceFolderId: str
    evidenceIds: List[str]


class ManualEvidenceTypeDef(BaseValidatorModel):
    s3ResourcePath: Optional[str] = None
    textResponse: Optional[str] = None
    evidenceFileName: Optional[str] = None


class ChangeLogTypeDef(BaseValidatorModel):
    objectType: Optional[ObjectTypeEnumType] = None
    objectName: Optional[str] = None
    action: Optional[ActionEnumType] = None
    createdAt: Optional[datetime] = None
    createdBy: Optional[str] = None


class EvidenceInsightsTypeDef(BaseValidatorModel):
    noncompliantEvidenceCount: Optional[int] = None
    compliantEvidenceCount: Optional[int] = None
    inconclusiveEvidenceCount: Optional[int] = None


class SourceKeywordTypeDef(BaseValidatorModel):
    keywordInputType: Optional[KeywordInputTypeType] = None
    keywordValue: Optional[str] = None


class ControlMetadataTypeDef(BaseValidatorModel):
    arn: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    controlSources: Optional[str] = None
    createdAt: Optional[datetime] = None
    lastUpdatedAt: Optional[datetime] = None


class CreateAssessmentFrameworkControlTypeDef(BaseValidatorModel):
    id: str


# This class is the input for the 'create_assessment_report' function.
class CreateAssessmentReportRequestTypeDef(BaseValidatorModel):
    name: str
    assessmentId: str
    description: Optional[str] = None
    queryStatement: Optional[str] = None


class DefaultExportDestinationTypeDef(BaseValidatorModel):
    destinationType: Optional[Literal["S3"]] = None
    destination: Optional[str] = None


class DelegationMetadataTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    assessmentName: Optional[str] = None
    assessmentId: Optional[str] = None
    status: Optional[DelegationStatusType] = None
    roleArn: Optional[str] = None
    creationTime: Optional[datetime] = None
    controlSetName: Optional[str] = None


class DeleteAssessmentFrameworkRequestTypeDef(BaseValidatorModel):
    frameworkId: str


class DeleteAssessmentFrameworkShareRequestTypeDef(BaseValidatorModel):
    requestId: str
    requestType: ShareRequestTypeType


class DeleteAssessmentReportRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    assessmentReportId: str


class DeleteAssessmentRequestTypeDef(BaseValidatorModel):
    assessmentId: str


class DeleteControlRequestTypeDef(BaseValidatorModel):
    controlId: str


class DeregisterOrganizationAdminAccountRequestTypeDef(BaseValidatorModel):
    adminAccountId: Optional[str] = None


class DeregistrationPolicyTypeDef(BaseValidatorModel):
    deleteResources: Optional[DeleteResourcesType] = None


class DisassociateAssessmentReportEvidenceFolderRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    evidenceFolderId: str


class EvidenceFinderEnablementTypeDef(BaseValidatorModel):
    eventDataStoreArn: Optional[str] = None
    enablementStatus: Optional[EvidenceFinderEnablementStatusType] = None
    backfillStatus: Optional[EvidenceFinderBackfillStatusType] = None
    error: Optional[str] = None


class ResourceTypeDef(BaseValidatorModel):
    arn: Optional[str] = None
    value: Optional[str] = None
    complianceCheck: Optional[str] = None


# This class is the input for the 'get_assessment_framework' function.
class GetAssessmentFrameworkRequestTypeDef(BaseValidatorModel):
    frameworkId: str


# This class is the input for the 'get_assessment_report_url' function.
class GetAssessmentReportUrlRequestTypeDef(BaseValidatorModel):
    assessmentReportId: str
    assessmentId: str


class URLTypeDef(BaseValidatorModel):
    hyperlinkName: Optional[str] = None
    link: Optional[str] = None


# This class is the input for the 'get_assessment' function.
class GetAssessmentRequestTypeDef(BaseValidatorModel):
    assessmentId: str


# This class is the input for the 'get_change_logs' function.
class GetChangeLogsRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    controlSetId: Optional[str] = None
    controlId: Optional[str] = None
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'get_control' function.
class GetControlRequestTypeDef(BaseValidatorModel):
    controlId: str


# This class is the input for the 'get_delegations' function.
class GetDelegationsRequestTypeDef(BaseValidatorModel):
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'get_evidence_by_evidence_folder' function.
class GetEvidenceByEvidenceFolderRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    controlSetId: str
    evidenceFolderId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'get_evidence_file_upload_url' function.
class GetEvidenceFileUploadUrlRequestTypeDef(BaseValidatorModel):
    fileName: str


# This class is the input for the 'get_evidence_folder' function.
class GetEvidenceFolderRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    controlSetId: str
    evidenceFolderId: str


# This class is the input for the 'get_evidence_folders_by_assessment_control' function.
class GetEvidenceFoldersByAssessmentControlRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    controlSetId: str
    controlId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'get_evidence_folders_by_assessment' function.
class GetEvidenceFoldersByAssessmentRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'get_evidence' function.
class GetEvidenceRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    controlSetId: str
    evidenceFolderId: str
    evidenceId: str


# This class is the input for the 'get_insights_by_assessment' function.
class GetInsightsByAssessmentRequestTypeDef(BaseValidatorModel):
    assessmentId: str


class InsightsByAssessmentTypeDef(BaseValidatorModel):
    noncompliantEvidenceCount: Optional[int] = None
    compliantEvidenceCount: Optional[int] = None
    inconclusiveEvidenceCount: Optional[int] = None
    assessmentControlsCountByNoncompliantEvidence: Optional[int] = None
    totalAssessmentControlsCount: Optional[int] = None
    lastUpdated: Optional[datetime] = None


class InsightsTypeDef(BaseValidatorModel):
    activeAssessmentsCount: Optional[int] = None
    noncompliantEvidenceCount: Optional[int] = None
    compliantEvidenceCount: Optional[int] = None
    inconclusiveEvidenceCount: Optional[int] = None
    assessmentControlsCountByNoncompliantEvidence: Optional[int] = None
    totalAssessmentControlsCount: Optional[int] = None
    lastUpdated: Optional[datetime] = None


class ServiceMetadataTypeDef(BaseValidatorModel):
    name: Optional[str] = None
    displayName: Optional[str] = None
    description: Optional[str] = None
    category: Optional[str] = None


# This class is the input for the 'get_settings' function.
class GetSettingsRequestTypeDef(BaseValidatorModel):
    attribute: SettingAttributeType


# This class is the input for the 'list_assessment_control_insights_by_control_domain' function.
class ListAssessmentControlInsightsByControlDomainRequestTypeDef(BaseValidatorModel):
    controlDomainId: str
    assessmentId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_assessment_framework_share_requests' function.
class ListAssessmentFrameworkShareRequestsRequestTypeDef(BaseValidatorModel):
    requestType: ShareRequestTypeType
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_assessment_frameworks' function.
class ListAssessmentFrameworksRequestTypeDef(BaseValidatorModel):
    frameworkType: FrameworkTypeType
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_assessment_reports' function.
class ListAssessmentReportsRequestTypeDef(BaseValidatorModel):
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_assessments' function.
class ListAssessmentsRequestTypeDef(BaseValidatorModel):
    status: Optional[AssessmentStatusType] = None
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_control_domain_insights_by_assessment' function.
class ListControlDomainInsightsByAssessmentRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_control_domain_insights' function.
class ListControlDomainInsightsRequestTypeDef(BaseValidatorModel):
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_control_insights_by_control_domain' function.
class ListControlInsightsByControlDomainRequestTypeDef(BaseValidatorModel):
    controlDomainId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_controls' function.
class ListControlsRequestTypeDef(BaseValidatorModel):
    controlType: ControlTypeType
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None
    controlCatalogId: Optional[str] = None


# This class is the input for the 'list_keywords_for_data_source' function.
class ListKeywordsForDataSourceRequestTypeDef(BaseValidatorModel):
    source: DataSourceTypeType
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_notifications' function.
class ListNotificationsRequestTypeDef(BaseValidatorModel):
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


class NotificationTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    assessmentId: Optional[str] = None
    assessmentName: Optional[str] = None
    controlSetId: Optional[str] = None
    controlSetName: Optional[str] = None
    description: Optional[str] = None
    eventTime: Optional[datetime] = None
    source: Optional[str] = None


# This class is the input for the 'list_tags_for_resource' function.
class ListTagsForResourceRequestTypeDef(BaseValidatorModel):
    resourceArn: str


# This class is the input for the 'register_account' function.
class RegisterAccountRequestTypeDef(BaseValidatorModel):
    kmsKey: Optional[str] = None
    delegatedAdminAccount: Optional[str] = None


# This class is the input for the 'register_organization_admin_account' function.
class RegisterOrganizationAdminAccountRequestTypeDef(BaseValidatorModel):
    adminAccountId: str


# This class is the input for the 'start_assessment_framework_share' function.
class StartAssessmentFrameworkShareRequestTypeDef(BaseValidatorModel):
    frameworkId: str
    destinationAccount: str
    destinationRegion: str
    comment: Optional[str] = None


class TagResourceRequestTypeDef(BaseValidatorModel):
    resourceArn: str
    tags: Dict[str, str]


class UntagResourceRequestTypeDef(BaseValidatorModel):
    resourceArn: str
    tagKeys: List[str]


# This class is the input for the 'update_assessment_control' function.
class UpdateAssessmentControlRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    controlSetId: str
    controlId: str
    controlStatus: Optional[ControlStatusType] = None
    commentBody: Optional[str] = None


# This class is the input for the 'update_assessment_control_set_status' function.
class UpdateAssessmentControlSetStatusRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    controlSetId: str
    status: ControlSetStatusType
    comment: str


# This class is the input for the 'update_assessment_framework_share' function.
class UpdateAssessmentFrameworkShareRequestTypeDef(BaseValidatorModel):
    requestId: str
    requestType: ShareRequestTypeType
    action: ShareRequestActionType


# This class is the input for the 'update_assessment_status' function.
class UpdateAssessmentStatusRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    status: AssessmentStatusType


# This class is the input for the 'validate_assessment_report_integrity' function.
class ValidateAssessmentReportIntegrityRequestTypeDef(BaseValidatorModel):
    s3RelativePath: str


class ScopeOutputTypeDef(BaseValidatorModel):
    awsAccounts: Optional[List[AWSAccountTypeDef]] = None
    awsServices: Optional[List[AWSServiceTypeDef]] = None


class ScopeTypeDef(BaseValidatorModel):
    awsAccounts: Optional[List[AWSAccountTypeDef]] = None
    awsServices: Optional[List[AWSServiceTypeDef]] = None


class AssessmentMetadataItemTypeDef(BaseValidatorModel):
    name: Optional[str] = None
    id: Optional[str] = None
    complianceType: Optional[str] = None
    status: Optional[AssessmentStatusType] = None
    roles: Optional[List[RoleTypeDef]] = None
    delegations: Optional[List[DelegationTypeDef]] = None
    creationTime: Optional[datetime] = None
    lastUpdated: Optional[datetime] = None


class AssessmentControlTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    status: Optional[ControlStatusType] = None
    response: Optional[ControlResponseType] = None
    comments: Optional[List[ControlCommentTypeDef]] = None
    evidenceSources: Optional[List[str]] = None
    evidenceCount: Optional[int] = None
    assessmentReportEvidenceCount: Optional[int] = None


# This class is the output for the 'batch_associate_assessment_report_evidence' function.
class BatchAssociateAssessmentReportEvidenceResponseTypeDef(BaseValidatorModel):
    evidenceIds: List[str]
    errors: List[AssessmentReportEvidenceErrorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'batch_disassociate_assessment_report_evidence' function.
class BatchDisassociateAssessmentReportEvidenceResponseTypeDef(BaseValidatorModel):
    evidenceIds: List[str]
    errors: List[AssessmentReportEvidenceErrorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_assessment_report' function.
class CreateAssessmentReportResponseTypeDef(BaseValidatorModel):
    assessmentReport: AssessmentReportTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class DeregisterAccountResponseTypeDef(BaseValidatorModel):
    status: AccountStatusType
    ResponseMetadata: ResponseMetadataTypeDef


class GetAccountStatusResponseTypeDef(BaseValidatorModel):
    status: AccountStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_evidence_file_upload_url' function.
class GetEvidenceFileUploadUrlResponseTypeDef(BaseValidatorModel):
    evidenceFileName: str
    uploadUrl: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_evidence_folder' function.
class GetEvidenceFolderResponseTypeDef(BaseValidatorModel):
    evidenceFolder: AssessmentEvidenceFolderTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_evidence_folders_by_assessment_control' function.
class GetEvidenceFoldersByAssessmentControlResponseTypeDef(BaseValidatorModel):
    evidenceFolders: List[AssessmentEvidenceFolderTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'get_evidence_folders_by_assessment' function.
class GetEvidenceFoldersByAssessmentResponseTypeDef(BaseValidatorModel):
    evidenceFolders: List[AssessmentEvidenceFolderTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class GetOrganizationAdminAccountResponseTypeDef(BaseValidatorModel):
    adminAccountId: str
    organizationId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_assessment_framework_share_requests' function.
class ListAssessmentFrameworkShareRequestsResponseTypeDef(BaseValidatorModel):
    assessmentFrameworkShareRequests: List[AssessmentFrameworkShareRequestTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_assessment_frameworks' function.
class ListAssessmentFrameworksResponseTypeDef(BaseValidatorModel):
    frameworkMetadataList: List[AssessmentFrameworkMetadataTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_assessment_reports' function.
class ListAssessmentReportsResponseTypeDef(BaseValidatorModel):
    assessmentReports: List[AssessmentReportMetadataTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_keywords_for_data_source' function.
class ListKeywordsForDataSourceResponseTypeDef(BaseValidatorModel):
    keywords: List[str]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_tags_for_resource' function.
class ListTagsForResourceResponseTypeDef(BaseValidatorModel):
    tags: Dict[str, str]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'register_account' function.
class RegisterAccountResponseTypeDef(BaseValidatorModel):
    status: AccountStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'register_organization_admin_account' function.
class RegisterOrganizationAdminAccountResponseTypeDef(BaseValidatorModel):
    adminAccountId: str
    organizationId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'start_assessment_framework_share' function.
class StartAssessmentFrameworkShareResponseTypeDef(BaseValidatorModel):
    assessmentFrameworkShareRequest: AssessmentFrameworkShareRequestTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_assessment_framework_share' function.
class UpdateAssessmentFrameworkShareResponseTypeDef(BaseValidatorModel):
    assessmentFrameworkShareRequest: AssessmentFrameworkShareRequestTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'validate_assessment_report_integrity' function.
class ValidateAssessmentReportIntegrityResponseTypeDef(BaseValidatorModel):
    signatureValid: bool
    signatureAlgorithm: str
    signatureDateTime: str
    signatureKeyId: str
    validationErrors: List[str]
    ResponseMetadata: ResponseMetadataTypeDef


class BatchCreateDelegationByAssessmentErrorTypeDef(BaseValidatorModel):
    createDelegationRequest: Optional[CreateDelegationRequestTypeDef] = None
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None


# This class is the input for the 'batch_create_delegation_by_assessment' function.
class BatchCreateDelegationByAssessmentRequestTypeDef(BaseValidatorModel):
    createDelegationRequests: List[CreateDelegationRequestTypeDef]
    assessmentId: str


# This class is the output for the 'batch_delete_delegation_by_assessment' function.
class BatchDeleteDelegationByAssessmentResponseTypeDef(BaseValidatorModel):
    errors: List[BatchDeleteDelegationByAssessmentErrorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class BatchImportEvidenceToAssessmentControlErrorTypeDef(BaseValidatorModel):
    manualEvidence: Optional[ManualEvidenceTypeDef] = None
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None


# This class is the input for the 'batch_import_evidence_to_assessment_control' function.
class BatchImportEvidenceToAssessmentControlRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    controlSetId: str
    controlId: str
    manualEvidence: List[ManualEvidenceTypeDef]


# This class is the output for the 'get_change_logs' function.
class GetChangeLogsResponseTypeDef(BaseValidatorModel):
    changeLogs: List[ChangeLogTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class ControlDomainInsightsTypeDef(BaseValidatorModel):
    name: Optional[str] = None
    id: Optional[str] = None
    controlsCountByNoncompliantEvidence: Optional[int] = None
    totalControlsCount: Optional[int] = None
    evidenceInsights: Optional[EvidenceInsightsTypeDef] = None
    lastUpdated: Optional[datetime] = None


class ControlInsightsMetadataByAssessmentItemTypeDef(BaseValidatorModel):
    name: Optional[str] = None
    id: Optional[str] = None
    evidenceInsights: Optional[EvidenceInsightsTypeDef] = None
    controlSetName: Optional[str] = None
    lastUpdated: Optional[datetime] = None


class ControlInsightsMetadataItemTypeDef(BaseValidatorModel):
    name: Optional[str] = None
    id: Optional[str] = None
    evidenceInsights: Optional[EvidenceInsightsTypeDef] = None
    lastUpdated: Optional[datetime] = None


class ControlMappingSourceTypeDef(BaseValidatorModel):
    sourceId: Optional[str] = None
    sourceName: Optional[str] = None
    sourceDescription: Optional[str] = None
    sourceSetUpOption: Optional[SourceSetUpOptionType] = None
    sourceType: Optional[SourceTypeType] = None
    sourceKeyword: Optional[SourceKeywordTypeDef] = None
    sourceFrequency: Optional[SourceFrequencyType] = None
    troubleshootingText: Optional[str] = None


class CreateControlMappingSourceTypeDef(BaseValidatorModel):
    sourceName: Optional[str] = None
    sourceDescription: Optional[str] = None
    sourceSetUpOption: Optional[SourceSetUpOptionType] = None
    sourceType: Optional[SourceTypeType] = None
    sourceKeyword: Optional[SourceKeywordTypeDef] = None
    sourceFrequency: Optional[SourceFrequencyType] = None
    troubleshootingText: Optional[str] = None


# This class is the output for the 'list_controls' function.
class ListControlsResponseTypeDef(BaseValidatorModel):
    controlMetadataList: List[ControlMetadataTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class CreateAssessmentFrameworkControlSetTypeDef(BaseValidatorModel):
    name: str
    controls: Optional[List[CreateAssessmentFrameworkControlTypeDef]] = None


class UpdateAssessmentFrameworkControlSetTypeDef(BaseValidatorModel):
    name: str
    controls: List[CreateAssessmentFrameworkControlTypeDef]
    id: Optional[str] = None


# This class is the output for the 'get_delegations' function.
class GetDelegationsResponseTypeDef(BaseValidatorModel):
    delegations: List[DelegationMetadataTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the input for the 'update_settings' function.
class UpdateSettingsRequestTypeDef(BaseValidatorModel):
    snsTopic: Optional[str] = None
    defaultAssessmentReportsDestination: Optional[AssessmentReportsDestinationTypeDef] = None
    defaultProcessOwners: Optional[List[RoleTypeDef]] = None
    kmsKey: Optional[str] = None
    evidenceFinderEnabled: Optional[bool] = None
    deregistrationPolicy: Optional[DeregistrationPolicyTypeDef] = None
    defaultExportDestination: Optional[DefaultExportDestinationTypeDef] = None


class SettingsTypeDef(BaseValidatorModel):
    isAwsOrgEnabled: Optional[bool] = None
    snsTopic: Optional[str] = None
    defaultAssessmentReportsDestination: Optional[AssessmentReportsDestinationTypeDef] = None
    defaultProcessOwners: Optional[List[RoleTypeDef]] = None
    kmsKey: Optional[str] = None
    evidenceFinderEnablement: Optional[EvidenceFinderEnablementTypeDef] = None
    deregistrationPolicy: Optional[DeregistrationPolicyTypeDef] = None
    defaultExportDestination: Optional[DefaultExportDestinationTypeDef] = None


class EvidenceTypeDef(BaseValidatorModel):
    dataSource: Optional[str] = None
    evidenceAwsAccountId: Optional[str] = None
    time: Optional[datetime] = None
    eventSource: Optional[str] = None
    eventName: Optional[str] = None
    evidenceByType: Optional[str] = None
    resourcesIncluded: Optional[List[ResourceTypeDef]] = None
    attributes: Optional[Dict[str, str]] = None
    iamId: Optional[str] = None
    complianceCheck: Optional[str] = None
    awsOrganization: Optional[str] = None
    awsAccountId: Optional[str] = None
    evidenceFolderId: Optional[str] = None
    id: Optional[str] = None
    assessmentReportSelection: Optional[str] = None


# This class is the output for the 'get_assessment_report_url' function.
class GetAssessmentReportUrlResponseTypeDef(BaseValidatorModel):
    preSignedUrl: URLTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_insights_by_assessment' function.
class GetInsightsByAssessmentResponseTypeDef(BaseValidatorModel):
    insights: InsightsByAssessmentTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class GetInsightsResponseTypeDef(BaseValidatorModel):
    insights: InsightsTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class GetServicesInScopeResponseTypeDef(BaseValidatorModel):
    serviceMetadata: List[ServiceMetadataTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_notifications' function.
class ListNotificationsResponseTypeDef(BaseValidatorModel):
    notifications: List[NotificationTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class AssessmentMetadataTypeDef(BaseValidatorModel):
    name: Optional[str] = None
    id: Optional[str] = None
    description: Optional[str] = None
    complianceType: Optional[str] = None
    status: Optional[AssessmentStatusType] = None
    assessmentReportsDestination: Optional[AssessmentReportsDestinationTypeDef] = None
    scope: Optional[ScopeOutputTypeDef] = None
    roles: Optional[List[RoleTypeDef]] = None
    delegations: Optional[List[DelegationTypeDef]] = None
    creationTime: Optional[datetime] = None
    lastUpdated: Optional[datetime] = None


ScopeUnionTypeDef = Union[ScopeOutputTypeDef, ScopeTypeDef]


# This class is the output for the 'list_assessments' function.
class ListAssessmentsResponseTypeDef(BaseValidatorModel):
    assessmentMetadata: List[AssessmentMetadataItemTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class AssessmentControlSetTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    description: Optional[str] = None
    status: Optional[ControlSetStatusType] = None
    roles: Optional[List[RoleTypeDef]] = None
    controls: Optional[List[AssessmentControlTypeDef]] = None
    delegations: Optional[List[DelegationTypeDef]] = None
    systemEvidenceCount: Optional[int] = None
    manualEvidenceCount: Optional[int] = None


# This class is the output for the 'update_assessment_control' function.
class UpdateAssessmentControlResponseTypeDef(BaseValidatorModel):
    control: AssessmentControlTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'batch_create_delegation_by_assessment' function.
class BatchCreateDelegationByAssessmentResponseTypeDef(BaseValidatorModel):
    delegations: List[DelegationTypeDef]
    errors: List[BatchCreateDelegationByAssessmentErrorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'batch_import_evidence_to_assessment_control' function.
class BatchImportEvidenceToAssessmentControlResponseTypeDef(BaseValidatorModel):
    errors: List[BatchImportEvidenceToAssessmentControlErrorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_control_domain_insights_by_assessment' function.
class ListControlDomainInsightsByAssessmentResponseTypeDef(BaseValidatorModel):
    controlDomainInsights: List[ControlDomainInsightsTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_control_domain_insights' function.
class ListControlDomainInsightsResponseTypeDef(BaseValidatorModel):
    controlDomainInsights: List[ControlDomainInsightsTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_assessment_control_insights_by_control_domain' function.
class ListAssessmentControlInsightsByControlDomainResponseTypeDef(BaseValidatorModel):
    controlInsightsByAssessment: List[ControlInsightsMetadataByAssessmentItemTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_control_insights_by_control_domain' function.
class ListControlInsightsByControlDomainResponseTypeDef(BaseValidatorModel):
    controlInsightsMetadata: List[ControlInsightsMetadataItemTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class ControlTypeDef(BaseValidatorModel):
    arn: Optional[str] = None
    id: Optional[str] = None
    type: Optional[ControlTypeType] = None
    name: Optional[str] = None
    description: Optional[str] = None
    testingInformation: Optional[str] = None
    actionPlanTitle: Optional[str] = None
    actionPlanInstructions: Optional[str] = None
    controlSources: Optional[str] = None
    controlMappingSources: Optional[List[ControlMappingSourceTypeDef]] = None
    createdAt: Optional[datetime] = None
    lastUpdatedAt: Optional[datetime] = None
    createdBy: Optional[str] = None
    lastUpdatedBy: Optional[str] = None
    tags: Optional[Dict[str, str]] = None
    state: Optional[ControlStateType] = None


# This class is the input for the 'update_control' function.
class UpdateControlRequestTypeDef(BaseValidatorModel):
    controlId: str
    name: str
    controlMappingSources: List[ControlMappingSourceTypeDef]
    description: Optional[str] = None
    testingInformation: Optional[str] = None
    actionPlanTitle: Optional[str] = None
    actionPlanInstructions: Optional[str] = None


# This class is the input for the 'create_control' function.
class CreateControlRequestTypeDef(BaseValidatorModel):
    name: str
    controlMappingSources: List[CreateControlMappingSourceTypeDef]
    description: Optional[str] = None
    testingInformation: Optional[str] = None
    actionPlanTitle: Optional[str] = None
    actionPlanInstructions: Optional[str] = None
    tags: Optional[Dict[str, str]] = None


# This class is the input for the 'create_assessment_framework' function.
class CreateAssessmentFrameworkRequestTypeDef(BaseValidatorModel):
    name: str
    controlSets: List[CreateAssessmentFrameworkControlSetTypeDef]
    description: Optional[str] = None
    complianceType: Optional[str] = None
    tags: Optional[Dict[str, str]] = None


# This class is the input for the 'update_assessment_framework' function.
class UpdateAssessmentFrameworkRequestTypeDef(BaseValidatorModel):
    frameworkId: str
    name: str
    controlSets: List[UpdateAssessmentFrameworkControlSetTypeDef]
    description: Optional[str] = None
    complianceType: Optional[str] = None


# This class is the output for the 'get_settings' function.
class GetSettingsResponseTypeDef(BaseValidatorModel):
    settings: SettingsTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_settings' function.
class UpdateSettingsResponseTypeDef(BaseValidatorModel):
    settings: SettingsTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_evidence_by_evidence_folder' function.
class GetEvidenceByEvidenceFolderResponseTypeDef(BaseValidatorModel):
    evidence: List[EvidenceTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'get_evidence' function.
class GetEvidenceResponseTypeDef(BaseValidatorModel):
    evidence: EvidenceTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'create_assessment' function.
class CreateAssessmentRequestTypeDef(BaseValidatorModel):
    name: str
    assessmentReportsDestination: AssessmentReportsDestinationTypeDef
    scope: ScopeUnionTypeDef
    roles: List[RoleTypeDef]
    frameworkId: str
    description: Optional[str] = None
    tags: Optional[Dict[str, str]] = None


# This class is the input for the 'update_assessment' function.
class UpdateAssessmentRequestTypeDef(BaseValidatorModel):
    assessmentId: str
    scope: ScopeUnionTypeDef
    assessmentName: Optional[str] = None
    assessmentDescription: Optional[str] = None
    assessmentReportsDestination: Optional[AssessmentReportsDestinationTypeDef] = None
    roles: Optional[List[RoleTypeDef]] = None


class AssessmentFrameworkTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    arn: Optional[str] = None
    metadata: Optional[FrameworkMetadataTypeDef] = None
    controlSets: Optional[List[AssessmentControlSetTypeDef]] = None


# This class is the output for the 'update_assessment_control_set_status' function.
class UpdateAssessmentControlSetStatusResponseTypeDef(BaseValidatorModel):
    controlSet: AssessmentControlSetTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class ControlSetTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    name: Optional[str] = None
    controls: Optional[List[ControlTypeDef]] = None


# This class is the output for the 'create_control' function.
class CreateControlResponseTypeDef(BaseValidatorModel):
    control: ControlTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_control' function.
class GetControlResponseTypeDef(BaseValidatorModel):
    control: ControlTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_control' function.
class UpdateControlResponseTypeDef(BaseValidatorModel):
    control: ControlTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class AssessmentTypeDef(BaseValidatorModel):
    arn: Optional[str] = None
    awsAccount: Optional[AWSAccountTypeDef] = None
    metadata: Optional[AssessmentMetadataTypeDef] = None
    framework: Optional[AssessmentFrameworkTypeDef] = None
    tags: Optional[Dict[str, str]] = None


class FrameworkTypeDef(BaseValidatorModel):
    arn: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    type: Optional[FrameworkTypeType] = None
    complianceType: Optional[str] = None
    description: Optional[str] = None
    logo: Optional[str] = None
    controlSources: Optional[str] = None
    controlSets: Optional[List[ControlSetTypeDef]] = None
    createdAt: Optional[datetime] = None
    lastUpdatedAt: Optional[datetime] = None
    createdBy: Optional[str] = None
    lastUpdatedBy: Optional[str] = None
    tags: Optional[Dict[str, str]] = None


# This class is the output for the 'create_assessment' function.
class CreateAssessmentResponseTypeDef(BaseValidatorModel):
    assessment: AssessmentTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_assessment' function.
class GetAssessmentResponseTypeDef(BaseValidatorModel):
    assessment: AssessmentTypeDef
    userRole: RoleTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_assessment' function.
class UpdateAssessmentResponseTypeDef(BaseValidatorModel):
    assessment: AssessmentTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_assessment_status' function.
class UpdateAssessmentStatusResponseTypeDef(BaseValidatorModel):
    assessment: AssessmentTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_assessment_framework' function.
class CreateAssessmentFrameworkResponseTypeDef(BaseValidatorModel):
    framework: FrameworkTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_assessment_framework' function.
class GetAssessmentFrameworkResponseTypeDef(BaseValidatorModel):
    framework: FrameworkTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_assessment_framework' function.
class UpdateAssessmentFrameworkResponseTypeDef(BaseValidatorModel):
    framework: FrameworkTypeDef
    ResponseMetadata: ResponseMetadataTypeDef
