# This file is auto-generated by aws_resource_validator.generator.pipeline_b.
# Do not edit manually; run `arv-generate pipeline-b` to refresh it.
from datetime import datetime
from decimal import Decimal
from typing import (
    Any,
    Callable,
    Dict,
    FrozenSet,
    IO,
    List,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    Union,
)

from botocore.client import BaseClient
from botocore.response import StreamingBody
from pydantic import Field

from aws_resource_validator.core.base_validator_model import BaseValidatorModel, EventStream
from aws_resource_validator.pydantic_models.keyspaces.keyspaces_constants import *  # noqa: F401,F403

# Optional boto3 symbols — imported lazily so services that don't need them
# aren't forced to pull in boto3 at import time.
try:
    from boto3.dynamodb.conditions import ConditionBase  # noqa: F401
except ImportError:  # pragma: no cover
    ConditionBase = Any  # type: ignore[assignment,misc]
try:
    from boto3.s3.transfer import TransferConfig  # noqa: F401
except ImportError:  # pragma: no cover
    TransferConfig = Any  # type: ignore[assignment,misc]


class TargetTrackingScalingPolicyConfigurationTypeDef(BaseValidatorModel):
    targetValue: float
    disableScaleIn: Optional[bool] = None
    scaleInCooldown: Optional[int] = None
    scaleOutCooldown: Optional[int] = None


class CapacitySpecificationSummaryTypeDef(BaseValidatorModel):
    throughputMode: ThroughputModeType
    readCapacityUnits: Optional[int] = None
    writeCapacityUnits: Optional[int] = None
    lastUpdateToPayPerRequestTimestamp: Optional[datetime] = None


class CapacitySpecificationTypeDef(BaseValidatorModel):
    throughputMode: ThroughputModeType
    readCapacityUnits: Optional[int] = None
    writeCapacityUnits: Optional[int] = None


class CdcSpecificationSummaryTypeDef(BaseValidatorModel):
    status: CdcStatusType
    viewType: Optional[ViewTypeType] = None


class TagTypeDef(BaseValidatorModel):
    key: str
    value: str


class ClientSideTimestampsTypeDef(BaseValidatorModel):
    status: Literal["ENABLED"]


class ClusteringKeyTypeDef(BaseValidatorModel):
    name: str
    orderBy: SortOrderType


class ColumnDefinitionTypeDef(BaseValidatorModel):
    name: str
    type: str


class CommentTypeDef(BaseValidatorModel):
    message: str


class ReplicationSpecificationTypeDef(BaseValidatorModel):
    replicationStrategy: RsType
    regionList: Optional[List[str]] = None


class ResponseMetadataTypeDef(BaseValidatorModel):
    RequestId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, str]
    RetryAttempts: int
    HostId: Optional[str] = None


class EncryptionSpecificationTypeDef(BaseValidatorModel):
    type: EncryptionTypeType
    kmsKeyIdentifier: Optional[str] = None


class PointInTimeRecoveryTypeDef(BaseValidatorModel):
    status: PointInTimeRecoveryStatusType


class TimeToLiveTypeDef(BaseValidatorModel):
    status: Literal["ENABLED"]


class WarmThroughputSpecificationTypeDef(BaseValidatorModel):
    readUnitsPerSecond: Optional[int] = None
    writeUnitsPerSecond: Optional[int] = None


class FieldDefinitionTypeDef(BaseValidatorModel):
    name: str
    type: str


class DeleteKeyspaceRequestTypeDef(BaseValidatorModel):
    keyspaceName: str


class DeleteTableRequestTypeDef(BaseValidatorModel):
    keyspaceName: str
    tableName: str


# This class is the input for the 'delete_type' function.
class DeleteTypeRequestTypeDef(BaseValidatorModel):
    keyspaceName: str
    typeName: str


# This class is the input for the 'get_keyspace' function.
class GetKeyspaceRequestTypeDef(BaseValidatorModel):
    keyspaceName: str


class ReplicationGroupStatusTypeDef(BaseValidatorModel):
    region: str
    keyspaceStatus: KeyspaceStatusType
    tablesReplicationProgress: Optional[str] = None


# This class is the input for the 'get_table_auto_scaling_settings' function.
class GetTableAutoScalingSettingsRequestTypeDef(BaseValidatorModel):
    keyspaceName: str
    tableName: str


# This class is the input for the 'get_table' function.
class GetTableRequestTypeDef(BaseValidatorModel):
    keyspaceName: str
    tableName: str


class PointInTimeRecoverySummaryTypeDef(BaseValidatorModel):
    status: PointInTimeRecoveryStatusType
    earliestRestorableTimestamp: Optional[datetime] = None


class WarmThroughputSpecificationSummaryTypeDef(BaseValidatorModel):
    readUnitsPerSecond: int
    writeUnitsPerSecond: int
    status: WarmThroughputStatusType


# This class is the input for the 'get_type' function.
class GetTypeRequestTypeDef(BaseValidatorModel):
    keyspaceName: str
    typeName: str


class KeyspaceSummaryTypeDef(BaseValidatorModel):
    keyspaceName: str
    resourceArn: str
    replicationStrategy: RsType
    replicationRegions: Optional[List[str]] = None


class PaginatorConfigTypeDef(BaseValidatorModel):
    MaxItems: Optional[int] = None
    PageSize: Optional[int] = None
    StartingToken: Optional[str] = None


# This class is the input for the 'list_keyspaces' function.
class ListKeyspacesRequestTypeDef(BaseValidatorModel):
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_tables' function.
class ListTablesRequestTypeDef(BaseValidatorModel):
    keyspaceName: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


class TableSummaryTypeDef(BaseValidatorModel):
    keyspaceName: str
    tableName: str
    resourceArn: str


# This class is the input for the 'list_tags_for_resource' function.
class ListTagsForResourceRequestTypeDef(BaseValidatorModel):
    resourceArn: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_types' function.
class ListTypesRequestTypeDef(BaseValidatorModel):
    keyspaceName: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


class PartitionKeyTypeDef(BaseValidatorModel):
    name: str


TimestampTypeDef = Union[datetime, str]


class StaticColumnTypeDef(BaseValidatorModel):
    name: str


class AutoScalingPolicyTypeDef(BaseValidatorModel):
    targetTrackingScalingPolicyConfiguration: Optional[TargetTrackingScalingPolicyConfigurationTypeDef] = None


class CdcSpecificationTypeDef(BaseValidatorModel):
    status: CdcStatusType
    viewType: Optional[ViewTypeType] = None
    tags: Optional[List[TagTypeDef]] = None
    propagateTags: Optional[CdcPropagateTagsType] = None


class TagResourceRequestTypeDef(BaseValidatorModel):
    resourceArn: str
    tags: List[TagTypeDef]


class UntagResourceRequestTypeDef(BaseValidatorModel):
    resourceArn: str
    tags: List[TagTypeDef]


# This class is the input for the 'create_keyspace' function.
class CreateKeyspaceRequestTypeDef(BaseValidatorModel):
    keyspaceName: str
    tags: Optional[List[TagTypeDef]] = None
    replicationSpecification: Optional[ReplicationSpecificationTypeDef] = None


# This class is the input for the 'update_keyspace' function.
class UpdateKeyspaceRequestTypeDef(BaseValidatorModel):
    keyspaceName: str
    replicationSpecification: ReplicationSpecificationTypeDef
    clientSideTimestamps: Optional[ClientSideTimestampsTypeDef] = None


# This class is the output for the 'create_keyspace' function.
class CreateKeyspaceResponseTypeDef(BaseValidatorModel):
    resourceArn: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_table' function.
class CreateTableResponseTypeDef(BaseValidatorModel):
    resourceArn: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_type' function.
class CreateTypeResponseTypeDef(BaseValidatorModel):
    keyspaceArn: str
    typeName: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_type' function.
class DeleteTypeResponseTypeDef(BaseValidatorModel):
    keyspaceArn: str
    typeName: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_tags_for_resource' function.
class ListTagsForResourceResponseTypeDef(BaseValidatorModel):
    tags: List[TagTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_types' function.
class ListTypesResponseTypeDef(BaseValidatorModel):
    types: List[str]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'restore_table' function.
class RestoreTableResponseTypeDef(BaseValidatorModel):
    restoredTableARN: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_keyspace' function.
class UpdateKeyspaceResponseTypeDef(BaseValidatorModel):
    resourceArn: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_table' function.
class UpdateTableResponseTypeDef(BaseValidatorModel):
    resourceArn: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'create_type' function.
class CreateTypeRequestTypeDef(BaseValidatorModel):
    keyspaceName: str
    typeName: str
    fieldDefinitions: List[FieldDefinitionTypeDef]


# This class is the output for the 'get_type' function.
class GetTypeResponseTypeDef(BaseValidatorModel):
    keyspaceName: str
    typeName: str
    fieldDefinitions: List[FieldDefinitionTypeDef]
    lastModifiedTimestamp: datetime
    status: TypeStatusType
    directReferringTables: List[str]
    directParentTypes: List[str]
    maxNestingDepth: int
    keyspaceArn: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_keyspace' function.
class GetKeyspaceResponseTypeDef(BaseValidatorModel):
    keyspaceName: str
    resourceArn: str
    replicationStrategy: RsType
    replicationRegions: List[str]
    replicationGroupStatuses: List[ReplicationGroupStatusTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class ReplicaSpecificationSummaryTypeDef(BaseValidatorModel):
    region: Optional[str] = None
    status: Optional[TableStatusType] = None
    capacitySpecification: Optional[CapacitySpecificationSummaryTypeDef] = None
    warmThroughputSpecification: Optional[WarmThroughputSpecificationSummaryTypeDef] = None


# This class is the output for the 'list_keyspaces' function.
class ListKeyspacesResponseTypeDef(BaseValidatorModel):
    keyspaces: List[KeyspaceSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class ListKeyspacesRequestPaginateTypeDef(BaseValidatorModel):
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListTablesRequestPaginateTypeDef(BaseValidatorModel):
    keyspaceName: str
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListTagsForResourceRequestPaginateTypeDef(BaseValidatorModel):
    resourceArn: str
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListTypesRequestPaginateTypeDef(BaseValidatorModel):
    keyspaceName: str
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the output for the 'list_tables' function.
class ListTablesResponseTypeDef(BaseValidatorModel):
    tables: List[TableSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class SchemaDefinitionOutputTypeDef(BaseValidatorModel):
    allColumns: List[ColumnDefinitionTypeDef]
    partitionKeys: List[PartitionKeyTypeDef]
    clusteringKeys: Optional[List[ClusteringKeyTypeDef]] = None
    staticColumns: Optional[List[StaticColumnTypeDef]] = None


class SchemaDefinitionTypeDef(BaseValidatorModel):
    allColumns: List[ColumnDefinitionTypeDef]
    partitionKeys: List[PartitionKeyTypeDef]
    clusteringKeys: Optional[List[ClusteringKeyTypeDef]] = None
    staticColumns: Optional[List[StaticColumnTypeDef]] = None


class AutoScalingSettingsTypeDef(BaseValidatorModel):
    autoScalingDisabled: Optional[bool] = None
    minimumUnits: Optional[int] = None
    maximumUnits: Optional[int] = None
    scalingPolicy: Optional[AutoScalingPolicyTypeDef] = None


# This class is the output for the 'get_table' function.
class GetTableResponseTypeDef(BaseValidatorModel):
    keyspaceName: str
    tableName: str
    resourceArn: str
    creationTimestamp: datetime
    status: TableStatusType
    schemaDefinition: SchemaDefinitionOutputTypeDef
    capacitySpecification: CapacitySpecificationSummaryTypeDef
    encryptionSpecification: EncryptionSpecificationTypeDef
    pointInTimeRecovery: PointInTimeRecoverySummaryTypeDef
    ttl: TimeToLiveTypeDef
    defaultTimeToLive: int
    comment: CommentTypeDef
    clientSideTimestamps: ClientSideTimestampsTypeDef
    replicaSpecifications: List[ReplicaSpecificationSummaryTypeDef]
    latestStreamArn: str
    cdcSpecification: CdcSpecificationSummaryTypeDef
    warmThroughputSpecification: WarmThroughputSpecificationSummaryTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


SchemaDefinitionUnionTypeDef = Union[SchemaDefinitionOutputTypeDef, SchemaDefinitionTypeDef]


class AutoScalingSpecificationTypeDef(BaseValidatorModel):
    writeCapacityAutoScaling: Optional[AutoScalingSettingsTypeDef] = None
    readCapacityAutoScaling: Optional[AutoScalingSettingsTypeDef] = None


class ReplicaSpecificationTypeDef(BaseValidatorModel):
    region: str
    readCapacityUnits: Optional[int] = None
    readCapacityAutoScaling: Optional[AutoScalingSettingsTypeDef] = None


class ReplicaAutoScalingSpecificationTypeDef(BaseValidatorModel):
    region: Optional[str] = None
    autoScalingSpecification: Optional[AutoScalingSpecificationTypeDef] = None


# This class is the input for the 'create_table' function.
class CreateTableRequestTypeDef(BaseValidatorModel):
    keyspaceName: str
    tableName: str
    schemaDefinition: SchemaDefinitionUnionTypeDef
    comment: Optional[CommentTypeDef] = None
    capacitySpecification: Optional[CapacitySpecificationTypeDef] = None
    encryptionSpecification: Optional[EncryptionSpecificationTypeDef] = None
    pointInTimeRecovery: Optional[PointInTimeRecoveryTypeDef] = None
    ttl: Optional[TimeToLiveTypeDef] = None
    defaultTimeToLive: Optional[int] = None
    tags: Optional[List[TagTypeDef]] = None
    clientSideTimestamps: Optional[ClientSideTimestampsTypeDef] = None
    autoScalingSpecification: Optional[AutoScalingSpecificationTypeDef] = None
    replicaSpecifications: Optional[List[ReplicaSpecificationTypeDef]] = None
    cdcSpecification: Optional[CdcSpecificationTypeDef] = None
    warmThroughputSpecification: Optional[WarmThroughputSpecificationTypeDef] = None


# This class is the input for the 'restore_table' function.
class RestoreTableRequestTypeDef(BaseValidatorModel):
    sourceKeyspaceName: str
    sourceTableName: str
    targetKeyspaceName: str
    targetTableName: str
    restoreTimestamp: Optional[TimestampTypeDef] = None
    capacitySpecificationOverride: Optional[CapacitySpecificationTypeDef] = None
    encryptionSpecificationOverride: Optional[EncryptionSpecificationTypeDef] = None
    pointInTimeRecoveryOverride: Optional[PointInTimeRecoveryTypeDef] = None
    tagsOverride: Optional[List[TagTypeDef]] = None
    autoScalingSpecification: Optional[AutoScalingSpecificationTypeDef] = None
    replicaSpecifications: Optional[List[ReplicaSpecificationTypeDef]] = None


# This class is the input for the 'update_table' function.
class UpdateTableRequestTypeDef(BaseValidatorModel):
    keyspaceName: str
    tableName: str
    addColumns: Optional[List[ColumnDefinitionTypeDef]] = None
    capacitySpecification: Optional[CapacitySpecificationTypeDef] = None
    encryptionSpecification: Optional[EncryptionSpecificationTypeDef] = None
    pointInTimeRecovery: Optional[PointInTimeRecoveryTypeDef] = None
    ttl: Optional[TimeToLiveTypeDef] = None
    defaultTimeToLive: Optional[int] = None
    clientSideTimestamps: Optional[ClientSideTimestampsTypeDef] = None
    autoScalingSpecification: Optional[AutoScalingSpecificationTypeDef] = None
    replicaSpecifications: Optional[List[ReplicaSpecificationTypeDef]] = None
    cdcSpecification: Optional[CdcSpecificationTypeDef] = None
    warmThroughputSpecification: Optional[WarmThroughputSpecificationTypeDef] = None


# This class is the output for the 'get_table_auto_scaling_settings' function.
class GetTableAutoScalingSettingsResponseTypeDef(BaseValidatorModel):
    keyspaceName: str
    tableName: str
    resourceArn: str
    autoScalingSpecification: AutoScalingSpecificationTypeDef
    replicaSpecifications: List[ReplicaAutoScalingSpecificationTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
