# This file is auto-generated by aws_resource_validator.generator.pipeline_b.
# Do not edit manually; run `arv-generate pipeline-b` to refresh it.
from datetime import datetime
from decimal import Decimal
from typing import (
    Annotated,
    Any,
    Callable,
    Dict,
    FrozenSet,
    IO,
    List,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    Union,
)

from botocore.client import BaseClient
from botocore.response import StreamingBody
from pydantic import Field

from aws_resource_validator.core.base_validator_model import BaseValidatorModel, EventStream
from aws_resource_validator.core.pattern_validation import aws_field_pattern as _aws_pattern
from aws_resource_validator.pydantic_models.voice_id.voice_id_constants import *  # noqa: F401,F403

# Optional boto3 symbols — imported lazily so services that don't need them
# aren't forced to pull in boto3 at import time.
try:
    from boto3.dynamodb.conditions import ConditionBase  # noqa: F401
except ImportError:  # pragma: no cover
    ConditionBase = Any  # type: ignore[assignment,misc]
try:
    from boto3.s3.transfer import TransferConfig  # noqa: F401
except ImportError:  # pragma: no cover
    TransferConfig = Any  # type: ignore[assignment,misc]


# This class is the input for the 'associate_fraudster' function.
class AssociateFraudsterRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    FraudsterId: Annotated[str, _aws_pattern("VoiceId", "FraudsterId")]
    WatchlistId: Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]


class FraudsterTypeDef(BaseValidatorModel):
    CreatedAt: Optional[datetime] = None
    DomainId: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainId")]] = None
    GeneratedFraudsterId: Optional[Annotated[str, _aws_pattern("VoiceId", "GeneratedFraudsterId")]] = None
    WatchlistIds: Optional[List[Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]]] = None


class ResponseMetadataTypeDef(BaseValidatorModel):
    RequestId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, str]
    RetryAttempts: int
    HostId: Optional[str] = None


class AuthenticationConfigurationTypeDef(BaseValidatorModel):
    AcceptanceThreshold: int


class ServerSideEncryptionConfigurationTypeDef(BaseValidatorModel):
    KmsKeyId: str


class TagTypeDef(BaseValidatorModel):
    Key: Annotated[str, _aws_pattern("VoiceId", "TagKey")]
    Value: Annotated[str, _aws_pattern("VoiceId", "TagValue")]


# This class is the input for the 'create_watchlist' function.
class CreateWatchlistRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    Name: Annotated[str, _aws_pattern("VoiceId", "WatchlistName")]
    ClientToken: Optional[Annotated[str, _aws_pattern("VoiceId", "ClientTokenString")]] = None
    Description: Optional[Annotated[str, _aws_pattern("VoiceId", "WatchlistDescription")]] = None


class WatchlistTypeDef(BaseValidatorModel):
    CreatedAt: Optional[datetime] = None
    DefaultWatchlist: Optional[bool] = None
    Description: Optional[Annotated[str, _aws_pattern("VoiceId", "WatchlistDescription")]] = None
    DomainId: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainId")]] = None
    Name: Optional[Annotated[str, _aws_pattern("VoiceId", "WatchlistName")]] = None
    UpdatedAt: Optional[datetime] = None
    WatchlistId: Optional[Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]] = None


# This class is the input for the 'delete_domain' function.
class DeleteDomainRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]


# This class is the input for the 'delete_fraudster' function.
class DeleteFraudsterRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    FraudsterId: Annotated[str, _aws_pattern("VoiceId", "FraudsterId")]


# This class is the input for the 'delete_speaker' function.
class DeleteSpeakerRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    SpeakerId: Annotated[str, _aws_pattern("VoiceId", "SpeakerId")]


# This class is the input for the 'delete_watchlist' function.
class DeleteWatchlistRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    WatchlistId: Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]


# This class is the input for the 'describe_domain' function.
class DescribeDomainRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]


# This class is the input for the 'describe_fraudster_registration_job' function.
class DescribeFraudsterRegistrationJobRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    JobId: Annotated[str, _aws_pattern("VoiceId", "JobId")]


# This class is the input for the 'describe_fraudster' function.
class DescribeFraudsterRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    FraudsterId: Annotated[str, _aws_pattern("VoiceId", "FraudsterId")]


# This class is the input for the 'describe_speaker_enrollment_job' function.
class DescribeSpeakerEnrollmentJobRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    JobId: Annotated[str, _aws_pattern("VoiceId", "JobId")]


# This class is the input for the 'describe_speaker' function.
class DescribeSpeakerRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    SpeakerId: Annotated[str, _aws_pattern("VoiceId", "SpeakerId")]


class SpeakerTypeDef(BaseValidatorModel):
    CreatedAt: Optional[datetime] = None
    CustomerSpeakerId: Optional[Annotated[str, _aws_pattern("VoiceId", "CustomerSpeakerId")]] = None
    DomainId: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainId")]] = None
    GeneratedSpeakerId: Optional[Annotated[str, _aws_pattern("VoiceId", "GeneratedSpeakerId")]] = None
    LastAccessedAt: Optional[datetime] = None
    Status: Optional[SpeakerStatusType] = None
    UpdatedAt: Optional[datetime] = None


# This class is the input for the 'describe_watchlist' function.
class DescribeWatchlistRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    WatchlistId: Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]


# This class is the input for the 'disassociate_fraudster' function.
class DisassociateFraudsterRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    FraudsterId: Annotated[str, _aws_pattern("VoiceId", "FraudsterId")]
    WatchlistId: Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]


class ServerSideEncryptionUpdateDetailsTypeDef(BaseValidatorModel):
    Message: Optional[str] = None
    OldKmsKeyId: Optional[str] = None
    UpdateStatus: Optional[ServerSideEncryptionUpdateStatusType] = None


class WatchlistDetailsTypeDef(BaseValidatorModel):
    DefaultWatchlistId: Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]


class EnrollmentJobFraudDetectionConfigOutputTypeDef(BaseValidatorModel):
    FraudDetectionAction: Optional[FraudDetectionActionType] = None
    RiskThreshold: Optional[int] = None
    WatchlistIds: Optional[List[str]] = None


class EnrollmentJobFraudDetectionConfigTypeDef(BaseValidatorModel):
    FraudDetectionAction: Optional[FraudDetectionActionType] = None
    RiskThreshold: Optional[int] = None
    WatchlistIds: Optional[List[Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]]] = None


# This class is the input for the 'evaluate_session' function.
class EvaluateSessionRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    SessionNameOrId: Annotated[str, _aws_pattern("VoiceId", "SessionNameOrId")]


class FailureDetailsTypeDef(BaseValidatorModel):
    Message: Optional[str] = None
    StatusCode: Optional[int] = None


class FraudDetectionConfigurationTypeDef(BaseValidatorModel):
    RiskThreshold: Optional[int] = None
    WatchlistId: Optional[Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]] = None


class KnownFraudsterRiskTypeDef(BaseValidatorModel):
    RiskScore: int
    GeneratedFraudsterId: Optional[Annotated[str, _aws_pattern("VoiceId", "GeneratedFraudsterId")]] = None


class VoiceSpoofingRiskTypeDef(BaseValidatorModel):
    RiskScore: int


class JobProgressTypeDef(BaseValidatorModel):
    PercentComplete: Optional[int] = None


class InputDataConfigTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("VoiceId", "S3Uri")]


class OutputDataConfigTypeDef(BaseValidatorModel):
    S3Uri: Annotated[str, _aws_pattern("VoiceId", "S3Uri")]
    KmsKeyId: Optional[str] = None


class RegistrationConfigOutputTypeDef(BaseValidatorModel):
    DuplicateRegistrationAction: Optional[DuplicateRegistrationActionType] = None
    FraudsterSimilarityThreshold: Optional[int] = None
    WatchlistIds: Optional[List[str]] = None


class FraudsterSummaryTypeDef(BaseValidatorModel):
    CreatedAt: Optional[datetime] = None
    DomainId: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainId")]] = None
    GeneratedFraudsterId: Optional[Annotated[str, _aws_pattern("VoiceId", "GeneratedFraudsterId")]] = None
    WatchlistIds: Optional[List[Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]]] = None


class PaginatorConfigTypeDef(BaseValidatorModel):
    MaxItems: Optional[int] = None
    PageSize: Optional[int] = None
    StartingToken: Optional[str] = None


# This class is the input for the 'list_domains' function.
class ListDomainsRequestTypeDef(BaseValidatorModel):
    MaxResults: Optional[int] = None
    NextToken: Optional[Annotated[str, _aws_pattern("VoiceId", "NextToken")]] = None


# This class is the input for the 'list_fraudster_registration_jobs' function.
class ListFraudsterRegistrationJobsRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    JobStatus: Optional[FraudsterRegistrationJobStatusType] = None
    MaxResults: Optional[int] = None
    NextToken: Optional[Annotated[str, _aws_pattern("VoiceId", "NextToken")]] = None


# This class is the input for the 'list_fraudsters' function.
class ListFraudstersRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    MaxResults: Optional[int] = None
    NextToken: Optional[Annotated[str, _aws_pattern("VoiceId", "NextToken")]] = None
    WatchlistId: Optional[Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]] = None


# This class is the input for the 'list_speaker_enrollment_jobs' function.
class ListSpeakerEnrollmentJobsRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    JobStatus: Optional[SpeakerEnrollmentJobStatusType] = None
    MaxResults: Optional[int] = None
    NextToken: Optional[Annotated[str, _aws_pattern("VoiceId", "NextToken")]] = None


# This class is the input for the 'list_speakers' function.
class ListSpeakersRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    MaxResults: Optional[int] = None
    NextToken: Optional[Annotated[str, _aws_pattern("VoiceId", "NextToken")]] = None


class SpeakerSummaryTypeDef(BaseValidatorModel):
    CreatedAt: Optional[datetime] = None
    CustomerSpeakerId: Optional[Annotated[str, _aws_pattern("VoiceId", "CustomerSpeakerId")]] = None
    DomainId: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainId")]] = None
    GeneratedSpeakerId: Optional[Annotated[str, _aws_pattern("VoiceId", "GeneratedSpeakerId")]] = None
    LastAccessedAt: Optional[datetime] = None
    Status: Optional[SpeakerStatusType] = None
    UpdatedAt: Optional[datetime] = None


# This class is the input for the 'list_tags_for_resource' function.
class ListTagsForResourceRequestTypeDef(BaseValidatorModel):
    ResourceArn: Annotated[str, _aws_pattern("VoiceId", "AmazonResourceName")]


# This class is the input for the 'list_watchlists' function.
class ListWatchlistsRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    MaxResults: Optional[int] = None
    NextToken: Optional[Annotated[str, _aws_pattern("VoiceId", "NextToken")]] = None


class WatchlistSummaryTypeDef(BaseValidatorModel):
    CreatedAt: Optional[datetime] = None
    DefaultWatchlist: Optional[bool] = None
    Description: Optional[Annotated[str, _aws_pattern("VoiceId", "WatchlistDescription")]] = None
    DomainId: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainId")]] = None
    Name: Optional[Annotated[str, _aws_pattern("VoiceId", "WatchlistName")]] = None
    UpdatedAt: Optional[datetime] = None
    WatchlistId: Optional[Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]] = None


# This class is the input for the 'opt_out_speaker' function.
class OptOutSpeakerRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    SpeakerId: Annotated[str, _aws_pattern("VoiceId", "SpeakerId")]


class RegistrationConfigTypeDef(BaseValidatorModel):
    DuplicateRegistrationAction: Optional[DuplicateRegistrationActionType] = None
    FraudsterSimilarityThreshold: Optional[int] = None
    WatchlistIds: Optional[List[Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]]] = None


class UntagResourceRequestTypeDef(BaseValidatorModel):
    ResourceArn: Annotated[str, _aws_pattern("VoiceId", "AmazonResourceName")]
    TagKeys: List[Annotated[str, _aws_pattern("VoiceId", "TagKey")]]


# This class is the input for the 'update_watchlist' function.
class UpdateWatchlistRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    WatchlistId: Annotated[str, _aws_pattern("VoiceId", "WatchlistId")]
    Description: Optional[Annotated[str, _aws_pattern("VoiceId", "WatchlistDescription")]] = None
    Name: Optional[Annotated[str, _aws_pattern("VoiceId", "WatchlistName")]] = None


# This class is the output for the 'associate_fraudster' function.
class AssociateFraudsterResponseTypeDef(BaseValidatorModel):
    Fraudster: FraudsterTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_fraudster' function.
class DescribeFraudsterResponseTypeDef(BaseValidatorModel):
    Fraudster: FraudsterTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'disassociate_fraudster' function.
class DisassociateFraudsterResponseTypeDef(BaseValidatorModel):
    Fraudster: FraudsterTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_domain' function.
class EmptyResponseMetadataTypeDef(BaseValidatorModel):
    ResponseMetadata: ResponseMetadataTypeDef


class AuthenticationResultTypeDef(BaseValidatorModel):
    AudioAggregationEndedAt: Optional[datetime] = None
    AudioAggregationStartedAt: Optional[datetime] = None
    AuthenticationResultId: Optional[Annotated[str, _aws_pattern("VoiceId", "UniqueIdLarge")]] = None
    Configuration: Optional[AuthenticationConfigurationTypeDef] = None
    CustomerSpeakerId: Optional[Annotated[str, _aws_pattern("VoiceId", "CustomerSpeakerId")]] = None
    Decision: Optional[AuthenticationDecisionType] = None
    GeneratedSpeakerId: Optional[Annotated[str, _aws_pattern("VoiceId", "GeneratedSpeakerId")]] = None
    Score: Optional[int] = None


# This class is the input for the 'update_domain' function.
class UpdateDomainRequestTypeDef(BaseValidatorModel):
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    Name: Annotated[str, _aws_pattern("VoiceId", "DomainName")]
    ServerSideEncryptionConfiguration: ServerSideEncryptionConfigurationTypeDef
    Description: Optional[Annotated[str, _aws_pattern("VoiceId", "Description")]] = None


# This class is the input for the 'create_domain' function.
class CreateDomainRequestTypeDef(BaseValidatorModel):
    Name: Annotated[str, _aws_pattern("VoiceId", "DomainName")]
    ServerSideEncryptionConfiguration: ServerSideEncryptionConfigurationTypeDef
    ClientToken: Optional[Annotated[str, _aws_pattern("VoiceId", "ClientTokenString")]] = None
    Description: Optional[Annotated[str, _aws_pattern("VoiceId", "Description")]] = None
    Tags: Optional[List[TagTypeDef]] = None


# This class is the output for the 'list_tags_for_resource' function.
class ListTagsForResourceResponseTypeDef(BaseValidatorModel):
    Tags: List[TagTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class TagResourceRequestTypeDef(BaseValidatorModel):
    ResourceArn: Annotated[str, _aws_pattern("VoiceId", "AmazonResourceName")]
    Tags: List[TagTypeDef]


# This class is the output for the 'create_watchlist' function.
class CreateWatchlistResponseTypeDef(BaseValidatorModel):
    Watchlist: WatchlistTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_watchlist' function.
class DescribeWatchlistResponseTypeDef(BaseValidatorModel):
    Watchlist: WatchlistTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_watchlist' function.
class UpdateWatchlistResponseTypeDef(BaseValidatorModel):
    Watchlist: WatchlistTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_speaker' function.
class DescribeSpeakerResponseTypeDef(BaseValidatorModel):
    Speaker: SpeakerTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'opt_out_speaker' function.
class OptOutSpeakerResponseTypeDef(BaseValidatorModel):
    Speaker: SpeakerTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class DomainSummaryTypeDef(BaseValidatorModel):
    Arn: Optional[Annotated[str, _aws_pattern("VoiceId", "Arn")]] = None
    CreatedAt: Optional[datetime] = None
    Description: Optional[Annotated[str, _aws_pattern("VoiceId", "Description")]] = None
    DomainId: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainId")]] = None
    DomainStatus: Optional[DomainStatusType] = None
    Name: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainName")]] = None
    ServerSideEncryptionConfiguration: Optional[ServerSideEncryptionConfigurationTypeDef] = None
    ServerSideEncryptionUpdateDetails: Optional[ServerSideEncryptionUpdateDetailsTypeDef] = None
    UpdatedAt: Optional[datetime] = None
    WatchlistDetails: Optional[WatchlistDetailsTypeDef] = None


class DomainTypeDef(BaseValidatorModel):
    Arn: Optional[Annotated[str, _aws_pattern("VoiceId", "Arn")]] = None
    CreatedAt: Optional[datetime] = None
    Description: Optional[Annotated[str, _aws_pattern("VoiceId", "Description")]] = None
    DomainId: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainId")]] = None
    DomainStatus: Optional[DomainStatusType] = None
    Name: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainName")]] = None
    ServerSideEncryptionConfiguration: Optional[ServerSideEncryptionConfigurationTypeDef] = None
    ServerSideEncryptionUpdateDetails: Optional[ServerSideEncryptionUpdateDetailsTypeDef] = None
    UpdatedAt: Optional[datetime] = None
    WatchlistDetails: Optional[WatchlistDetailsTypeDef] = None


class EnrollmentConfigOutputTypeDef(BaseValidatorModel):
    ExistingEnrollmentAction: Optional[ExistingEnrollmentActionType] = None
    FraudDetectionConfig: Optional[EnrollmentJobFraudDetectionConfigOutputTypeDef] = None


class EnrollmentConfigTypeDef(BaseValidatorModel):
    ExistingEnrollmentAction: Optional[ExistingEnrollmentActionType] = None
    FraudDetectionConfig: Optional[EnrollmentJobFraudDetectionConfigTypeDef] = None


class FraudRiskDetailsTypeDef(BaseValidatorModel):
    KnownFraudsterRisk: KnownFraudsterRiskTypeDef
    VoiceSpoofingRisk: VoiceSpoofingRiskTypeDef


class FraudsterRegistrationJobSummaryTypeDef(BaseValidatorModel):
    CreatedAt: Optional[datetime] = None
    DomainId: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainId")]] = None
    EndedAt: Optional[datetime] = None
    FailureDetails: Optional[FailureDetailsTypeDef] = None
    JobId: Optional[Annotated[str, _aws_pattern("VoiceId", "JobId")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("VoiceId", "JobName")]] = None
    JobProgress: Optional[JobProgressTypeDef] = None
    JobStatus: Optional[FraudsterRegistrationJobStatusType] = None


class SpeakerEnrollmentJobSummaryTypeDef(BaseValidatorModel):
    CreatedAt: Optional[datetime] = None
    DomainId: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainId")]] = None
    EndedAt: Optional[datetime] = None
    FailureDetails: Optional[FailureDetailsTypeDef] = None
    JobId: Optional[Annotated[str, _aws_pattern("VoiceId", "JobId")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("VoiceId", "JobName")]] = None
    JobProgress: Optional[JobProgressTypeDef] = None
    JobStatus: Optional[SpeakerEnrollmentJobStatusType] = None


class FraudsterRegistrationJobTypeDef(BaseValidatorModel):
    CreatedAt: Optional[datetime] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("VoiceId", "IamRoleArn")]] = None
    DomainId: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainId")]] = None
    EndedAt: Optional[datetime] = None
    FailureDetails: Optional[FailureDetailsTypeDef] = None
    InputDataConfig: Optional[InputDataConfigTypeDef] = None
    JobId: Optional[Annotated[str, _aws_pattern("VoiceId", "JobId")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("VoiceId", "JobName")]] = None
    JobProgress: Optional[JobProgressTypeDef] = None
    JobStatus: Optional[FraudsterRegistrationJobStatusType] = None
    OutputDataConfig: Optional[OutputDataConfigTypeDef] = None
    RegistrationConfig: Optional[RegistrationConfigOutputTypeDef] = None


# This class is the output for the 'list_fraudsters' function.
class ListFraudstersResponseTypeDef(BaseValidatorModel):
    FraudsterSummaries: List[FraudsterSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


class ListDomainsRequestPaginateTypeDef(BaseValidatorModel):
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListFraudsterRegistrationJobsRequestPaginateTypeDef(BaseValidatorModel):
    DomainId: str
    JobStatus: Optional[FraudsterRegistrationJobStatusType] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListFraudstersRequestPaginateTypeDef(BaseValidatorModel):
    DomainId: str
    WatchlistId: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListSpeakerEnrollmentJobsRequestPaginateTypeDef(BaseValidatorModel):
    DomainId: str
    JobStatus: Optional[SpeakerEnrollmentJobStatusType] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListSpeakersRequestPaginateTypeDef(BaseValidatorModel):
    DomainId: str
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListWatchlistsRequestPaginateTypeDef(BaseValidatorModel):
    DomainId: str
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the output for the 'list_speakers' function.
class ListSpeakersResponseTypeDef(BaseValidatorModel):
    SpeakerSummaries: List[SpeakerSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'list_watchlists' function.
class ListWatchlistsResponseTypeDef(BaseValidatorModel):
    WatchlistSummaries: List[WatchlistSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


RegistrationConfigUnionTypeDef = Union[RegistrationConfigOutputTypeDef, RegistrationConfigTypeDef]


# This class is the output for the 'list_domains' function.
class ListDomainsResponseTypeDef(BaseValidatorModel):
    DomainSummaries: List[DomainSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'create_domain' function.
class CreateDomainResponseTypeDef(BaseValidatorModel):
    Domain: DomainTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_domain' function.
class DescribeDomainResponseTypeDef(BaseValidatorModel):
    Domain: DomainTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_domain' function.
class UpdateDomainResponseTypeDef(BaseValidatorModel):
    Domain: DomainTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class SpeakerEnrollmentJobTypeDef(BaseValidatorModel):
    CreatedAt: Optional[datetime] = None
    DataAccessRoleArn: Optional[Annotated[str, _aws_pattern("VoiceId", "IamRoleArn")]] = None
    DomainId: Optional[Annotated[str, _aws_pattern("VoiceId", "DomainId")]] = None
    EndedAt: Optional[datetime] = None
    EnrollmentConfig: Optional[EnrollmentConfigOutputTypeDef] = None
    FailureDetails: Optional[FailureDetailsTypeDef] = None
    InputDataConfig: Optional[InputDataConfigTypeDef] = None
    JobId: Optional[Annotated[str, _aws_pattern("VoiceId", "JobId")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("VoiceId", "JobName")]] = None
    JobProgress: Optional[JobProgressTypeDef] = None
    JobStatus: Optional[SpeakerEnrollmentJobStatusType] = None
    OutputDataConfig: Optional[OutputDataConfigTypeDef] = None


EnrollmentConfigUnionTypeDef = Union[EnrollmentConfigOutputTypeDef, EnrollmentConfigTypeDef]


class FraudDetectionResultTypeDef(BaseValidatorModel):
    AudioAggregationEndedAt: Optional[datetime] = None
    AudioAggregationStartedAt: Optional[datetime] = None
    Configuration: Optional[FraudDetectionConfigurationTypeDef] = None
    Decision: Optional[FraudDetectionDecisionType] = None
    FraudDetectionResultId: Optional[Annotated[str, _aws_pattern("VoiceId", "UniqueIdLarge")]] = None
    Reasons: Optional[List[FraudDetectionReasonType]] = None
    RiskDetails: Optional[FraudRiskDetailsTypeDef] = None


# This class is the output for the 'list_fraudster_registration_jobs' function.
class ListFraudsterRegistrationJobsResponseTypeDef(BaseValidatorModel):
    JobSummaries: List[FraudsterRegistrationJobSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'list_speaker_enrollment_jobs' function.
class ListSpeakerEnrollmentJobsResponseTypeDef(BaseValidatorModel):
    JobSummaries: List[SpeakerEnrollmentJobSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'describe_fraudster_registration_job' function.
class DescribeFraudsterRegistrationJobResponseTypeDef(BaseValidatorModel):
    Job: FraudsterRegistrationJobTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'start_fraudster_registration_job' function.
class StartFraudsterRegistrationJobResponseTypeDef(BaseValidatorModel):
    Job: FraudsterRegistrationJobTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'start_fraudster_registration_job' function.
class StartFraudsterRegistrationJobRequestTypeDef(BaseValidatorModel):
    DataAccessRoleArn: Annotated[str, _aws_pattern("VoiceId", "IamRoleArn")]
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    InputDataConfig: InputDataConfigTypeDef
    OutputDataConfig: OutputDataConfigTypeDef
    ClientToken: Optional[Annotated[str, _aws_pattern("VoiceId", "ClientTokenString")]] = None
    JobName: Optional[Annotated[str, _aws_pattern("VoiceId", "JobName")]] = None
    RegistrationConfig: Optional[RegistrationConfigUnionTypeDef] = None


# This class is the output for the 'describe_speaker_enrollment_job' function.
class DescribeSpeakerEnrollmentJobResponseTypeDef(BaseValidatorModel):
    Job: SpeakerEnrollmentJobTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'start_speaker_enrollment_job' function.
class StartSpeakerEnrollmentJobResponseTypeDef(BaseValidatorModel):
    Job: SpeakerEnrollmentJobTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'start_speaker_enrollment_job' function.
class StartSpeakerEnrollmentJobRequestTypeDef(BaseValidatorModel):
    DataAccessRoleArn: Annotated[str, _aws_pattern("VoiceId", "IamRoleArn")]
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    InputDataConfig: InputDataConfigTypeDef
    OutputDataConfig: OutputDataConfigTypeDef
    ClientToken: Optional[Annotated[str, _aws_pattern("VoiceId", "ClientTokenString")]] = None
    EnrollmentConfig: Optional[EnrollmentConfigUnionTypeDef] = None
    JobName: Optional[Annotated[str, _aws_pattern("VoiceId", "JobName")]] = None


# This class is the output for the 'evaluate_session' function.
class EvaluateSessionResponseTypeDef(BaseValidatorModel):
    AuthenticationResult: AuthenticationResultTypeDef
    DomainId: Annotated[str, _aws_pattern("VoiceId", "DomainId")]
    FraudDetectionResult: FraudDetectionResultTypeDef
    SessionId: Annotated[str, _aws_pattern("VoiceId", "SessionId")]
    SessionName: Annotated[str, _aws_pattern("VoiceId", "SessionName")]
    StreamingStatus: StreamingStatusType
    ResponseMetadata: ResponseMetadataTypeDef
