# This file is auto-generated by aws_resource_validator.generator.pipeline_b.
# Do not edit manually; run `arv-generate pipeline-b` to refresh it.
from datetime import datetime
from decimal import Decimal
from typing import (
    Annotated,
    Any,
    Callable,
    Dict,
    FrozenSet,
    IO,
    List,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    Union,
)

from botocore.client import BaseClient
from botocore.response import StreamingBody
from pydantic import Field

from aws_resource_validator.core.base_validator_model import BaseValidatorModel, EventStream
from aws_resource_validator.core.pattern_validation import aws_field_pattern as _aws_pattern
from aws_resource_validator.pydantic_models.cloudsearch.cloudsearch_constants import *  # noqa: F401,F403

# Optional boto3 symbols — imported lazily so services that don't need them
# aren't forced to pull in boto3 at import time.
try:
    from boto3.dynamodb.conditions import ConditionBase  # noqa: F401
except ImportError:  # pragma: no cover
    ConditionBase = Any  # type: ignore[assignment,misc]
try:
    from boto3.s3.transfer import TransferConfig  # noqa: F401
except ImportError:  # pragma: no cover
    TransferConfig = Any  # type: ignore[assignment,misc]


class OptionStatusTypeDef(BaseValidatorModel):
    CreationDate: datetime
    UpdateDate: datetime
    State: OptionStateType
    UpdateVersion: Optional[int] = None
    PendingDeletion: Optional[bool] = None


class AnalysisOptionsTypeDef(BaseValidatorModel):
    Synonyms: Optional[str] = None
    Stopwords: Optional[str] = None
    StemmingDictionary: Optional[str] = None
    JapaneseTokenizationDictionary: Optional[str] = None
    AlgorithmicStemming: Optional[AlgorithmicStemmingType] = None


# This class is the input for the 'build_suggesters' function.
class BuildSuggestersRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]


class ResponseMetadataTypeDef(BaseValidatorModel):
    RequestId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, str]
    RetryAttempts: int
    HostId: Optional[str] = None


# This class is the input for the 'create_domain' function.
class CreateDomainRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]


class DateArrayOptionsTypeDef(BaseValidatorModel):
    DefaultValue: Optional[str] = None
    SourceFields: Optional[Annotated[str, _aws_pattern("Cloudsearch", "FieldNameCommaList")]] = None
    FacetEnabled: Optional[bool] = None
    SearchEnabled: Optional[bool] = None
    ReturnEnabled: Optional[bool] = None


class DateOptionsTypeDef(BaseValidatorModel):
    DefaultValue: Optional[str] = None
    SourceField: Optional[Annotated[str, _aws_pattern("Cloudsearch", "FieldName")]] = None
    FacetEnabled: Optional[bool] = None
    SearchEnabled: Optional[bool] = None
    ReturnEnabled: Optional[bool] = None
    SortEnabled: Optional[bool] = None


class ExpressionTypeDef(BaseValidatorModel):
    ExpressionName: Annotated[str, _aws_pattern("Cloudsearch", "StandardName")]
    ExpressionValue: str


# This class is the input for the 'delete_analysis_scheme' function.
class DeleteAnalysisSchemeRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    AnalysisSchemeName: Annotated[str, _aws_pattern("Cloudsearch", "StandardName")]


# This class is the input for the 'delete_domain' function.
class DeleteDomainRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]


# This class is the input for the 'delete_expression' function.
class DeleteExpressionRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    ExpressionName: Annotated[str, _aws_pattern("Cloudsearch", "StandardName")]


# This class is the input for the 'delete_index_field' function.
class DeleteIndexFieldRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    IndexFieldName: Annotated[str, _aws_pattern("Cloudsearch", "DynamicFieldName")]


# This class is the input for the 'delete_suggester' function.
class DeleteSuggesterRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    SuggesterName: Annotated[str, _aws_pattern("Cloudsearch", "StandardName")]


# This class is the input for the 'describe_analysis_schemes' function.
class DescribeAnalysisSchemesRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    AnalysisSchemeNames: Optional[List[Annotated[str, _aws_pattern("Cloudsearch", "StandardName")]]] = None
    Deployed: Optional[bool] = None


# This class is the input for the 'describe_availability_options' function.
class DescribeAvailabilityOptionsRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    Deployed: Optional[bool] = None


# This class is the input for the 'describe_domain_endpoint_options' function.
class DescribeDomainEndpointOptionsRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    Deployed: Optional[bool] = None


# This class is the input for the 'describe_domains' function.
class DescribeDomainsRequestTypeDef(BaseValidatorModel):
    DomainNames: Optional[List[Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]]] = None


# This class is the input for the 'describe_expressions' function.
class DescribeExpressionsRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    ExpressionNames: Optional[List[Annotated[str, _aws_pattern("Cloudsearch", "StandardName")]]] = None
    Deployed: Optional[bool] = None


# This class is the input for the 'describe_index_fields' function.
class DescribeIndexFieldsRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    FieldNames: Optional[List[Annotated[str, _aws_pattern("Cloudsearch", "DynamicFieldName")]]] = None
    Deployed: Optional[bool] = None


# This class is the input for the 'describe_scaling_parameters' function.
class DescribeScalingParametersRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]


# This class is the input for the 'describe_service_access_policies' function.
class DescribeServiceAccessPoliciesRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    Deployed: Optional[bool] = None


# This class is the input for the 'describe_suggesters' function.
class DescribeSuggestersRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    SuggesterNames: Optional[List[Annotated[str, _aws_pattern("Cloudsearch", "StandardName")]]] = None
    Deployed: Optional[bool] = None


class DocumentSuggesterOptionsTypeDef(BaseValidatorModel):
    SourceField: Annotated[str, _aws_pattern("Cloudsearch", "FieldName")]
    FuzzyMatching: Optional[SuggesterFuzzyMatchingType] = None
    SortExpression: Optional[str] = None


class DomainEndpointOptionsTypeDef(BaseValidatorModel):
    EnforceHTTPS: Optional[bool] = None
    TLSSecurityPolicy: Optional[TLSSecurityPolicyType] = None


class LimitsTypeDef(BaseValidatorModel):
    MaximumReplicationCount: int
    MaximumPartitionCount: int


class ServiceEndpointTypeDef(BaseValidatorModel):
    Endpoint: Optional[str] = None


class DoubleArrayOptionsTypeDef(BaseValidatorModel):
    DefaultValue: Optional[float] = None
    SourceFields: Optional[Annotated[str, _aws_pattern("Cloudsearch", "FieldNameCommaList")]] = None
    FacetEnabled: Optional[bool] = None
    SearchEnabled: Optional[bool] = None
    ReturnEnabled: Optional[bool] = None


class DoubleOptionsTypeDef(BaseValidatorModel):
    DefaultValue: Optional[float] = None
    SourceField: Optional[Annotated[str, _aws_pattern("Cloudsearch", "FieldName")]] = None
    FacetEnabled: Optional[bool] = None
    SearchEnabled: Optional[bool] = None
    ReturnEnabled: Optional[bool] = None
    SortEnabled: Optional[bool] = None


# This class is the input for the 'index_documents' function.
class IndexDocumentsRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]


class IntArrayOptionsTypeDef(BaseValidatorModel):
    DefaultValue: Optional[int] = None
    SourceFields: Optional[Annotated[str, _aws_pattern("Cloudsearch", "FieldNameCommaList")]] = None
    FacetEnabled: Optional[bool] = None
    SearchEnabled: Optional[bool] = None
    ReturnEnabled: Optional[bool] = None


class IntOptionsTypeDef(BaseValidatorModel):
    DefaultValue: Optional[int] = None
    SourceField: Optional[Annotated[str, _aws_pattern("Cloudsearch", "FieldName")]] = None
    FacetEnabled: Optional[bool] = None
    SearchEnabled: Optional[bool] = None
    ReturnEnabled: Optional[bool] = None
    SortEnabled: Optional[bool] = None


class LatLonOptionsTypeDef(BaseValidatorModel):
    DefaultValue: Optional[str] = None
    SourceField: Optional[Annotated[str, _aws_pattern("Cloudsearch", "FieldName")]] = None
    FacetEnabled: Optional[bool] = None
    SearchEnabled: Optional[bool] = None
    ReturnEnabled: Optional[bool] = None
    SortEnabled: Optional[bool] = None


class LiteralArrayOptionsTypeDef(BaseValidatorModel):
    DefaultValue: Optional[str] = None
    SourceFields: Optional[Annotated[str, _aws_pattern("Cloudsearch", "FieldNameCommaList")]] = None
    FacetEnabled: Optional[bool] = None
    SearchEnabled: Optional[bool] = None
    ReturnEnabled: Optional[bool] = None


class LiteralOptionsTypeDef(BaseValidatorModel):
    DefaultValue: Optional[str] = None
    SourceField: Optional[Annotated[str, _aws_pattern("Cloudsearch", "FieldName")]] = None
    FacetEnabled: Optional[bool] = None
    SearchEnabled: Optional[bool] = None
    ReturnEnabled: Optional[bool] = None
    SortEnabled: Optional[bool] = None


class TextArrayOptionsTypeDef(BaseValidatorModel):
    DefaultValue: Optional[str] = None
    SourceFields: Optional[Annotated[str, _aws_pattern("Cloudsearch", "FieldNameCommaList")]] = None
    ReturnEnabled: Optional[bool] = None
    HighlightEnabled: Optional[bool] = None
    AnalysisScheme: Optional[Annotated[str, _aws_pattern("Cloudsearch", "Word")]] = None


class TextOptionsTypeDef(BaseValidatorModel):
    DefaultValue: Optional[str] = None
    SourceField: Optional[Annotated[str, _aws_pattern("Cloudsearch", "FieldName")]] = None
    ReturnEnabled: Optional[bool] = None
    SortEnabled: Optional[bool] = None
    HighlightEnabled: Optional[bool] = None
    AnalysisScheme: Optional[Annotated[str, _aws_pattern("Cloudsearch", "Word")]] = None


class ScalingParametersTypeDef(BaseValidatorModel):
    DesiredInstanceType: Optional[PartitionInstanceTypeType] = None
    DesiredReplicationCount: Optional[int] = None
    DesiredPartitionCount: Optional[int] = None


# This class is the input for the 'update_availability_options' function.
class UpdateAvailabilityOptionsRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    MultiAZ: bool


# This class is the input for the 'update_service_access_policies' function.
class UpdateServiceAccessPoliciesRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    AccessPolicies: str


class AccessPoliciesStatusTypeDef(BaseValidatorModel):
    Options: str
    Status: OptionStatusTypeDef


class AvailabilityOptionsStatusTypeDef(BaseValidatorModel):
    Options: bool
    Status: OptionStatusTypeDef


class AnalysisSchemeTypeDef(BaseValidatorModel):
    AnalysisSchemeName: Annotated[str, _aws_pattern("Cloudsearch", "StandardName")]
    AnalysisSchemeLanguage: AnalysisSchemeLanguageType
    AnalysisOptions: Optional[AnalysisOptionsTypeDef] = None


# This class is the output for the 'build_suggesters' function.
class BuildSuggestersResponseTypeDef(BaseValidatorModel):
    FieldNames: List[Annotated[str, _aws_pattern("Cloudsearch", "FieldName")]]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'index_documents' function.
class IndexDocumentsResponseTypeDef(BaseValidatorModel):
    FieldNames: List[Annotated[str, _aws_pattern("Cloudsearch", "FieldName")]]
    ResponseMetadata: ResponseMetadataTypeDef


class ListDomainNamesResponseTypeDef(BaseValidatorModel):
    DomainNames: Dict[str, str]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'define_expression' function.
class DefineExpressionRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    Expression: ExpressionTypeDef


class ExpressionStatusTypeDef(BaseValidatorModel):
    Options: ExpressionTypeDef
    Status: OptionStatusTypeDef


class SuggesterTypeDef(BaseValidatorModel):
    SuggesterName: Annotated[str, _aws_pattern("Cloudsearch", "StandardName")]
    DocumentSuggesterOptions: DocumentSuggesterOptionsTypeDef


class DomainEndpointOptionsStatusTypeDef(BaseValidatorModel):
    Options: DomainEndpointOptionsTypeDef
    Status: OptionStatusTypeDef


# This class is the input for the 'update_domain_endpoint_options' function.
class UpdateDomainEndpointOptionsRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    DomainEndpointOptions: DomainEndpointOptionsTypeDef


class DomainStatusTypeDef(BaseValidatorModel):
    DomainId: str
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    RequiresIndexDocuments: bool
    ARN: Optional[str] = None
    Created: Optional[bool] = None
    Deleted: Optional[bool] = None
    DocService: Optional[ServiceEndpointTypeDef] = None
    SearchService: Optional[ServiceEndpointTypeDef] = None
    Processing: Optional[bool] = None
    SearchInstanceType: Optional[str] = None
    SearchPartitionCount: Optional[int] = None
    SearchInstanceCount: Optional[int] = None
    Limits: Optional[LimitsTypeDef] = None


class IndexFieldTypeDef(BaseValidatorModel):
    IndexFieldName: Annotated[str, _aws_pattern("Cloudsearch", "DynamicFieldName")]
    IndexFieldType: IndexFieldTypeType
    IntOptions: Optional[IntOptionsTypeDef] = None
    DoubleOptions: Optional[DoubleOptionsTypeDef] = None
    LiteralOptions: Optional[LiteralOptionsTypeDef] = None
    TextOptions: Optional[TextOptionsTypeDef] = None
    DateOptions: Optional[DateOptionsTypeDef] = None
    LatLonOptions: Optional[LatLonOptionsTypeDef] = None
    IntArrayOptions: Optional[IntArrayOptionsTypeDef] = None
    DoubleArrayOptions: Optional[DoubleArrayOptionsTypeDef] = None
    LiteralArrayOptions: Optional[LiteralArrayOptionsTypeDef] = None
    TextArrayOptions: Optional[TextArrayOptionsTypeDef] = None
    DateArrayOptions: Optional[DateArrayOptionsTypeDef] = None


class ScalingParametersStatusTypeDef(BaseValidatorModel):
    Options: ScalingParametersTypeDef
    Status: OptionStatusTypeDef


# This class is the input for the 'update_scaling_parameters' function.
class UpdateScalingParametersRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    ScalingParameters: ScalingParametersTypeDef


# This class is the output for the 'describe_service_access_policies' function.
class DescribeServiceAccessPoliciesResponseTypeDef(BaseValidatorModel):
    AccessPolicies: AccessPoliciesStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_service_access_policies' function.
class UpdateServiceAccessPoliciesResponseTypeDef(BaseValidatorModel):
    AccessPolicies: AccessPoliciesStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_availability_options' function.
class DescribeAvailabilityOptionsResponseTypeDef(BaseValidatorModel):
    AvailabilityOptions: AvailabilityOptionsStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_availability_options' function.
class UpdateAvailabilityOptionsResponseTypeDef(BaseValidatorModel):
    AvailabilityOptions: AvailabilityOptionsStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class AnalysisSchemeStatusTypeDef(BaseValidatorModel):
    Options: AnalysisSchemeTypeDef
    Status: OptionStatusTypeDef


# This class is the input for the 'define_analysis_scheme' function.
class DefineAnalysisSchemeRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    AnalysisScheme: AnalysisSchemeTypeDef


# This class is the output for the 'define_expression' function.
class DefineExpressionResponseTypeDef(BaseValidatorModel):
    Expression: ExpressionStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_expression' function.
class DeleteExpressionResponseTypeDef(BaseValidatorModel):
    Expression: ExpressionStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_expressions' function.
class DescribeExpressionsResponseTypeDef(BaseValidatorModel):
    Expressions: List[ExpressionStatusTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'define_suggester' function.
class DefineSuggesterRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    Suggester: SuggesterTypeDef


class SuggesterStatusTypeDef(BaseValidatorModel):
    Options: SuggesterTypeDef
    Status: OptionStatusTypeDef


# This class is the output for the 'describe_domain_endpoint_options' function.
class DescribeDomainEndpointOptionsResponseTypeDef(BaseValidatorModel):
    DomainEndpointOptions: DomainEndpointOptionsStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_domain_endpoint_options' function.
class UpdateDomainEndpointOptionsResponseTypeDef(BaseValidatorModel):
    DomainEndpointOptions: DomainEndpointOptionsStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_domain' function.
class CreateDomainResponseTypeDef(BaseValidatorModel):
    DomainStatus: DomainStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_domain' function.
class DeleteDomainResponseTypeDef(BaseValidatorModel):
    DomainStatus: DomainStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_domains' function.
class DescribeDomainsResponseTypeDef(BaseValidatorModel):
    DomainStatusList: List[DomainStatusTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'define_index_field' function.
class DefineIndexFieldRequestTypeDef(BaseValidatorModel):
    DomainName: Annotated[str, _aws_pattern("Cloudsearch", "DomainName")]
    IndexField: IndexFieldTypeDef


class IndexFieldStatusTypeDef(BaseValidatorModel):
    Options: IndexFieldTypeDef
    Status: OptionStatusTypeDef


# This class is the output for the 'describe_scaling_parameters' function.
class DescribeScalingParametersResponseTypeDef(BaseValidatorModel):
    ScalingParameters: ScalingParametersStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_scaling_parameters' function.
class UpdateScalingParametersResponseTypeDef(BaseValidatorModel):
    ScalingParameters: ScalingParametersStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'define_analysis_scheme' function.
class DefineAnalysisSchemeResponseTypeDef(BaseValidatorModel):
    AnalysisScheme: AnalysisSchemeStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_analysis_scheme' function.
class DeleteAnalysisSchemeResponseTypeDef(BaseValidatorModel):
    AnalysisScheme: AnalysisSchemeStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_analysis_schemes' function.
class DescribeAnalysisSchemesResponseTypeDef(BaseValidatorModel):
    AnalysisSchemes: List[AnalysisSchemeStatusTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'define_suggester' function.
class DefineSuggesterResponseTypeDef(BaseValidatorModel):
    Suggester: SuggesterStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_suggester' function.
class DeleteSuggesterResponseTypeDef(BaseValidatorModel):
    Suggester: SuggesterStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_suggesters' function.
class DescribeSuggestersResponseTypeDef(BaseValidatorModel):
    Suggesters: List[SuggesterStatusTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'define_index_field' function.
class DefineIndexFieldResponseTypeDef(BaseValidatorModel):
    IndexField: IndexFieldStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_index_field' function.
class DeleteIndexFieldResponseTypeDef(BaseValidatorModel):
    IndexField: IndexFieldStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_index_fields' function.
class DescribeIndexFieldsResponseTypeDef(BaseValidatorModel):
    IndexFields: List[IndexFieldStatusTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
