"""Render :class:`ServiceModelIR` to disk as three files + a manifest."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from aws_resource_validator.generator.common.formatter import format_python
from aws_resource_validator.generator.common.io import ensure_package, write_text_atomic
from aws_resource_validator.generator.common.logging import get_logger
from aws_resource_validator.generator.common.templates import build_environment
from aws_resource_validator.generator.pipeline_b.model_ir import ClassIR, ServiceModelIR, UnionAliasIR

_logger = get_logger(__name__)
_TEMPLATE_DIR = Path(__file__).parent / "templates"
_CLASSES_TEMPLATE = "classes.py.j2"
_CONSTANTS_TEMPLATE = "constants.py.j2"


@dataclass(frozen=True)
class EmittedArtifacts:
    """Paths written for one service. Returned for orchestration + tests."""

    classes_file: Path
    constants_file: Path
    manifest_file: Path
    init_file: Path


def _role_comment(cls: ClassIR) -> str | None:
    if cls.role == "internal" or cls.role_fn is None:
        return None
    return f"# This class is the {cls.role} for the '{cls.role_fn}' function."


def _serialize_items(ir: ServiceModelIR) -> list[dict[str, object]]:
    """Return a flat list of template dicts in the same order as ``ir.items``.

    Preserving source order keeps forward references resolvable at import
    time — the upstream stubs are topologically sorted for this reason.
    Literal aliases are emitted separately in the constants module.
    """
    serialized: list[dict[str, object]] = []
    for item in ir.items:
        if isinstance(item, ClassIR):
            serialized.append(_serialize_class(item))
        elif isinstance(item, UnionAliasIR):
            serialized.append(
                {
                    "kind": "alias",
                    "name": item.name,
                    "expression": item.expression,
                }
            )
    return serialized


def _serialize_class(cls: ClassIR) -> dict[str, object]:
    return {
        "kind": "class",
        "name": cls.name,
        "base": cls.base,
        "role_comment": _role_comment(cls),
        "fields": [
            {
                "py_name": field.py_name,
                "name_literal": repr(field.name),
                "annotation": field.annotation,
                "default_expr": field.default_expr,
                "needs_alias": field.py_name != field.name,
            }
            for field in cls.fields
        ],
    }


def render_classes(ir: ServiceModelIR) -> str:
    template = build_environment(_TEMPLATE_DIR).get_template(_CLASSES_TEMPLATE)
    rendered = template.render(service=ir.service, items=_serialize_items(ir))
    return format_python(rendered)


def render_constants(ir: ServiceModelIR) -> str:
    template = build_environment(_TEMPLATE_DIR).get_template(_CONSTANTS_TEMPLATE)
    rendered = template.render(literals=ir.literals)
    return format_python(rendered)


def build_manifest(ir: ServiceModelIR, module: str) -> dict[str, object]:
    return {
        "service": ir.service,
        "module": module,
        "classes": [cls.name for cls in ir.classes],
        "union_aliases": [alias.name for alias in ir.union_aliases],
    }


def build_init_content(ir: ServiceModelIR) -> str:
    """Re-export the generated names from ``<service>/__init__.py``."""
    module = f"{ir.service}_classes"
    lines = [
        "# This file is auto-generated by aws_resource_validator.generator.pipeline_b.",
        "from __future__ import annotations",
        "",
    ]
    names = sorted({cls.name for cls in ir.classes} | {alias.name for alias in ir.union_aliases})
    if names:
        joined = ",\n    ".join(names)
        lines.append(f"from aws_resource_validator.pydantic_models.{ir.service}.{module} import (\n    {joined},\n)")
        lines.append("")
        quoted = ",\n    ".join(repr(n) for n in names)
        lines.append(f"__all__ = [\n    {quoted},\n]")
    return "\n".join(lines) + "\n"


def emit_service(ir: ServiceModelIR, out_dir: Path) -> EmittedArtifacts:
    """Write ``<service>_classes.py``, ``<service>_constants.py``, ``__init__.py``, and ``_manifest.json``."""
    service_dir = out_dir / ir.service
    ensure_package(service_dir)

    classes_file = service_dir / f"{ir.service}_classes.py"
    constants_file = service_dir / f"{ir.service}_constants.py"
    manifest_file = service_dir / "_manifest.json"
    init_file = service_dir / "__init__.py"

    write_text_atomic(classes_file, render_classes(ir))
    write_text_atomic(constants_file, render_constants(ir))
    write_text_atomic(init_file, build_init_content(ir))

    module = f"aws_resource_validator.pydantic_models.{ir.service}.{ir.service}_classes"
    write_text_atomic(manifest_file, json.dumps(build_manifest(ir, module), indent=2, sort_keys=True) + "\n")

    _logger.info(
        "Emitted %s (%d classes, %d aliases, %d literals).",
        ir.service,
        len(ir.classes),
        len(ir.union_aliases),
        len(ir.literals),
    )
    return EmittedArtifacts(
        classes_file=classes_file,
        constants_file=constants_file,
        manifest_file=manifest_file,
        init_file=init_file,
    )
