# This file is auto-generated by aws_resource_validator.generator.pipeline_b.
# Do not edit manually; run `arv-generate pipeline-b` to refresh it.
from datetime import datetime
from decimal import Decimal
from typing import (
    Annotated,
    Any,
    Callable,
    Dict,
    FrozenSet,
    IO,
    List,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    Union,
)

from botocore.client import BaseClient
from botocore.response import StreamingBody
from pydantic import Field

from aws_resource_validator.core.base_validator_model import BaseValidatorModel, EventStream
from aws_resource_validator.core.pattern_validation import aws_field_pattern as _aws_pattern
from aws_resource_validator.pydantic_models.codestar_connections.codestar_connections_constants import *  # noqa: F401,F403

# Optional boto3 symbols — imported lazily so services that don't need them
# aren't forced to pull in boto3 at import time.
try:
    from boto3.dynamodb.conditions import ConditionBase  # noqa: F401
except ImportError:  # pragma: no cover
    ConditionBase = Any  # type: ignore[assignment,misc]
try:
    from boto3.s3.transfer import TransferConfig  # noqa: F401
except ImportError:  # pragma: no cover
    TransferConfig = Any  # type: ignore[assignment,misc]


class ConnectionTypeDef(BaseValidatorModel):
    ConnectionName: Optional[Annotated[str, _aws_pattern("CodestarConnections", "ConnectionName")]] = None
    ConnectionArn: Optional[Annotated[str, _aws_pattern("CodestarConnections", "ConnectionArn")]] = None
    ProviderType: Optional[ProviderTypeType] = None
    OwnerAccountId: Optional[Annotated[str, _aws_pattern("CodestarConnections", "AccountId")]] = None
    ConnectionStatus: Optional[ConnectionStatusType] = None
    HostArn: Optional[Annotated[str, _aws_pattern("CodestarConnections", "HostArn")]] = None


class TagTypeDef(BaseValidatorModel):
    Key: Annotated[str, _aws_pattern("CodestarConnections", "TagKey")]
    Value: Annotated[str, _aws_pattern("CodestarConnections", "TagValue")]


class ResponseMetadataTypeDef(BaseValidatorModel):
    RequestId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, str]
    RetryAttempts: int
    HostId: Optional[str] = None


class RepositoryLinkInfoTypeDef(BaseValidatorModel):
    ConnectionArn: Annotated[str, _aws_pattern("CodestarConnections", "ConnectionArn")]
    OwnerId: Annotated[str, _aws_pattern("CodestarConnections", "OwnerId")]
    ProviderType: ProviderTypeType
    RepositoryLinkArn: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryLinkArn")]
    RepositoryLinkId: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryLinkId")]
    RepositoryName: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryName")]
    EncryptionKeyArn: Optional[Annotated[str, _aws_pattern("CodestarConnections", "KmsKeyArn")]] = None


# This class is the input for the 'create_sync_configuration' function.
class CreateSyncConfigurationInputTypeDef(BaseValidatorModel):
    Branch: Annotated[str, _aws_pattern("CodestarConnections", "BranchName")]
    ConfigFile: str
    RepositoryLinkId: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryLinkId")]
    ResourceName: Annotated[str, _aws_pattern("CodestarConnections", "ResourceName")]
    RoleArn: Annotated[str, _aws_pattern("CodestarConnections", "IamRoleArn")]
    SyncType: Literal["CFN_STACK_SYNC"]
    PublishDeploymentStatus: Optional[PublishDeploymentStatusType] = None
    TriggerResourceUpdateOn: Optional[TriggerResourceUpdateOnType] = None


class SyncConfigurationTypeDef(BaseValidatorModel):
    Branch: Annotated[str, _aws_pattern("CodestarConnections", "BranchName")]
    OwnerId: Annotated[str, _aws_pattern("CodestarConnections", "OwnerId")]
    ProviderType: ProviderTypeType
    RepositoryLinkId: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryLinkId")]
    RepositoryName: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryName")]
    ResourceName: Annotated[str, _aws_pattern("CodestarConnections", "ResourceName")]
    RoleArn: Annotated[str, _aws_pattern("CodestarConnections", "IamRoleArn")]
    SyncType: Literal["CFN_STACK_SYNC"]
    ConfigFile: Optional[str] = None
    PublishDeploymentStatus: Optional[PublishDeploymentStatusType] = None
    TriggerResourceUpdateOn: Optional[TriggerResourceUpdateOnType] = None


class DeleteConnectionInputTypeDef(BaseValidatorModel):
    ConnectionArn: Annotated[str, _aws_pattern("CodestarConnections", "ConnectionArn")]


class DeleteHostInputTypeDef(BaseValidatorModel):
    HostArn: Annotated[str, _aws_pattern("CodestarConnections", "HostArn")]


class DeleteRepositoryLinkInputTypeDef(BaseValidatorModel):
    RepositoryLinkId: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryLinkId")]


class DeleteSyncConfigurationInputTypeDef(BaseValidatorModel):
    SyncType: Literal["CFN_STACK_SYNC"]
    ResourceName: Annotated[str, _aws_pattern("CodestarConnections", "ResourceName")]


# This class is the input for the 'get_connection' function.
class GetConnectionInputTypeDef(BaseValidatorModel):
    ConnectionArn: Annotated[str, _aws_pattern("CodestarConnections", "ConnectionArn")]


# This class is the input for the 'get_host' function.
class GetHostInputTypeDef(BaseValidatorModel):
    HostArn: Annotated[str, _aws_pattern("CodestarConnections", "HostArn")]


class VpcConfigurationOutputTypeDef(BaseValidatorModel):
    VpcId: str
    SubnetIds: List[str]
    SecurityGroupIds: List[str]
    TlsCertificate: Optional[str] = None


# This class is the input for the 'get_repository_link' function.
class GetRepositoryLinkInputTypeDef(BaseValidatorModel):
    RepositoryLinkId: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryLinkId")]


# This class is the input for the 'get_repository_sync_status' function.
class GetRepositorySyncStatusInputTypeDef(BaseValidatorModel):
    Branch: Annotated[str, _aws_pattern("CodestarConnections", "BranchName")]
    RepositoryLinkId: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryLinkId")]
    SyncType: Literal["CFN_STACK_SYNC"]


# This class is the input for the 'get_resource_sync_status' function.
class GetResourceSyncStatusInputTypeDef(BaseValidatorModel):
    ResourceName: Annotated[str, _aws_pattern("CodestarConnections", "ResourceName")]
    SyncType: Literal["CFN_STACK_SYNC"]


class RevisionTypeDef(BaseValidatorModel):
    Branch: Annotated[str, _aws_pattern("CodestarConnections", "BranchName")]
    Directory: str
    OwnerId: Annotated[str, _aws_pattern("CodestarConnections", "OwnerId")]
    RepositoryName: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryName")]
    ProviderType: ProviderTypeType
    Sha: str


# This class is the input for the 'get_sync_blocker_summary' function.
class GetSyncBlockerSummaryInputTypeDef(BaseValidatorModel):
    SyncType: Literal["CFN_STACK_SYNC"]
    ResourceName: Annotated[str, _aws_pattern("CodestarConnections", "ResourceName")]


# This class is the input for the 'get_sync_configuration' function.
class GetSyncConfigurationInputTypeDef(BaseValidatorModel):
    SyncType: Literal["CFN_STACK_SYNC"]
    ResourceName: Annotated[str, _aws_pattern("CodestarConnections", "ResourceName")]


# This class is the input for the 'list_connections' function.
class ListConnectionsInputTypeDef(BaseValidatorModel):
    ProviderTypeFilter: Optional[ProviderTypeType] = None
    HostArnFilter: Optional[Annotated[str, _aws_pattern("CodestarConnections", "HostArn")]] = None
    MaxResults: Optional[int] = None
    NextToken: Optional[Annotated[str, _aws_pattern("CodestarConnections", "NextToken")]] = None


# This class is the input for the 'list_hosts' function.
class ListHostsInputTypeDef(BaseValidatorModel):
    MaxResults: Optional[int] = None
    NextToken: Optional[Annotated[str, _aws_pattern("CodestarConnections", "NextToken")]] = None


# This class is the input for the 'list_repository_links' function.
class ListRepositoryLinksInputTypeDef(BaseValidatorModel):
    MaxResults: Optional[int] = None
    NextToken: Optional[Annotated[str, _aws_pattern("CodestarConnections", "SharpNextToken")]] = None


# This class is the input for the 'list_repository_sync_definitions' function.
class ListRepositorySyncDefinitionsInputTypeDef(BaseValidatorModel):
    RepositoryLinkId: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryLinkId")]
    SyncType: Literal["CFN_STACK_SYNC"]


class RepositorySyncDefinitionTypeDef(BaseValidatorModel):
    Branch: Annotated[str, _aws_pattern("CodestarConnections", "BranchName")]
    Directory: str
    Parent: str
    Target: str


# This class is the input for the 'list_sync_configurations' function.
class ListSyncConfigurationsInputTypeDef(BaseValidatorModel):
    RepositoryLinkId: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryLinkId")]
    SyncType: Literal["CFN_STACK_SYNC"]
    MaxResults: Optional[int] = None
    NextToken: Optional[Annotated[str, _aws_pattern("CodestarConnections", "SharpNextToken")]] = None


# This class is the input for the 'list_tags_for_resource' function.
class ListTagsForResourceInputTypeDef(BaseValidatorModel):
    ResourceArn: Annotated[str, _aws_pattern("CodestarConnections", "AmazonResourceName")]


class RepositorySyncEventTypeDef(BaseValidatorModel):
    Event: str
    Time: datetime
    Type: str
    ExternalId: Optional[str] = None


class ResourceSyncEventTypeDef(BaseValidatorModel):
    Event: str
    Time: datetime
    Type: str
    ExternalId: Optional[str] = None


class SyncBlockerContextTypeDef(BaseValidatorModel):
    Key: str
    Value: str


class UntagResourceInputTypeDef(BaseValidatorModel):
    ResourceArn: Annotated[str, _aws_pattern("CodestarConnections", "AmazonResourceName")]
    TagKeys: List[Annotated[str, _aws_pattern("CodestarConnections", "TagKey")]]


# This class is the input for the 'update_repository_link' function.
class UpdateRepositoryLinkInputTypeDef(BaseValidatorModel):
    RepositoryLinkId: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryLinkId")]
    ConnectionArn: Optional[Annotated[str, _aws_pattern("CodestarConnections", "ConnectionArn")]] = None
    EncryptionKeyArn: Optional[Annotated[str, _aws_pattern("CodestarConnections", "KmsKeyArn")]] = None


# This class is the input for the 'update_sync_blocker' function.
class UpdateSyncBlockerInputTypeDef(BaseValidatorModel):
    Id: str
    SyncType: Literal["CFN_STACK_SYNC"]
    ResourceName: Annotated[str, _aws_pattern("CodestarConnections", "ResourceName")]
    ResolvedReason: str


# This class is the input for the 'update_sync_configuration' function.
class UpdateSyncConfigurationInputTypeDef(BaseValidatorModel):
    ResourceName: Annotated[str, _aws_pattern("CodestarConnections", "ResourceName")]
    SyncType: Literal["CFN_STACK_SYNC"]
    Branch: Optional[Annotated[str, _aws_pattern("CodestarConnections", "BranchName")]] = None
    ConfigFile: Optional[str] = None
    RepositoryLinkId: Optional[Annotated[str, _aws_pattern("CodestarConnections", "RepositoryLinkId")]] = None
    RoleArn: Optional[Annotated[str, _aws_pattern("CodestarConnections", "IamRoleArn")]] = None
    PublishDeploymentStatus: Optional[PublishDeploymentStatusType] = None
    TriggerResourceUpdateOn: Optional[TriggerResourceUpdateOnType] = None


class VpcConfigurationTypeDef(BaseValidatorModel):
    VpcId: Annotated[str, _aws_pattern("CodestarConnections", "VpcId")]
    SubnetIds: List[Annotated[str, _aws_pattern("CodestarConnections", "SubnetId")]]
    SecurityGroupIds: List[Annotated[str, _aws_pattern("CodestarConnections", "SecurityGroupId")]]
    TlsCertificate: Optional[Annotated[str, _aws_pattern("CodestarConnections", "TlsCertificate")]] = None


# This class is the input for the 'create_connection' function.
class CreateConnectionInputTypeDef(BaseValidatorModel):
    ConnectionName: Annotated[str, _aws_pattern("CodestarConnections", "ConnectionName")]
    ProviderType: Optional[ProviderTypeType] = None
    Tags: Optional[List[TagTypeDef]] = None
    HostArn: Optional[Annotated[str, _aws_pattern("CodestarConnections", "HostArn")]] = None


# This class is the input for the 'create_repository_link' function.
class CreateRepositoryLinkInputTypeDef(BaseValidatorModel):
    ConnectionArn: Annotated[str, _aws_pattern("CodestarConnections", "ConnectionArn")]
    OwnerId: Annotated[str, _aws_pattern("CodestarConnections", "OwnerId")]
    RepositoryName: Annotated[str, _aws_pattern("CodestarConnections", "RepositoryName")]
    EncryptionKeyArn: Optional[Annotated[str, _aws_pattern("CodestarConnections", "KmsKeyArn")]] = None
    Tags: Optional[List[TagTypeDef]] = None


class TagResourceInputTypeDef(BaseValidatorModel):
    ResourceArn: Annotated[str, _aws_pattern("CodestarConnections", "AmazonResourceName")]
    Tags: List[TagTypeDef]


# This class is the output for the 'create_connection' function.
class CreateConnectionOutputTypeDef(BaseValidatorModel):
    ConnectionArn: Annotated[str, _aws_pattern("CodestarConnections", "ConnectionArn")]
    Tags: List[TagTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_host' function.
class CreateHostOutputTypeDef(BaseValidatorModel):
    HostArn: Annotated[str, _aws_pattern("CodestarConnections", "HostArn")]
    Tags: List[TagTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_connection' function.
class GetConnectionOutputTypeDef(BaseValidatorModel):
    Connection: ConnectionTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_connections' function.
class ListConnectionsOutputTypeDef(BaseValidatorModel):
    Connections: List[ConnectionTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[Annotated[str, _aws_pattern("CodestarConnections", "NextToken")]] = None


# This class is the output for the 'list_tags_for_resource' function.
class ListTagsForResourceOutputTypeDef(BaseValidatorModel):
    Tags: List[TagTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_repository_link' function.
class CreateRepositoryLinkOutputTypeDef(BaseValidatorModel):
    RepositoryLinkInfo: RepositoryLinkInfoTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_repository_link' function.
class GetRepositoryLinkOutputTypeDef(BaseValidatorModel):
    RepositoryLinkInfo: RepositoryLinkInfoTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_repository_links' function.
class ListRepositoryLinksOutputTypeDef(BaseValidatorModel):
    RepositoryLinks: List[RepositoryLinkInfoTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[Annotated[str, _aws_pattern("CodestarConnections", "SharpNextToken")]] = None


# This class is the output for the 'update_repository_link' function.
class UpdateRepositoryLinkOutputTypeDef(BaseValidatorModel):
    RepositoryLinkInfo: RepositoryLinkInfoTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_sync_configuration' function.
class CreateSyncConfigurationOutputTypeDef(BaseValidatorModel):
    SyncConfiguration: SyncConfigurationTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_sync_configuration' function.
class GetSyncConfigurationOutputTypeDef(BaseValidatorModel):
    SyncConfiguration: SyncConfigurationTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_sync_configurations' function.
class ListSyncConfigurationsOutputTypeDef(BaseValidatorModel):
    SyncConfigurations: List[SyncConfigurationTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[Annotated[str, _aws_pattern("CodestarConnections", "SharpNextToken")]] = None


# This class is the output for the 'update_sync_configuration' function.
class UpdateSyncConfigurationOutputTypeDef(BaseValidatorModel):
    SyncConfiguration: SyncConfigurationTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_host' function.
class GetHostOutputTypeDef(BaseValidatorModel):
    Name: Annotated[str, _aws_pattern("CodestarConnections", "HostName")]
    Status: Annotated[str, _aws_pattern("CodestarConnections", "HostStatus")]
    ProviderType: ProviderTypeType
    ProviderEndpoint: Annotated[str, _aws_pattern("CodestarConnections", "Url")]
    VpcConfiguration: VpcConfigurationOutputTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class HostTypeDef(BaseValidatorModel):
    Name: Optional[Annotated[str, _aws_pattern("CodestarConnections", "HostName")]] = None
    HostArn: Optional[Annotated[str, _aws_pattern("CodestarConnections", "HostArn")]] = None
    ProviderType: Optional[ProviderTypeType] = None
    ProviderEndpoint: Optional[Annotated[str, _aws_pattern("CodestarConnections", "Url")]] = None
    VpcConfiguration: Optional[VpcConfigurationOutputTypeDef] = None
    Status: Optional[Annotated[str, _aws_pattern("CodestarConnections", "HostStatus")]] = None
    StatusMessage: Optional[str] = None


# This class is the output for the 'list_repository_sync_definitions' function.
class ListRepositorySyncDefinitionsOutputTypeDef(BaseValidatorModel):
    RepositorySyncDefinitions: List[RepositorySyncDefinitionTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[Annotated[str, _aws_pattern("CodestarConnections", "SharpNextToken")]] = None


class RepositorySyncAttemptTypeDef(BaseValidatorModel):
    StartedAt: datetime
    Status: RepositorySyncStatusType
    Events: List[RepositorySyncEventTypeDef]


class ResourceSyncAttemptTypeDef(BaseValidatorModel):
    Events: List[ResourceSyncEventTypeDef]
    InitialRevision: RevisionTypeDef
    StartedAt: datetime
    Status: ResourceSyncStatusType
    TargetRevision: RevisionTypeDef
    Target: str


class SyncBlockerTypeDef(BaseValidatorModel):
    Id: str
    Type: Literal["AUTOMATED"]
    Status: BlockerStatusType
    CreatedReason: str
    CreatedAt: datetime
    Contexts: Optional[List[SyncBlockerContextTypeDef]] = None
    ResolvedReason: Optional[str] = None
    ResolvedAt: Optional[datetime] = None


VpcConfigurationUnionTypeDef = Union[VpcConfigurationOutputTypeDef, VpcConfigurationTypeDef]


# This class is the output for the 'list_hosts' function.
class ListHostsOutputTypeDef(BaseValidatorModel):
    Hosts: List[HostTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[Annotated[str, _aws_pattern("CodestarConnections", "NextToken")]] = None


# This class is the output for the 'get_repository_sync_status' function.
class GetRepositorySyncStatusOutputTypeDef(BaseValidatorModel):
    LatestSync: RepositorySyncAttemptTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'get_resource_sync_status' function.
class GetResourceSyncStatusOutputTypeDef(BaseValidatorModel):
    DesiredState: RevisionTypeDef
    LatestSuccessfulSync: ResourceSyncAttemptTypeDef
    LatestSync: ResourceSyncAttemptTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class SyncBlockerSummaryTypeDef(BaseValidatorModel):
    ResourceName: Annotated[str, _aws_pattern("CodestarConnections", "ResourceName")]
    ParentResourceName: Optional[Annotated[str, _aws_pattern("CodestarConnections", "ResourceName")]] = None
    LatestBlockers: Optional[List[SyncBlockerTypeDef]] = None


# This class is the output for the 'update_sync_blocker' function.
class UpdateSyncBlockerOutputTypeDef(BaseValidatorModel):
    ResourceName: Annotated[str, _aws_pattern("CodestarConnections", "ResourceName")]
    ParentResourceName: Annotated[str, _aws_pattern("CodestarConnections", "ResourceName")]
    SyncBlocker: SyncBlockerTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'create_host' function.
class CreateHostInputTypeDef(BaseValidatorModel):
    Name: Annotated[str, _aws_pattern("CodestarConnections", "HostName")]
    ProviderType: ProviderTypeType
    ProviderEndpoint: Annotated[str, _aws_pattern("CodestarConnections", "Url")]
    VpcConfiguration: Optional[VpcConfigurationUnionTypeDef] = None
    Tags: Optional[List[TagTypeDef]] = None


class UpdateHostInputTypeDef(BaseValidatorModel):
    HostArn: Annotated[str, _aws_pattern("CodestarConnections", "HostArn")]
    ProviderEndpoint: Optional[Annotated[str, _aws_pattern("CodestarConnections", "Url")]] = None
    VpcConfiguration: Optional[VpcConfigurationUnionTypeDef] = None


# This class is the output for the 'get_sync_blocker_summary' function.
class GetSyncBlockerSummaryOutputTypeDef(BaseValidatorModel):
    SyncBlockerSummary: SyncBlockerSummaryTypeDef
    ResponseMetadata: ResponseMetadataTypeDef
