# This file is auto-generated by aws_resource_validator.generator.pipeline_b.
# Do not edit manually; run `arv-generate pipeline-b` to refresh it.
from datetime import datetime
from decimal import Decimal
from typing import (
    Any,
    Callable,
    Dict,
    FrozenSet,
    IO,
    List,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    Union,
)

from botocore.client import BaseClient
from botocore.response import StreamingBody
from pydantic import Field

from aws_resource_validator.core.base_validator_model import BaseValidatorModel, EventStream
from aws_resource_validator.pydantic_models.iotsitewise.iotsitewise_constants import *  # noqa: F401,F403

# Optional boto3 symbols — imported lazily so services that don't need them
# aren't forced to pull in boto3 at import time.
try:
    from boto3.dynamodb.conditions import ConditionBase  # noqa: F401
except ImportError:  # pragma: no cover
    ConditionBase = Any  # type: ignore[assignment,misc]
try:
    from boto3.s3.transfer import TransferConfig  # noqa: F401
except ImportError:  # pragma: no cover
    TransferConfig = Any  # type: ignore[assignment,misc]


class AccessDeniedExceptionTypeDef(BaseValidatorModel):
    message: Optional[str] = None


class ActionDefinitionTypeDef(BaseValidatorModel):
    actionDefinitionId: str
    actionName: str
    actionType: str


class ActionPayloadTypeDef(BaseValidatorModel):
    stringValue: str


class ResolveToTypeDef(BaseValidatorModel):
    assetId: str


class TargetResourceTypeDef(BaseValidatorModel):
    assetId: Optional[str] = None
    computationModelId: Optional[str] = None


class AggregatesTypeDef(BaseValidatorModel):
    average: Optional[float] = None
    count: Optional[float] = None
    maximum: Optional[float] = None
    minimum: Optional[float] = None
    sum: Optional[float] = None
    standardDeviation: Optional[float] = None


class AlarmsTypeDef(BaseValidatorModel):
    alarmRoleArn: str
    notificationLambdaArn: Optional[str] = None


class AssetBindingValueFilterTypeDef(BaseValidatorModel):
    assetId: str


class AssetCompositeModelPathSegmentTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    name: Optional[str] = None


class AssetErrorDetailsTypeDef(BaseValidatorModel):
    assetId: str
    code: Literal["INTERNAL_FAILURE"]
    message: str


class AssetHierarchyInfoTypeDef(BaseValidatorModel):
    parentAssetId: Optional[str] = None
    childAssetId: Optional[str] = None


class AssetHierarchyTypeDef(BaseValidatorModel):
    name: str
    id: Optional[str] = None
    externalId: Optional[str] = None


class AssetModelBindingValueFilterTypeDef(BaseValidatorModel):
    assetModelId: str


class AssetModelCompositeModelPathSegmentTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    name: Optional[str] = None


class AssetModelHierarchyDefinitionTypeDef(BaseValidatorModel):
    name: str
    childAssetModelId: str
    id: Optional[str] = None
    externalId: Optional[str] = None


class AssetModelHierarchyTypeDef(BaseValidatorModel):
    name: str
    childAssetModelId: str
    id: Optional[str] = None
    externalId: Optional[str] = None


class AssetModelPropertyBindingValueFilterTypeDef(BaseValidatorModel):
    assetModelId: str
    propertyId: str


class AssetModelPropertyBindingValueTypeDef(BaseValidatorModel):
    assetModelId: str
    propertyId: str


class AssetModelPropertyPathSegmentTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    name: Optional[str] = None


class InterfaceSummaryTypeDef(BaseValidatorModel):
    interfaceAssetModelId: str
    interfaceAssetModelPropertyId: str


class AssetPropertyBindingValueFilterTypeDef(BaseValidatorModel):
    assetId: str
    propertyId: str


class AssetPropertyBindingValueTypeDef(BaseValidatorModel):
    assetId: str
    propertyId: str


class AssetPropertyPathSegmentTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    name: Optional[str] = None


class PropertyNotificationTypeDef(BaseValidatorModel):
    topic: str
    state: PropertyNotificationStateType


class TimeInNanosTypeDef(BaseValidatorModel):
    timeInSeconds: int
    offsetInNanos: Optional[int] = None


# This class is the input for the 'associate_assets' function.
class AssociateAssetsRequestTypeDef(BaseValidatorModel):
    assetId: str
    hierarchyId: str
    childAssetId: str
    clientToken: Optional[str] = None


# This class is the input for the 'associate_time_series_to_asset_property' function.
class AssociateTimeSeriesToAssetPropertyRequestTypeDef(BaseValidatorModel):
    alias: str
    assetId: str
    propertyId: str
    clientToken: Optional[str] = None


class AttributeTypeDef(BaseValidatorModel):
    defaultValue: Optional[str] = None


# This class is the input for the 'batch_associate_project_assets' function.
class BatchAssociateProjectAssetsRequestTypeDef(BaseValidatorModel):
    projectId: str
    assetIds: List[str]
    clientToken: Optional[str] = None


class ResponseMetadataTypeDef(BaseValidatorModel):
    RequestId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, str]
    RetryAttempts: int
    HostId: Optional[str] = None


# This class is the input for the 'batch_disassociate_project_assets' function.
class BatchDisassociateProjectAssetsRequestTypeDef(BaseValidatorModel):
    projectId: str
    assetIds: List[str]
    clientToken: Optional[str] = None


TimestampTypeDef = Union[datetime, str]


class BatchGetAssetPropertyAggregatesErrorEntryTypeDef(BaseValidatorModel):
    errorCode: BatchGetAssetPropertyAggregatesErrorCodeType
    errorMessage: str
    entryId: str


class BatchGetAssetPropertyAggregatesErrorInfoTypeDef(BaseValidatorModel):
    errorCode: BatchGetAssetPropertyAggregatesErrorCodeType
    errorTimestamp: datetime


class BatchGetAssetPropertyValueEntryTypeDef(BaseValidatorModel):
    entryId: str
    assetId: Optional[str] = None
    propertyId: Optional[str] = None
    propertyAlias: Optional[str] = None


class BatchGetAssetPropertyValueErrorEntryTypeDef(BaseValidatorModel):
    errorCode: BatchGetAssetPropertyValueErrorCodeType
    errorMessage: str
    entryId: str


class BatchGetAssetPropertyValueErrorInfoTypeDef(BaseValidatorModel):
    errorCode: BatchGetAssetPropertyValueErrorCodeType
    errorTimestamp: datetime


class BatchGetAssetPropertyValueHistoryErrorEntryTypeDef(BaseValidatorModel):
    errorCode: BatchGetAssetPropertyValueHistoryErrorCodeType
    errorMessage: str
    entryId: str


class BatchGetAssetPropertyValueHistoryErrorInfoTypeDef(BaseValidatorModel):
    errorCode: BatchGetAssetPropertyValueHistoryErrorCodeType
    errorTimestamp: datetime


BlobTypeDef = Union[IO[Any], StreamingBody, bytes, str]


class ContentTypeDef(BaseValidatorModel):
    text: Optional[str] = None


class ColumnTypeTypeDef(BaseValidatorModel):
    scalarType: Optional[ScalarTypeType] = None


class CompositionRelationshipItemTypeDef(BaseValidatorModel):
    id: Optional[str] = None


class CompositionRelationshipSummaryTypeDef(BaseValidatorModel):
    assetModelId: str
    assetModelCompositeModelId: str
    assetModelCompositeModelType: str


class ComputationModelAnomalyDetectionConfigurationTypeDef(BaseValidatorModel):
    inputProperties: str
    resultProperty: str


class ConfigurationErrorDetailsTypeDef(BaseValidatorModel):
    code: ErrorCodeType
    message: str


class ConflictingOperationExceptionTypeDef(BaseValidatorModel):
    message: str
    resourceId: str
    resourceArn: str


# This class is the input for the 'create_asset' function.
class CreateAssetRequestTypeDef(BaseValidatorModel):
    assetName: str
    assetModelId: str
    assetId: Optional[str] = None
    assetExternalId: Optional[str] = None
    clientToken: Optional[str] = None
    tags: Optional[Dict[str, str]] = None
    assetDescription: Optional[str] = None


class ErrorReportLocationTypeDef(BaseValidatorModel):
    bucket: str
    prefix: str


class FileTypeDef(BaseValidatorModel):
    bucket: str
    key: str
    versionId: Optional[str] = None


# This class is the input for the 'create_dashboard' function.
class CreateDashboardRequestTypeDef(BaseValidatorModel):
    projectId: str
    dashboardName: str
    dashboardDefinition: str
    dashboardDescription: Optional[str] = None
    clientToken: Optional[str] = None
    tags: Optional[Dict[str, str]] = None


# This class is the input for the 'create_project' function.
class CreateProjectRequestTypeDef(BaseValidatorModel):
    portalId: str
    projectName: str
    projectDescription: Optional[str] = None
    clientToken: Optional[str] = None
    tags: Optional[Dict[str, str]] = None


class CsvOutputTypeDef(BaseValidatorModel):
    columnNames: List[ColumnNameType]


class CsvTypeDef(BaseValidatorModel):
    columnNames: List[ColumnNameType]


class CustomerManagedS3StorageTypeDef(BaseValidatorModel):
    s3ResourceArn: str
    roleArn: str


class DashboardSummaryTypeDef(BaseValidatorModel):
    id: str
    name: str
    description: Optional[str] = None
    creationDate: Optional[datetime] = None
    lastUpdateDate: Optional[datetime] = None


class DatumPaginatorTypeDef(BaseValidatorModel):
    scalarValue: Optional[str] = None
    arrayValue: Optional[List[Dict[str, Any]]] = None
    rowValue: Optional[Dict[str, Any]] = None
    nullValue: Optional[bool] = None


class DatumTypeDef(BaseValidatorModel):
    scalarValue: Optional[str] = None
    arrayValue: Optional[List[Dict[str, Any]]] = None
    rowValue: Optional[Dict[str, Any]] = None
    nullValue: Optional[bool] = None


class DatumWaiterTypeDef(BaseValidatorModel):
    scalarValue: Optional[str] = None
    arrayValue: Optional[List[Dict[str, Any]]] = None
    rowValue: Optional[Dict[str, Any]] = None
    nullValue: Optional[bool] = None


class DeleteAccessPolicyRequestTypeDef(BaseValidatorModel):
    accessPolicyId: str
    clientToken: Optional[str] = None


# This class is the input for the 'delete_asset_model_composite_model' function.
class DeleteAssetModelCompositeModelRequestTypeDef(BaseValidatorModel):
    assetModelId: str
    assetModelCompositeModelId: str
    clientToken: Optional[str] = None
    ifMatch: Optional[str] = None
    ifNoneMatch: Optional[str] = None
    matchForVersionType: Optional[AssetModelVersionTypeType] = None


# This class is the input for the 'delete_asset_model_interface_relationship' function.
class DeleteAssetModelInterfaceRelationshipRequestTypeDef(BaseValidatorModel):
    assetModelId: str
    interfaceAssetModelId: str
    clientToken: Optional[str] = None


# This class is the input for the 'delete_asset_model' function.
class DeleteAssetModelRequestTypeDef(BaseValidatorModel):
    assetModelId: str
    clientToken: Optional[str] = None
    ifMatch: Optional[str] = None
    ifNoneMatch: Optional[str] = None
    matchForVersionType: Optional[AssetModelVersionTypeType] = None


# This class is the input for the 'delete_asset' function.
class DeleteAssetRequestTypeDef(BaseValidatorModel):
    assetId: str
    clientToken: Optional[str] = None


# This class is the input for the 'delete_computation_model' function.
class DeleteComputationModelRequestTypeDef(BaseValidatorModel):
    computationModelId: str
    clientToken: Optional[str] = None


class DeleteDashboardRequestTypeDef(BaseValidatorModel):
    dashboardId: str
    clientToken: Optional[str] = None


# This class is the input for the 'delete_dataset' function.
class DeleteDatasetRequestTypeDef(BaseValidatorModel):
    datasetId: str
    clientToken: Optional[str] = None


# This class is the input for the 'delete_gateway' function.
class DeleteGatewayRequestTypeDef(BaseValidatorModel):
    gatewayId: str


# This class is the input for the 'delete_portal' function.
class DeletePortalRequestTypeDef(BaseValidatorModel):
    portalId: str
    clientToken: Optional[str] = None


class DeleteProjectRequestTypeDef(BaseValidatorModel):
    projectId: str
    clientToken: Optional[str] = None


# This class is the input for the 'delete_time_series' function.
class DeleteTimeSeriesRequestTypeDef(BaseValidatorModel):
    alias: Optional[str] = None
    assetId: Optional[str] = None
    propertyId: Optional[str] = None
    clientToken: Optional[str] = None


# This class is the input for the 'describe_access_policy' function.
class DescribeAccessPolicyRequestTypeDef(BaseValidatorModel):
    accessPolicyId: str


# This class is the input for the 'describe_action' function.
class DescribeActionRequestTypeDef(BaseValidatorModel):
    actionId: str


# This class is the input for the 'describe_asset_composite_model' function.
class DescribeAssetCompositeModelRequestTypeDef(BaseValidatorModel):
    assetId: str
    assetCompositeModelId: str


# This class is the input for the 'describe_asset_model_composite_model' function.
class DescribeAssetModelCompositeModelRequestTypeDef(BaseValidatorModel):
    assetModelId: str
    assetModelCompositeModelId: str
    assetModelVersion: Optional[str] = None


# This class is the input for the 'describe_asset_model_interface_relationship' function.
class DescribeAssetModelInterfaceRelationshipRequestTypeDef(BaseValidatorModel):
    assetModelId: str
    interfaceAssetModelId: str


class HierarchyMappingTypeDef(BaseValidatorModel):
    assetModelHierarchyId: str
    interfaceAssetModelHierarchyId: str


class PropertyMappingTypeDef(BaseValidatorModel):
    assetModelPropertyId: str
    interfaceAssetModelPropertyId: str


# This class is the input for the 'describe_asset_model' function.
class DescribeAssetModelRequestTypeDef(BaseValidatorModel):
    assetModelId: str
    excludeProperties: Optional[bool] = None
    assetModelVersion: Optional[str] = None


class WaiterConfigTypeDef(BaseValidatorModel):
    Delay: Optional[int] = None
    MaxAttempts: Optional[int] = None


class InterfaceRelationshipTypeDef(BaseValidatorModel):
    id: str


# This class is the input for the 'describe_asset_property' function.
class DescribeAssetPropertyRequestTypeDef(BaseValidatorModel):
    assetId: str
    propertyId: str


# This class is the input for the 'describe_asset' function.
class DescribeAssetRequestTypeDef(BaseValidatorModel):
    assetId: str
    excludeProperties: Optional[bool] = None


# This class is the input for the 'describe_bulk_import_job' function.
class DescribeBulkImportJobRequestTypeDef(BaseValidatorModel):
    jobId: str


# This class is the input for the 'describe_computation_model_execution_summary' function.
class DescribeComputationModelExecutionSummaryRequestTypeDef(BaseValidatorModel):
    computationModelId: str
    resolveToResourceType: Optional[Literal["ASSET"]] = None
    resolveToResourceId: Optional[str] = None


# This class is the input for the 'describe_computation_model' function.
class DescribeComputationModelRequestTypeDef(BaseValidatorModel):
    computationModelId: str
    computationModelVersion: Optional[str] = None


# This class is the input for the 'describe_dashboard' function.
class DescribeDashboardRequestTypeDef(BaseValidatorModel):
    dashboardId: str


# This class is the input for the 'describe_dataset' function.
class DescribeDatasetRequestTypeDef(BaseValidatorModel):
    datasetId: str


# This class is the input for the 'describe_execution' function.
class DescribeExecutionRequestTypeDef(BaseValidatorModel):
    executionId: str


class ExecutionStatusTypeDef(BaseValidatorModel):
    state: ExecutionStateType


# This class is the input for the 'describe_gateway_capability_configuration' function.
class DescribeGatewayCapabilityConfigurationRequestTypeDef(BaseValidatorModel):
    gatewayId: str
    capabilityNamespace: str


# This class is the input for the 'describe_gateway' function.
class DescribeGatewayRequestTypeDef(BaseValidatorModel):
    gatewayId: str


class GatewayCapabilitySummaryTypeDef(BaseValidatorModel):
    capabilityNamespace: str
    capabilitySyncStatus: CapabilitySyncStatusType


class LoggingOptionsTypeDef(BaseValidatorModel):
    level: LoggingLevelType


# This class is the input for the 'describe_portal' function.
class DescribePortalRequestTypeDef(BaseValidatorModel):
    portalId: str


class ImageLocationTypeDef(BaseValidatorModel):
    id: str
    url: str


class PortalTypeEntryOutputTypeDef(BaseValidatorModel):
    portalTools: Optional[List[str]] = None


# This class is the input for the 'describe_project' function.
class DescribeProjectRequestTypeDef(BaseValidatorModel):
    projectId: str


class RetentionPeriodTypeDef(BaseValidatorModel):
    numberOfDays: Optional[int] = None
    unlimited: Optional[bool] = None


class WarmTierRetentionPeriodTypeDef(BaseValidatorModel):
    numberOfDays: Optional[int] = None
    unlimited: Optional[bool] = None


# This class is the input for the 'describe_time_series' function.
class DescribeTimeSeriesRequestTypeDef(BaseValidatorModel):
    alias: Optional[str] = None
    assetId: Optional[str] = None
    propertyId: Optional[str] = None


class DetailedErrorTypeDef(BaseValidatorModel):
    code: DetailedErrorCodeType
    message: str


# This class is the input for the 'disassociate_assets' function.
class DisassociateAssetsRequestTypeDef(BaseValidatorModel):
    assetId: str
    hierarchyId: str
    childAssetId: str
    clientToken: Optional[str] = None


# This class is the input for the 'disassociate_time_series_from_asset_property' function.
class DisassociateTimeSeriesFromAssetPropertyRequestTypeDef(BaseValidatorModel):
    alias: str
    assetId: str
    propertyId: str
    clientToken: Optional[str] = None


class PaginatorConfigTypeDef(BaseValidatorModel):
    MaxItems: Optional[int] = None
    PageSize: Optional[int] = None
    StartingToken: Optional[str] = None


# This class is the input for the 'execute_query' function.
class ExecuteQueryRequestTypeDef(BaseValidatorModel):
    queryStatement: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None
    clientToken: Optional[str] = None


class ForwardingConfigTypeDef(BaseValidatorModel):
    state: ForwardingConfigStateType


class GreengrassTypeDef(BaseValidatorModel):
    groupArn: str


class GreengrassV2TypeDef(BaseValidatorModel):
    coreDeviceThingName: str
    coreDeviceOperatingSystem: Optional[CoreDeviceOperatingSystemType] = None


class SiemensIETypeDef(BaseValidatorModel):
    iotCoreThingName: str


# This class is the input for the 'get_asset_property_value' function.
class GetAssetPropertyValueRequestTypeDef(BaseValidatorModel):
    assetId: Optional[str] = None
    propertyId: Optional[str] = None
    propertyAlias: Optional[str] = None


# This class is the input for the 'get_interpolated_asset_property_values' function.
class GetInterpolatedAssetPropertyValuesRequestTypeDef(BaseValidatorModel):
    startTimeInSeconds: int
    endTimeInSeconds: int
    quality: QualityType
    intervalInSeconds: int
    type: str
    assetId: Optional[str] = None
    propertyId: Optional[str] = None
    propertyAlias: Optional[str] = None
    startTimeOffsetInNanos: Optional[int] = None
    endTimeOffsetInNanos: Optional[int] = None
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None
    intervalWindowInSeconds: Optional[int] = None


class GroupIdentityTypeDef(BaseValidatorModel):
    id: str


class IAMRoleIdentityTypeDef(BaseValidatorModel):
    arn: str


class IAMUserIdentityTypeDef(BaseValidatorModel):
    arn: str


class UserIdentityTypeDef(BaseValidatorModel):
    id: str


class InterfaceRelationshipSummaryTypeDef(BaseValidatorModel):
    id: str


class InternalFailureExceptionTypeDef(BaseValidatorModel):
    message: str


class InvalidRequestExceptionTypeDef(BaseValidatorModel):
    message: str


# This class is the input for the 'invoke_assistant' function.
class InvokeAssistantRequestTypeDef(BaseValidatorModel):
    message: str
    conversationId: Optional[str] = None
    enableTrace: Optional[bool] = None


class JobSummaryTypeDef(BaseValidatorModel):
    id: str
    name: str
    status: JobStatusType


class KendraSourceDetailTypeDef(BaseValidatorModel):
    knowledgeBaseArn: str
    roleArn: str


class LimitExceededExceptionTypeDef(BaseValidatorModel):
    message: str


# This class is the input for the 'list_access_policies' function.
class ListAccessPoliciesRequestTypeDef(BaseValidatorModel):
    identityType: Optional[IdentityTypeType] = None
    identityId: Optional[str] = None
    resourceType: Optional[ResourceTypeType] = None
    resourceId: Optional[str] = None
    iamArn: Optional[str] = None
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_actions' function.
class ListActionsRequestTypeDef(BaseValidatorModel):
    targetResourceType: TargetResourceTypeType
    targetResourceId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None
    resolveToResourceType: Optional[Literal["ASSET"]] = None
    resolveToResourceId: Optional[str] = None


# This class is the input for the 'list_asset_model_composite_models' function.
class ListAssetModelCompositeModelsRequestTypeDef(BaseValidatorModel):
    assetModelId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None
    assetModelVersion: Optional[str] = None


# This class is the input for the 'list_asset_model_properties' function.
class ListAssetModelPropertiesRequestTypeDef(BaseValidatorModel):
    assetModelId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None
    filter: Optional[ListAssetModelPropertiesFilterType] = None
    assetModelVersion: Optional[str] = None


# This class is the input for the 'list_asset_models' function.
class ListAssetModelsRequestTypeDef(BaseValidatorModel):
    assetModelTypes: Optional[List[AssetModelTypeType]] = None
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None
    assetModelVersion: Optional[str] = None


# This class is the input for the 'list_asset_properties' function.
class ListAssetPropertiesRequestTypeDef(BaseValidatorModel):
    assetId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None
    filter: Optional[ListAssetPropertiesFilterType] = None


# This class is the input for the 'list_asset_relationships' function.
class ListAssetRelationshipsRequestTypeDef(BaseValidatorModel):
    assetId: str
    traversalType: Literal["PATH_TO_ROOT"]
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_assets' function.
class ListAssetsRequestTypeDef(BaseValidatorModel):
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None
    assetModelId: Optional[str] = None
    filter: Optional[ListAssetsFilterType] = None


# This class is the input for the 'list_associated_assets' function.
class ListAssociatedAssetsRequestTypeDef(BaseValidatorModel):
    assetId: str
    hierarchyId: Optional[str] = None
    traversalDirection: Optional[TraversalDirectionType] = None
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_bulk_import_jobs' function.
class ListBulkImportJobsRequestTypeDef(BaseValidatorModel):
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None
    filter: Optional[ListBulkImportJobsFilterType] = None


# This class is the input for the 'list_composition_relationships' function.
class ListCompositionRelationshipsRequestTypeDef(BaseValidatorModel):
    assetModelId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_computation_model_resolve_to_resources' function.
class ListComputationModelResolveToResourcesRequestTypeDef(BaseValidatorModel):
    computationModelId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_computation_models' function.
class ListComputationModelsRequestTypeDef(BaseValidatorModel):
    computationModelType: Optional[Literal["ANOMALY_DETECTION"]] = None
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_dashboards' function.
class ListDashboardsRequestTypeDef(BaseValidatorModel):
    projectId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_datasets' function.
class ListDatasetsRequestTypeDef(BaseValidatorModel):
    sourceType: Literal["KENDRA"]
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_executions' function.
class ListExecutionsRequestTypeDef(BaseValidatorModel):
    targetResourceType: TargetResourceTypeType
    targetResourceId: str
    resolveToResourceType: Optional[Literal["ASSET"]] = None
    resolveToResourceId: Optional[str] = None
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None
    actionType: Optional[str] = None


# This class is the input for the 'list_gateways' function.
class ListGatewaysRequestTypeDef(BaseValidatorModel):
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_interface_relationships' function.
class ListInterfaceRelationshipsRequestTypeDef(BaseValidatorModel):
    interfaceAssetModelId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_portals' function.
class ListPortalsRequestTypeDef(BaseValidatorModel):
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_project_assets' function.
class ListProjectAssetsRequestTypeDef(BaseValidatorModel):
    projectId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'list_projects' function.
class ListProjectsRequestTypeDef(BaseValidatorModel):
    portalId: str
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


class ProjectSummaryTypeDef(BaseValidatorModel):
    id: str
    name: str
    description: Optional[str] = None
    creationDate: Optional[datetime] = None
    lastUpdateDate: Optional[datetime] = None


# This class is the input for the 'list_tags_for_resource' function.
class ListTagsForResourceRequestTypeDef(BaseValidatorModel):
    resourceArn: str


# This class is the input for the 'list_time_series' function.
class ListTimeSeriesRequestTypeDef(BaseValidatorModel):
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None
    assetId: Optional[str] = None
    aliasPrefix: Optional[str] = None
    timeSeriesType: Optional[ListTimeSeriesTypeType] = None


class TimeSeriesSummaryTypeDef(BaseValidatorModel):
    timeSeriesId: str
    dataType: PropertyDataTypeType
    timeSeriesCreationDate: datetime
    timeSeriesLastUpdateDate: datetime
    timeSeriesArn: str
    assetId: Optional[str] = None
    propertyId: Optional[str] = None
    alias: Optional[str] = None
    dataTypeSpec: Optional[str] = None


class LocationTypeDef(BaseValidatorModel):
    uri: Optional[str] = None


class MetricProcessingConfigTypeDef(BaseValidatorModel):
    computeLocation: ComputeLocationType


class TumblingWindowTypeDef(BaseValidatorModel):
    interval: str
    offset: Optional[str] = None


class MonitorErrorDetailsTypeDef(BaseValidatorModel):
    code: Optional[MonitorErrorCodeType] = None
    message: Optional[str] = None


class PortalResourceTypeDef(BaseValidatorModel):
    id: str


class PortalTypeEntryTypeDef(BaseValidatorModel):
    portalTools: Optional[List[str]] = None


class ProjectResourceTypeDef(BaseValidatorModel):
    id: str


class PropertyValueNullValueTypeDef(BaseValidatorModel):
    valueType: RawValueTypeType


# This class is the input for the 'put_default_encryption_configuration' function.
class PutDefaultEncryptionConfigurationRequestTypeDef(BaseValidatorModel):
    encryptionType: EncryptionTypeType
    kmsKeyId: Optional[str] = None


class ResourceNotFoundExceptionTypeDef(BaseValidatorModel):
    message: str


class ThrottlingExceptionTypeDef(BaseValidatorModel):
    message: str


class TraceTypeDef(BaseValidatorModel):
    text: Optional[str] = None


class TagResourceRequestTypeDef(BaseValidatorModel):
    resourceArn: str
    tags: Dict[str, str]


class UntagResourceRequestTypeDef(BaseValidatorModel):
    resourceArn: str
    tagKeys: List[str]


# This class is the input for the 'update_asset_property' function.
class UpdateAssetPropertyRequestTypeDef(BaseValidatorModel):
    assetId: str
    propertyId: str
    propertyAlias: Optional[str] = None
    propertyNotificationState: Optional[PropertyNotificationStateType] = None
    clientToken: Optional[str] = None
    propertyUnit: Optional[str] = None


# This class is the input for the 'update_asset' function.
class UpdateAssetRequestTypeDef(BaseValidatorModel):
    assetId: str
    assetName: str
    assetExternalId: Optional[str] = None
    clientToken: Optional[str] = None
    assetDescription: Optional[str] = None


class UpdateDashboardRequestTypeDef(BaseValidatorModel):
    dashboardId: str
    dashboardName: str
    dashboardDefinition: str
    dashboardDescription: Optional[str] = None
    clientToken: Optional[str] = None


# This class is the input for the 'update_gateway_capability_configuration' function.
class UpdateGatewayCapabilityConfigurationRequestTypeDef(BaseValidatorModel):
    gatewayId: str
    capabilityNamespace: str
    capabilityConfiguration: str


# This class is the input for the 'update_gateway' function.
class UpdateGatewayRequestTypeDef(BaseValidatorModel):
    gatewayId: str
    gatewayName: str


class UpdateProjectRequestTypeDef(BaseValidatorModel):
    projectId: str
    projectName: str
    projectDescription: Optional[str] = None
    clientToken: Optional[str] = None


class ComputationModelResolveToResourceSummaryTypeDef(BaseValidatorModel):
    resolveTo: Optional[ResolveToTypeDef] = None


class ActionSummaryTypeDef(BaseValidatorModel):
    actionId: Optional[str] = None
    actionDefinitionId: Optional[str] = None
    targetResource: Optional[TargetResourceTypeDef] = None
    resolveTo: Optional[ResolveToTypeDef] = None


# This class is the input for the 'execute_action' function.
class ExecuteActionRequestTypeDef(BaseValidatorModel):
    targetResource: TargetResourceTypeDef
    actionDefinitionId: str
    actionPayload: ActionPayloadTypeDef
    clientToken: Optional[str] = None
    resolveTo: Optional[ResolveToTypeDef] = None


class AggregatedValueTypeDef(BaseValidatorModel):
    timestamp: datetime
    value: AggregatesTypeDef
    quality: Optional[QualityType] = None


class AssetCompositeModelSummaryTypeDef(BaseValidatorModel):
    id: str
    name: str
    type: str
    description: str
    path: List[AssetCompositeModelPathSegmentTypeDef]
    externalId: Optional[str] = None


class AssetRelationshipSummaryTypeDef(BaseValidatorModel):
    relationshipType: Literal["HIERARCHY"]
    hierarchyInfo: Optional[AssetHierarchyInfoTypeDef] = None


class AssetModelCompositeModelSummaryTypeDef(BaseValidatorModel):
    id: str
    name: str
    type: str
    externalId: Optional[str] = None
    description: Optional[str] = None
    path: Optional[List[AssetModelCompositeModelPathSegmentTypeDef]] = None


class VariableValueOutputTypeDef(BaseValidatorModel):
    propertyId: Optional[str] = None
    hierarchyId: Optional[str] = None
    propertyPath: Optional[List[AssetModelPropertyPathSegmentTypeDef]] = None


class VariableValueTypeDef(BaseValidatorModel):
    propertyId: Optional[str] = None
    hierarchyId: Optional[str] = None
    propertyPath: Optional[List[AssetModelPropertyPathSegmentTypeDef]] = None


class DataBindingValueFilterTypeDef(BaseValidatorModel):
    asset: Optional[AssetBindingValueFilterTypeDef] = None
    assetModel: Optional[AssetModelBindingValueFilterTypeDef] = None
    assetProperty: Optional[AssetPropertyBindingValueFilterTypeDef] = None
    assetModelProperty: Optional[AssetModelPropertyBindingValueFilterTypeDef] = None


class ComputationModelDataBindingValueOutputTypeDef(BaseValidatorModel):
    assetModelProperty: Optional[AssetModelPropertyBindingValueTypeDef] = None
    assetProperty: Optional[AssetPropertyBindingValueTypeDef] = None
    list: Optional[List[Dict[str, Any]]] = None


class ComputationModelDataBindingValueTypeDef(BaseValidatorModel):
    assetModelProperty: Optional[AssetModelPropertyBindingValueTypeDef] = None
    assetProperty: Optional[AssetPropertyBindingValueTypeDef] = None
    list: Optional[List[Dict[str, Any]]] = None


class DataBindingValueTypeDef(BaseValidatorModel):
    assetModelProperty: Optional[AssetModelPropertyBindingValueTypeDef] = None
    assetProperty: Optional[AssetPropertyBindingValueTypeDef] = None


class AssetPropertySummaryTypeDef(BaseValidatorModel):
    id: str
    externalId: Optional[str] = None
    alias: Optional[str] = None
    unit: Optional[str] = None
    notification: Optional[PropertyNotificationTypeDef] = None
    assetCompositeModelId: Optional[str] = None
    path: Optional[List[AssetPropertyPathSegmentTypeDef]] = None


class AssetPropertyTypeDef(BaseValidatorModel):
    id: str
    name: str
    dataType: PropertyDataTypeType
    externalId: Optional[str] = None
    alias: Optional[str] = None
    notification: Optional[PropertyNotificationTypeDef] = None
    dataTypeSpec: Optional[str] = None
    unit: Optional[str] = None
    path: Optional[List[AssetPropertyPathSegmentTypeDef]] = None


class BatchPutAssetPropertyErrorTypeDef(BaseValidatorModel):
    errorCode: BatchPutAssetPropertyValueErrorCodeType
    errorMessage: str
    timestamps: List[TimeInNanosTypeDef]


# This class is the output for the 'batch_associate_project_assets' function.
class BatchAssociateProjectAssetsResponseTypeDef(BaseValidatorModel):
    errors: List[AssetErrorDetailsTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'batch_disassociate_project_assets' function.
class BatchDisassociateProjectAssetsResponseTypeDef(BaseValidatorModel):
    errors: List[AssetErrorDetailsTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_access_policy' function.
class CreateAccessPolicyResponseTypeDef(BaseValidatorModel):
    accessPolicyId: str
    accessPolicyArn: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_bulk_import_job' function.
class CreateBulkImportJobResponseTypeDef(BaseValidatorModel):
    jobId: str
    jobName: str
    jobStatus: JobStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_dashboard' function.
class CreateDashboardResponseTypeDef(BaseValidatorModel):
    dashboardId: str
    dashboardArn: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_gateway' function.
class CreateGatewayResponseTypeDef(BaseValidatorModel):
    gatewayId: str
    gatewayArn: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_project' function.
class CreateProjectResponseTypeDef(BaseValidatorModel):
    projectId: str
    projectArn: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_action' function.
class DescribeActionResponseTypeDef(BaseValidatorModel):
    actionId: str
    targetResource: TargetResourceTypeDef
    actionDefinitionId: str
    actionPayload: ActionPayloadTypeDef
    executionTime: datetime
    resolveTo: ResolveToTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_computation_model_execution_summary' function.
class DescribeComputationModelExecutionSummaryResponseTypeDef(BaseValidatorModel):
    computationModelId: str
    resolveTo: ResolveToTypeDef
    computationModelExecutionSummary: Dict[str, str]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_dashboard' function.
class DescribeDashboardResponseTypeDef(BaseValidatorModel):
    dashboardId: str
    dashboardArn: str
    dashboardName: str
    projectId: str
    dashboardDescription: str
    dashboardDefinition: str
    dashboardCreationDate: datetime
    dashboardLastUpdateDate: datetime
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_gateway_capability_configuration' function.
class DescribeGatewayCapabilityConfigurationResponseTypeDef(BaseValidatorModel):
    gatewayId: str
    capabilityNamespace: str
    capabilityConfiguration: str
    capabilitySyncStatus: CapabilitySyncStatusType
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_project' function.
class DescribeProjectResponseTypeDef(BaseValidatorModel):
    projectId: str
    projectArn: str
    projectName: str
    portalId: str
    projectDescription: str
    projectCreationDate: datetime
    projectLastUpdateDate: datetime
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_time_series' function.
class DescribeTimeSeriesResponseTypeDef(BaseValidatorModel):
    assetId: str
    propertyId: str
    alias: str
    timeSeriesId: str
    dataType: PropertyDataTypeType
    dataTypeSpec: str
    timeSeriesCreationDate: datetime
    timeSeriesLastUpdateDate: datetime
    timeSeriesArn: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'associate_assets' function.
class EmptyResponseMetadataTypeDef(BaseValidatorModel):
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'execute_action' function.
class ExecuteActionResponseTypeDef(BaseValidatorModel):
    actionId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_project_assets' function.
class ListProjectAssetsResponseTypeDef(BaseValidatorModel):
    assetIds: List[str]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_tags_for_resource' function.
class ListTagsForResourceResponseTypeDef(BaseValidatorModel):
    tags: Dict[str, str]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_gateway_capability_configuration' function.
class UpdateGatewayCapabilityConfigurationResponseTypeDef(BaseValidatorModel):
    capabilityNamespace: str
    capabilitySyncStatus: CapabilitySyncStatusType
    ResponseMetadata: ResponseMetadataTypeDef


class BatchGetAssetPropertyAggregatesEntryTypeDef(BaseValidatorModel):
    entryId: str
    aggregateTypes: List[AggregateTypeType]
    resolution: str
    startDate: TimestampTypeDef
    endDate: TimestampTypeDef
    assetId: Optional[str] = None
    propertyId: Optional[str] = None
    propertyAlias: Optional[str] = None
    qualities: Optional[List[QualityType]] = None
    timeOrdering: Optional[TimeOrderingType] = None


class BatchGetAssetPropertyValueHistoryEntryTypeDef(BaseValidatorModel):
    entryId: str
    assetId: Optional[str] = None
    propertyId: Optional[str] = None
    propertyAlias: Optional[str] = None
    startDate: Optional[TimestampTypeDef] = None
    endDate: Optional[TimestampTypeDef] = None
    qualities: Optional[List[QualityType]] = None
    timeOrdering: Optional[TimeOrderingType] = None


# This class is the input for the 'get_asset_property_aggregates' function.
class GetAssetPropertyAggregatesRequestTypeDef(BaseValidatorModel):
    aggregateTypes: List[AggregateTypeType]
    resolution: str
    startDate: TimestampTypeDef
    endDate: TimestampTypeDef
    assetId: Optional[str] = None
    propertyId: Optional[str] = None
    propertyAlias: Optional[str] = None
    qualities: Optional[List[QualityType]] = None
    timeOrdering: Optional[TimeOrderingType] = None
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'get_asset_property_value_history' function.
class GetAssetPropertyValueHistoryRequestTypeDef(BaseValidatorModel):
    assetId: Optional[str] = None
    propertyId: Optional[str] = None
    propertyAlias: Optional[str] = None
    startDate: Optional[TimestampTypeDef] = None
    endDate: Optional[TimestampTypeDef] = None
    qualities: Optional[List[QualityType]] = None
    timeOrdering: Optional[TimeOrderingType] = None
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


class BatchGetAssetPropertyAggregatesSkippedEntryTypeDef(BaseValidatorModel):
    entryId: str
    completionStatus: BatchEntryCompletionStatusType
    errorInfo: Optional[BatchGetAssetPropertyAggregatesErrorInfoTypeDef] = None


# This class is the input for the 'batch_get_asset_property_value' function.
class BatchGetAssetPropertyValueRequestTypeDef(BaseValidatorModel):
    entries: List[BatchGetAssetPropertyValueEntryTypeDef]
    nextToken: Optional[str] = None


class BatchGetAssetPropertyValueSkippedEntryTypeDef(BaseValidatorModel):
    entryId: str
    completionStatus: BatchEntryCompletionStatusType
    errorInfo: Optional[BatchGetAssetPropertyValueErrorInfoTypeDef] = None


class BatchGetAssetPropertyValueHistorySkippedEntryTypeDef(BaseValidatorModel):
    entryId: str
    completionStatus: BatchEntryCompletionStatusType
    errorInfo: Optional[BatchGetAssetPropertyValueHistoryErrorInfoTypeDef] = None


class ImageFileTypeDef(BaseValidatorModel):
    data: BlobTypeDef
    type: Literal["PNG"]


class ColumnInfoTypeDef(BaseValidatorModel):
    name: Optional[str] = None
    type: Optional[ColumnTypeTypeDef] = None


class CompositionDetailsTypeDef(BaseValidatorModel):
    compositionRelationship: Optional[List[CompositionRelationshipItemTypeDef]] = None


# This class is the output for the 'list_composition_relationships' function.
class ListCompositionRelationshipsResponseTypeDef(BaseValidatorModel):
    compositionRelationshipSummaries: List[CompositionRelationshipSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class ComputationModelConfigurationTypeDef(BaseValidatorModel):
    anomalyDetection: Optional[ComputationModelAnomalyDetectionConfigurationTypeDef] = None


class ConfigurationStatusTypeDef(BaseValidatorModel):
    state: ConfigurationStateType
    error: Optional[ConfigurationErrorDetailsTypeDef] = None


class FileFormatOutputTypeDef(BaseValidatorModel):
    csv: Optional[CsvOutputTypeDef] = None
    parquet: Optional[Dict[str, Any]] = None


class FileFormatTypeDef(BaseValidatorModel):
    csv: Optional[CsvTypeDef] = None
    parquet: Optional[Dict[str, Any]] = None


class MultiLayerStorageTypeDef(BaseValidatorModel):
    customerManagedS3Storage: CustomerManagedS3StorageTypeDef


# This class is the output for the 'list_dashboards' function.
class ListDashboardsResponseTypeDef(BaseValidatorModel):
    dashboardSummaries: List[DashboardSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class RowPaginatorTypeDef(BaseValidatorModel):
    data: List[DatumPaginatorTypeDef]


class RowTypeDef(BaseValidatorModel):
    data: List[DatumTypeDef]


class RowWaiterTypeDef(BaseValidatorModel):
    data: List[DatumWaiterTypeDef]


# This class is the output for the 'describe_asset_model_interface_relationship' function.
class DescribeAssetModelInterfaceRelationshipResponseTypeDef(BaseValidatorModel):
    assetModelId: str
    interfaceAssetModelId: str
    propertyMappings: List[PropertyMappingTypeDef]
    hierarchyMappings: List[HierarchyMappingTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class PropertyMappingConfigurationTypeDef(BaseValidatorModel):
    matchByPropertyName: Optional[bool] = None
    createMissingProperty: Optional[bool] = None
    overrides: Optional[List[PropertyMappingTypeDef]] = None


class DescribeAssetModelRequestWaitExtraTypeDef(BaseValidatorModel):
    assetModelId: str
    excludeProperties: Optional[bool] = None
    assetModelVersion: Optional[str] = None
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


class DescribeAssetModelRequestWaitTypeDef(BaseValidatorModel):
    assetModelId: str
    excludeProperties: Optional[bool] = None
    assetModelVersion: Optional[str] = None
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


class DescribeAssetRequestWaitExtraTypeDef(BaseValidatorModel):
    assetId: str
    excludeProperties: Optional[bool] = None
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


class DescribeAssetRequestWaitTypeDef(BaseValidatorModel):
    assetId: str
    excludeProperties: Optional[bool] = None
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


class DescribePortalRequestWaitExtraTypeDef(BaseValidatorModel):
    portalId: str
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


class DescribePortalRequestWaitTypeDef(BaseValidatorModel):
    portalId: str
    WaiterConfig: Optional[WaiterConfigTypeDef] = None


# This class is the output for the 'describe_execution' function.
class DescribeExecutionResponseTypeDef(BaseValidatorModel):
    executionId: str
    actionType: str
    targetResource: TargetResourceTypeDef
    targetResourceVersion: str
    resolveTo: ResolveToTypeDef
    executionStartTime: datetime
    executionEndTime: datetime
    executionStatus: ExecutionStatusTypeDef
    executionResult: Dict[str, str]
    executionDetails: Dict[str, str]
    executionEntityVersion: str
    ResponseMetadata: ResponseMetadataTypeDef


class ExecutionSummaryTypeDef(BaseValidatorModel):
    executionId: str
    targetResource: TargetResourceTypeDef
    targetResourceVersion: str
    executionStartTime: datetime
    executionStatus: ExecutionStatusTypeDef
    actionType: Optional[str] = None
    resolveTo: Optional[ResolveToTypeDef] = None
    executionEndTime: Optional[datetime] = None
    executionEntityVersion: Optional[str] = None


class DescribeLoggingOptionsResponseTypeDef(BaseValidatorModel):
    loggingOptions: LoggingOptionsTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class PutLoggingOptionsRequestTypeDef(BaseValidatorModel):
    loggingOptions: LoggingOptionsTypeDef


class ErrorDetailsTypeDef(BaseValidatorModel):
    code: ErrorCodeType
    message: str
    details: Optional[List[DetailedErrorTypeDef]] = None


class ExecuteQueryRequestPaginateTypeDef(BaseValidatorModel):
    queryStatement: str
    clientToken: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class GetAssetPropertyAggregatesRequestPaginateTypeDef(BaseValidatorModel):
    aggregateTypes: List[AggregateTypeType]
    resolution: str
    startDate: TimestampTypeDef
    endDate: TimestampTypeDef
    assetId: Optional[str] = None
    propertyId: Optional[str] = None
    propertyAlias: Optional[str] = None
    qualities: Optional[List[QualityType]] = None
    timeOrdering: Optional[TimeOrderingType] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class GetAssetPropertyValueHistoryRequestPaginateTypeDef(BaseValidatorModel):
    assetId: Optional[str] = None
    propertyId: Optional[str] = None
    propertyAlias: Optional[str] = None
    startDate: Optional[TimestampTypeDef] = None
    endDate: Optional[TimestampTypeDef] = None
    qualities: Optional[List[QualityType]] = None
    timeOrdering: Optional[TimeOrderingType] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class GetInterpolatedAssetPropertyValuesRequestPaginateTypeDef(BaseValidatorModel):
    startTimeInSeconds: int
    endTimeInSeconds: int
    quality: QualityType
    intervalInSeconds: int
    type: str
    assetId: Optional[str] = None
    propertyId: Optional[str] = None
    propertyAlias: Optional[str] = None
    startTimeOffsetInNanos: Optional[int] = None
    endTimeOffsetInNanos: Optional[int] = None
    intervalWindowInSeconds: Optional[int] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListAccessPoliciesRequestPaginateTypeDef(BaseValidatorModel):
    identityType: Optional[IdentityTypeType] = None
    identityId: Optional[str] = None
    resourceType: Optional[ResourceTypeType] = None
    resourceId: Optional[str] = None
    iamArn: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListActionsRequestPaginateTypeDef(BaseValidatorModel):
    targetResourceType: TargetResourceTypeType
    targetResourceId: str
    resolveToResourceType: Optional[Literal["ASSET"]] = None
    resolveToResourceId: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListAssetModelCompositeModelsRequestPaginateTypeDef(BaseValidatorModel):
    assetModelId: str
    assetModelVersion: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListAssetModelPropertiesRequestPaginateTypeDef(BaseValidatorModel):
    assetModelId: str
    filter: Optional[ListAssetModelPropertiesFilterType] = None
    assetModelVersion: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListAssetModelsRequestPaginateTypeDef(BaseValidatorModel):
    assetModelTypes: Optional[List[AssetModelTypeType]] = None
    assetModelVersion: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListAssetPropertiesRequestPaginateTypeDef(BaseValidatorModel):
    assetId: str
    filter: Optional[ListAssetPropertiesFilterType] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListAssetRelationshipsRequestPaginateTypeDef(BaseValidatorModel):
    assetId: str
    traversalType: Literal["PATH_TO_ROOT"]
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListAssetsRequestPaginateTypeDef(BaseValidatorModel):
    assetModelId: Optional[str] = None
    filter: Optional[ListAssetsFilterType] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListAssociatedAssetsRequestPaginateTypeDef(BaseValidatorModel):
    assetId: str
    hierarchyId: Optional[str] = None
    traversalDirection: Optional[TraversalDirectionType] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListBulkImportJobsRequestPaginateTypeDef(BaseValidatorModel):
    filter: Optional[ListBulkImportJobsFilterType] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListCompositionRelationshipsRequestPaginateTypeDef(BaseValidatorModel):
    assetModelId: str
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListComputationModelResolveToResourcesRequestPaginateTypeDef(BaseValidatorModel):
    computationModelId: str
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListComputationModelsRequestPaginateTypeDef(BaseValidatorModel):
    computationModelType: Optional[Literal["ANOMALY_DETECTION"]] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListDashboardsRequestPaginateTypeDef(BaseValidatorModel):
    projectId: str
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListDatasetsRequestPaginateTypeDef(BaseValidatorModel):
    sourceType: Literal["KENDRA"]
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListExecutionsRequestPaginateTypeDef(BaseValidatorModel):
    targetResourceType: TargetResourceTypeType
    targetResourceId: str
    resolveToResourceType: Optional[Literal["ASSET"]] = None
    resolveToResourceId: Optional[str] = None
    actionType: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListGatewaysRequestPaginateTypeDef(BaseValidatorModel):
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListInterfaceRelationshipsRequestPaginateTypeDef(BaseValidatorModel):
    interfaceAssetModelId: str
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListPortalsRequestPaginateTypeDef(BaseValidatorModel):
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListProjectAssetsRequestPaginateTypeDef(BaseValidatorModel):
    projectId: str
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListProjectsRequestPaginateTypeDef(BaseValidatorModel):
    portalId: str
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListTimeSeriesRequestPaginateTypeDef(BaseValidatorModel):
    assetId: Optional[str] = None
    aliasPrefix: Optional[str] = None
    timeSeriesType: Optional[ListTimeSeriesTypeType] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class MeasurementProcessingConfigTypeDef(BaseValidatorModel):
    forwardingConfig: ForwardingConfigTypeDef


class TransformProcessingConfigTypeDef(BaseValidatorModel):
    computeLocation: ComputeLocationType
    forwardingConfig: Optional[ForwardingConfigTypeDef] = None


class GatewayPlatformTypeDef(BaseValidatorModel):
    greengrass: Optional[GreengrassTypeDef] = None
    greengrassV2: Optional[GreengrassV2TypeDef] = None
    siemensIE: Optional[SiemensIETypeDef] = None


class IdentityTypeDef(BaseValidatorModel):
    user: Optional[UserIdentityTypeDef] = None
    group: Optional[GroupIdentityTypeDef] = None
    iamUser: Optional[IAMUserIdentityTypeDef] = None
    iamRole: Optional[IAMRoleIdentityTypeDef] = None


# This class is the output for the 'list_interface_relationships' function.
class ListInterfaceRelationshipsResponseTypeDef(BaseValidatorModel):
    interfaceRelationshipSummaries: List[InterfaceRelationshipSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_bulk_import_jobs' function.
class ListBulkImportJobsResponseTypeDef(BaseValidatorModel):
    jobSummaries: List[JobSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class SourceDetailTypeDef(BaseValidatorModel):
    kendra: Optional[KendraSourceDetailTypeDef] = None


# This class is the output for the 'list_projects' function.
class ListProjectsResponseTypeDef(BaseValidatorModel):
    projectSummaries: List[ProjectSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_time_series' function.
class ListTimeSeriesResponseTypeDef(BaseValidatorModel):
    TimeSeriesSummaries: List[TimeSeriesSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class SourceTypeDef(BaseValidatorModel):
    arn: Optional[str] = None
    location: Optional[LocationTypeDef] = None


class MetricWindowTypeDef(BaseValidatorModel):
    tumbling: Optional[TumblingWindowTypeDef] = None


class PortalStatusTypeDef(BaseValidatorModel):
    state: PortalStateType
    error: Optional[MonitorErrorDetailsTypeDef] = None


PortalTypeEntryUnionTypeDef = Union[PortalTypeEntryOutputTypeDef, PortalTypeEntryTypeDef]


class ResourceTypeDef(BaseValidatorModel):
    portal: Optional[PortalResourceTypeDef] = None
    project: Optional[ProjectResourceTypeDef] = None


class VariantTypeDef(BaseValidatorModel):
    stringValue: Optional[str] = None
    integerValue: Optional[int] = None
    doubleValue: Optional[float] = None
    booleanValue: Optional[bool] = None
    nullValue: Optional[PropertyValueNullValueTypeDef] = None


# This class is the output for the 'list_computation_model_resolve_to_resources' function.
class ListComputationModelResolveToResourcesResponseTypeDef(BaseValidatorModel):
    computationModelResolveToResourceSummaries: List[ComputationModelResolveToResourceSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_actions' function.
class ListActionsResponseTypeDef(BaseValidatorModel):
    actionSummaries: List[ActionSummaryTypeDef]
    nextToken: str
    ResponseMetadata: ResponseMetadataTypeDef


class BatchGetAssetPropertyAggregatesSuccessEntryTypeDef(BaseValidatorModel):
    entryId: str
    aggregatedValues: List[AggregatedValueTypeDef]


# This class is the output for the 'get_asset_property_aggregates' function.
class GetAssetPropertyAggregatesResponseTypeDef(BaseValidatorModel):
    aggregatedValues: List[AggregatedValueTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_asset_relationships' function.
class ListAssetRelationshipsResponseTypeDef(BaseValidatorModel):
    assetRelationshipSummaries: List[AssetRelationshipSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_asset_model_composite_models' function.
class ListAssetModelCompositeModelsResponseTypeDef(BaseValidatorModel):
    assetModelCompositeModelSummaries: List[AssetModelCompositeModelSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class ExpressionVariableOutputTypeDef(BaseValidatorModel):
    name: str
    value: VariableValueOutputTypeDef


VariableValueUnionTypeDef = Union[VariableValueOutputTypeDef, VariableValueTypeDef]


class ListComputationModelDataBindingUsagesRequestPaginateTypeDef(BaseValidatorModel):
    dataBindingValueFilter: DataBindingValueFilterTypeDef
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the input for the 'list_computation_model_data_binding_usages' function.
class ListComputationModelDataBindingUsagesRequestTypeDef(BaseValidatorModel):
    dataBindingValueFilter: DataBindingValueFilterTypeDef
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


ComputationModelDataBindingValueUnionTypeDef = Union[
    ComputationModelDataBindingValueOutputTypeDef, ComputationModelDataBindingValueTypeDef
]


class MatchedDataBindingTypeDef(BaseValidatorModel):
    value: DataBindingValueTypeDef


# This class is the output for the 'list_asset_properties' function.
class ListAssetPropertiesResponseTypeDef(BaseValidatorModel):
    assetPropertySummaries: List[AssetPropertySummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class AssetCompositeModelTypeDef(BaseValidatorModel):
    name: str
    type: str
    properties: List[AssetPropertyTypeDef]
    description: Optional[str] = None
    id: Optional[str] = None
    externalId: Optional[str] = None


# This class is the output for the 'describe_asset_composite_model' function.
class DescribeAssetCompositeModelResponseTypeDef(BaseValidatorModel):
    assetId: str
    assetCompositeModelId: str
    assetCompositeModelExternalId: str
    assetCompositeModelPath: List[AssetCompositeModelPathSegmentTypeDef]
    assetCompositeModelName: str
    assetCompositeModelDescription: str
    assetCompositeModelType: str
    assetCompositeModelProperties: List[AssetPropertyTypeDef]
    assetCompositeModelSummaries: List[AssetCompositeModelSummaryTypeDef]
    actionDefinitions: List[ActionDefinitionTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class BatchPutAssetPropertyErrorEntryTypeDef(BaseValidatorModel):
    entryId: str
    errors: List[BatchPutAssetPropertyErrorTypeDef]


# This class is the input for the 'batch_get_asset_property_aggregates' function.
class BatchGetAssetPropertyAggregatesRequestTypeDef(BaseValidatorModel):
    entries: List[BatchGetAssetPropertyAggregatesEntryTypeDef]
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


# This class is the input for the 'batch_get_asset_property_value_history' function.
class BatchGetAssetPropertyValueHistoryRequestTypeDef(BaseValidatorModel):
    entries: List[BatchGetAssetPropertyValueHistoryEntryTypeDef]
    nextToken: Optional[str] = None
    maxResults: Optional[int] = None


class ImageTypeDef(BaseValidatorModel):
    id: Optional[str] = None
    file: Optional[ImageFileTypeDef] = None


class DescribeDefaultEncryptionConfigurationResponseTypeDef(BaseValidatorModel):
    encryptionType: EncryptionTypeType
    kmsKeyArn: str
    configurationStatus: ConfigurationStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'put_default_encryption_configuration' function.
class PutDefaultEncryptionConfigurationResponseTypeDef(BaseValidatorModel):
    encryptionType: EncryptionTypeType
    kmsKeyArn: str
    configurationStatus: ConfigurationStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class JobConfigurationOutputTypeDef(BaseValidatorModel):
    fileFormat: FileFormatOutputTypeDef


class JobConfigurationTypeDef(BaseValidatorModel):
    fileFormat: FileFormatTypeDef


class DescribeStorageConfigurationResponseTypeDef(BaseValidatorModel):
    storageType: StorageTypeType
    multiLayerStorage: MultiLayerStorageTypeDef
    disassociatedDataStorage: DisassociatedDataStorageStateType
    retentionPeriod: RetentionPeriodTypeDef
    configurationStatus: ConfigurationStatusTypeDef
    lastUpdateDate: datetime
    warmTier: WarmTierStateType
    warmTierRetentionPeriod: WarmTierRetentionPeriodTypeDef
    disallowIngestNullNaN: bool
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'put_storage_configuration' function.
class PutStorageConfigurationRequestTypeDef(BaseValidatorModel):
    storageType: StorageTypeType
    multiLayerStorage: Optional[MultiLayerStorageTypeDef] = None
    disassociatedDataStorage: Optional[DisassociatedDataStorageStateType] = None
    retentionPeriod: Optional[RetentionPeriodTypeDef] = None
    warmTier: Optional[WarmTierStateType] = None
    warmTierRetentionPeriod: Optional[WarmTierRetentionPeriodTypeDef] = None
    disallowIngestNullNaN: Optional[bool] = None


# This class is the output for the 'put_storage_configuration' function.
class PutStorageConfigurationResponseTypeDef(BaseValidatorModel):
    storageType: StorageTypeType
    multiLayerStorage: MultiLayerStorageTypeDef
    disassociatedDataStorage: DisassociatedDataStorageStateType
    retentionPeriod: RetentionPeriodTypeDef
    configurationStatus: ConfigurationStatusTypeDef
    warmTier: WarmTierStateType
    warmTierRetentionPeriod: WarmTierRetentionPeriodTypeDef
    disallowIngestNullNaN: bool
    ResponseMetadata: ResponseMetadataTypeDef


class ExecuteQueryResponsePaginatorTypeDef(BaseValidatorModel):
    columns: List[ColumnInfoTypeDef]
    rows: List[RowPaginatorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'execute_query' function.
class ExecuteQueryResponseTypeDef(BaseValidatorModel):
    columns: List[ColumnInfoTypeDef]
    rows: List[RowTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class ExecuteQueryResponseWaiterTypeDef(BaseValidatorModel):
    columns: List[ColumnInfoTypeDef]
    rows: List[RowWaiterTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the input for the 'put_asset_model_interface_relationship' function.
class PutAssetModelInterfaceRelationshipRequestTypeDef(BaseValidatorModel):
    assetModelId: str
    interfaceAssetModelId: str
    propertyMappingConfiguration: PropertyMappingConfigurationTypeDef
    clientToken: Optional[str] = None


# This class is the output for the 'list_executions' function.
class ListExecutionsResponseTypeDef(BaseValidatorModel):
    executionSummaries: List[ExecutionSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class AssetModelStatusTypeDef(BaseValidatorModel):
    state: AssetModelStateType
    error: Optional[ErrorDetailsTypeDef] = None


class AssetStatusTypeDef(BaseValidatorModel):
    state: AssetStateType
    error: Optional[ErrorDetailsTypeDef] = None


class ComputationModelStatusTypeDef(BaseValidatorModel):
    state: ComputationModelStateType
    error: Optional[ErrorDetailsTypeDef] = None


class DatasetStatusTypeDef(BaseValidatorModel):
    state: DatasetStateType
    error: Optional[ErrorDetailsTypeDef] = None


class MeasurementTypeDef(BaseValidatorModel):
    processingConfig: Optional[MeasurementProcessingConfigTypeDef] = None


# This class is the input for the 'create_gateway' function.
class CreateGatewayRequestTypeDef(BaseValidatorModel):
    gatewayName: str
    gatewayPlatform: GatewayPlatformTypeDef
    gatewayVersion: Optional[str] = None
    tags: Optional[Dict[str, str]] = None


# This class is the output for the 'describe_gateway' function.
class DescribeGatewayResponseTypeDef(BaseValidatorModel):
    gatewayId: str
    gatewayName: str
    gatewayArn: str
    gatewayPlatform: GatewayPlatformTypeDef
    gatewayVersion: str
    gatewayCapabilitySummaries: List[GatewayCapabilitySummaryTypeDef]
    creationDate: datetime
    lastUpdateDate: datetime
    ResponseMetadata: ResponseMetadataTypeDef


class GatewaySummaryTypeDef(BaseValidatorModel):
    gatewayId: str
    gatewayName: str
    creationDate: datetime
    lastUpdateDate: datetime
    gatewayPlatform: Optional[GatewayPlatformTypeDef] = None
    gatewayVersion: Optional[str] = None
    gatewayCapabilitySummaries: Optional[List[GatewayCapabilitySummaryTypeDef]] = None


class DatasetSourceTypeDef(BaseValidatorModel):
    sourceType: Literal["KENDRA"]
    sourceFormat: Literal["KNOWLEDGE_BASE"]
    sourceDetail: Optional[SourceDetailTypeDef] = None


class DataSetReferenceTypeDef(BaseValidatorModel):
    datasetArn: Optional[str] = None
    source: Optional[SourceTypeDef] = None


# This class is the output for the 'create_portal' function.
class CreatePortalResponseTypeDef(BaseValidatorModel):
    portalId: str
    portalArn: str
    portalStartUrl: str
    portalStatus: PortalStatusTypeDef
    ssoApplicationId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_portal' function.
class DeletePortalResponseTypeDef(BaseValidatorModel):
    portalStatus: PortalStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_portal' function.
class DescribePortalResponseTypeDef(BaseValidatorModel):
    portalId: str
    portalArn: str
    portalName: str
    portalDescription: str
    portalClientId: str
    portalStartUrl: str
    portalContactEmail: str
    portalStatus: PortalStatusTypeDef
    portalCreationDate: datetime
    portalLastUpdateDate: datetime
    portalLogoImageLocation: ImageLocationTypeDef
    roleArn: str
    portalAuthMode: AuthModeType
    notificationSenderEmail: str
    alarms: AlarmsTypeDef
    portalType: PortalTypeType
    portalTypeConfiguration: Dict[str, PortalTypeEntryOutputTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class PortalSummaryTypeDef(BaseValidatorModel):
    id: str
    name: str
    startUrl: str
    status: PortalStatusTypeDef
    description: Optional[str] = None
    creationDate: Optional[datetime] = None
    lastUpdateDate: Optional[datetime] = None
    roleArn: Optional[str] = None
    portalType: Optional[PortalTypeType] = None


# This class is the output for the 'update_portal' function.
class UpdatePortalResponseTypeDef(BaseValidatorModel):
    portalStatus: PortalStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'create_portal' function.
class CreatePortalRequestTypeDef(BaseValidatorModel):
    portalName: str
    portalContactEmail: str
    roleArn: str
    portalDescription: Optional[str] = None
    clientToken: Optional[str] = None
    portalLogoImageFile: Optional[ImageFileTypeDef] = None
    tags: Optional[Dict[str, str]] = None
    portalAuthMode: Optional[AuthModeType] = None
    notificationSenderEmail: Optional[str] = None
    alarms: Optional[AlarmsTypeDef] = None
    portalType: Optional[PortalTypeType] = None
    portalTypeConfiguration: Optional[Dict[str, PortalTypeEntryUnionTypeDef]] = None


class AccessPolicySummaryTypeDef(BaseValidatorModel):
    id: str
    identity: IdentityTypeDef
    resource: ResourceTypeDef
    permission: PermissionType
    creationDate: Optional[datetime] = None
    lastUpdateDate: Optional[datetime] = None


# This class is the input for the 'create_access_policy' function.
class CreateAccessPolicyRequestTypeDef(BaseValidatorModel):
    accessPolicyIdentity: IdentityTypeDef
    accessPolicyResource: ResourceTypeDef
    accessPolicyPermission: PermissionType
    clientToken: Optional[str] = None
    tags: Optional[Dict[str, str]] = None


# This class is the output for the 'describe_access_policy' function.
class DescribeAccessPolicyResponseTypeDef(BaseValidatorModel):
    accessPolicyId: str
    accessPolicyArn: str
    accessPolicyIdentity: IdentityTypeDef
    accessPolicyResource: ResourceTypeDef
    accessPolicyPermission: PermissionType
    accessPolicyCreationDate: datetime
    accessPolicyLastUpdateDate: datetime
    ResponseMetadata: ResponseMetadataTypeDef


class UpdateAccessPolicyRequestTypeDef(BaseValidatorModel):
    accessPolicyId: str
    accessPolicyIdentity: IdentityTypeDef
    accessPolicyResource: ResourceTypeDef
    accessPolicyPermission: PermissionType
    clientToken: Optional[str] = None


class AssetPropertyValueTypeDef(BaseValidatorModel):
    value: VariantTypeDef
    timestamp: TimeInNanosTypeDef
    quality: Optional[QualityType] = None


class InterpolatedAssetPropertyValueTypeDef(BaseValidatorModel):
    timestamp: TimeInNanosTypeDef
    value: VariantTypeDef


# This class is the output for the 'batch_get_asset_property_aggregates' function.
class BatchGetAssetPropertyAggregatesResponseTypeDef(BaseValidatorModel):
    errorEntries: List[BatchGetAssetPropertyAggregatesErrorEntryTypeDef]
    successEntries: List[BatchGetAssetPropertyAggregatesSuccessEntryTypeDef]
    skippedEntries: List[BatchGetAssetPropertyAggregatesSkippedEntryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class MetricOutputTypeDef(BaseValidatorModel):
    window: MetricWindowTypeDef
    expression: Optional[str] = None
    variables: Optional[List[ExpressionVariableOutputTypeDef]] = None
    processingConfig: Optional[MetricProcessingConfigTypeDef] = None


class TransformOutputTypeDef(BaseValidatorModel):
    expression: str
    variables: List[ExpressionVariableOutputTypeDef]
    processingConfig: Optional[TransformProcessingConfigTypeDef] = None


class ExpressionVariableTypeDef(BaseValidatorModel):
    name: str
    value: VariableValueUnionTypeDef


# This class is the input for the 'create_computation_model' function.
class CreateComputationModelRequestTypeDef(BaseValidatorModel):
    computationModelName: str
    computationModelConfiguration: ComputationModelConfigurationTypeDef
    computationModelDataBinding: Dict[str, ComputationModelDataBindingValueUnionTypeDef]
    computationModelDescription: Optional[str] = None
    clientToken: Optional[str] = None
    tags: Optional[Dict[str, str]] = None


# This class is the input for the 'update_computation_model' function.
class UpdateComputationModelRequestTypeDef(BaseValidatorModel):
    computationModelId: str
    computationModelName: str
    computationModelConfiguration: ComputationModelConfigurationTypeDef
    computationModelDataBinding: Dict[str, ComputationModelDataBindingValueUnionTypeDef]
    computationModelDescription: Optional[str] = None
    clientToken: Optional[str] = None


class ComputationModelDataBindingUsageSummaryTypeDef(BaseValidatorModel):
    computationModelIds: List[str]
    matchedDataBinding: MatchedDataBindingTypeDef


# This class is the output for the 'batch_put_asset_property_value' function.
class BatchPutAssetPropertyValueResponseTypeDef(BaseValidatorModel):
    errorEntries: List[BatchPutAssetPropertyErrorEntryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'update_portal' function.
class UpdatePortalRequestTypeDef(BaseValidatorModel):
    portalId: str
    portalName: str
    portalContactEmail: str
    roleArn: str
    portalDescription: Optional[str] = None
    portalLogoImage: Optional[ImageTypeDef] = None
    clientToken: Optional[str] = None
    notificationSenderEmail: Optional[str] = None
    alarms: Optional[AlarmsTypeDef] = None
    portalType: Optional[PortalTypeType] = None
    portalTypeConfiguration: Optional[Dict[str, PortalTypeEntryUnionTypeDef]] = None


# This class is the output for the 'describe_bulk_import_job' function.
class DescribeBulkImportJobResponseTypeDef(BaseValidatorModel):
    jobId: str
    jobName: str
    jobStatus: JobStatusType
    jobRoleArn: str
    files: List[FileTypeDef]
    errorReportLocation: ErrorReportLocationTypeDef
    jobConfiguration: JobConfigurationOutputTypeDef
    jobCreationDate: datetime
    jobLastUpdateDate: datetime
    adaptiveIngestion: bool
    deleteFilesAfterImport: bool
    ResponseMetadata: ResponseMetadataTypeDef


JobConfigurationUnionTypeDef = Union[JobConfigurationOutputTypeDef, JobConfigurationTypeDef]


class AssetModelSummaryTypeDef(BaseValidatorModel):
    id: str
    arn: str
    name: str
    description: str
    creationDate: datetime
    lastUpdateDate: datetime
    status: AssetModelStatusTypeDef
    externalId: Optional[str] = None
    assetModelType: Optional[AssetModelTypeType] = None
    version: Optional[str] = None


# This class is the output for the 'create_asset_model_composite_model' function.
class CreateAssetModelCompositeModelResponseTypeDef(BaseValidatorModel):
    assetModelCompositeModelId: str
    assetModelCompositeModelPath: List[AssetModelCompositeModelPathSegmentTypeDef]
    assetModelStatus: AssetModelStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_asset_model' function.
class CreateAssetModelResponseTypeDef(BaseValidatorModel):
    assetModelId: str
    assetModelArn: str
    assetModelStatus: AssetModelStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_asset_model_composite_model' function.
class DeleteAssetModelCompositeModelResponseTypeDef(BaseValidatorModel):
    assetModelStatus: AssetModelStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_asset_model_interface_relationship' function.
class DeleteAssetModelInterfaceRelationshipResponseTypeDef(BaseValidatorModel):
    assetModelId: str
    interfaceAssetModelId: str
    assetModelArn: str
    assetModelStatus: AssetModelStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_asset_model' function.
class DeleteAssetModelResponseTypeDef(BaseValidatorModel):
    assetModelStatus: AssetModelStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'put_asset_model_interface_relationship' function.
class PutAssetModelInterfaceRelationshipResponseTypeDef(BaseValidatorModel):
    assetModelId: str
    interfaceAssetModelId: str
    assetModelArn: str
    assetModelStatus: AssetModelStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_asset_model_composite_model' function.
class UpdateAssetModelCompositeModelResponseTypeDef(BaseValidatorModel):
    assetModelCompositeModelPath: List[AssetModelCompositeModelPathSegmentTypeDef]
    assetModelStatus: AssetModelStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_asset_model' function.
class UpdateAssetModelResponseTypeDef(BaseValidatorModel):
    assetModelStatus: AssetModelStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class AssetSummaryTypeDef(BaseValidatorModel):
    id: str
    arn: str
    name: str
    assetModelId: str
    creationDate: datetime
    lastUpdateDate: datetime
    status: AssetStatusTypeDef
    hierarchies: List[AssetHierarchyTypeDef]
    externalId: Optional[str] = None
    description: Optional[str] = None


class AssociatedAssetsSummaryTypeDef(BaseValidatorModel):
    id: str
    arn: str
    name: str
    assetModelId: str
    creationDate: datetime
    lastUpdateDate: datetime
    status: AssetStatusTypeDef
    hierarchies: List[AssetHierarchyTypeDef]
    externalId: Optional[str] = None
    description: Optional[str] = None


# This class is the output for the 'create_asset' function.
class CreateAssetResponseTypeDef(BaseValidatorModel):
    assetId: str
    assetArn: str
    assetStatus: AssetStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_asset' function.
class DeleteAssetResponseTypeDef(BaseValidatorModel):
    assetStatus: AssetStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_asset' function.
class DescribeAssetResponseTypeDef(BaseValidatorModel):
    assetId: str
    assetExternalId: str
    assetArn: str
    assetName: str
    assetModelId: str
    assetProperties: List[AssetPropertyTypeDef]
    assetHierarchies: List[AssetHierarchyTypeDef]
    assetCompositeModels: List[AssetCompositeModelTypeDef]
    assetCreationDate: datetime
    assetLastUpdateDate: datetime
    assetStatus: AssetStatusTypeDef
    assetDescription: str
    assetCompositeModelSummaries: List[AssetCompositeModelSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_asset' function.
class UpdateAssetResponseTypeDef(BaseValidatorModel):
    assetStatus: AssetStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class ComputationModelSummaryTypeDef(BaseValidatorModel):
    id: str
    arn: str
    name: str
    type: Literal["ANOMALY_DETECTION"]
    creationDate: datetime
    lastUpdateDate: datetime
    status: ComputationModelStatusTypeDef
    version: str
    description: Optional[str] = None


# This class is the output for the 'create_computation_model' function.
class CreateComputationModelResponseTypeDef(BaseValidatorModel):
    computationModelId: str
    computationModelArn: str
    computationModelStatus: ComputationModelStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_computation_model' function.
class DeleteComputationModelResponseTypeDef(BaseValidatorModel):
    computationModelStatus: ComputationModelStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_computation_model' function.
class DescribeComputationModelResponseTypeDef(BaseValidatorModel):
    computationModelId: str
    computationModelArn: str
    computationModelName: str
    computationModelDescription: str
    computationModelConfiguration: ComputationModelConfigurationTypeDef
    computationModelDataBinding: Dict[str, ComputationModelDataBindingValueOutputTypeDef]
    computationModelCreationDate: datetime
    computationModelLastUpdateDate: datetime
    computationModelStatus: ComputationModelStatusTypeDef
    computationModelVersion: str
    actionDefinitions: List[ActionDefinitionTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_computation_model' function.
class UpdateComputationModelResponseTypeDef(BaseValidatorModel):
    computationModelStatus: ComputationModelStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_dataset' function.
class CreateDatasetResponseTypeDef(BaseValidatorModel):
    datasetId: str
    datasetArn: str
    datasetStatus: DatasetStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class DatasetSummaryTypeDef(BaseValidatorModel):
    id: str
    arn: str
    name: str
    description: str
    creationDate: datetime
    lastUpdateDate: datetime
    status: DatasetStatusTypeDef


# This class is the output for the 'delete_dataset' function.
class DeleteDatasetResponseTypeDef(BaseValidatorModel):
    datasetStatus: DatasetStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_dataset' function.
class UpdateDatasetResponseTypeDef(BaseValidatorModel):
    datasetId: str
    datasetArn: str
    datasetStatus: DatasetStatusTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_gateways' function.
class ListGatewaysResponseTypeDef(BaseValidatorModel):
    gatewaySummaries: List[GatewaySummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the input for the 'create_dataset' function.
class CreateDatasetRequestTypeDef(BaseValidatorModel):
    datasetName: str
    datasetSource: DatasetSourceTypeDef
    datasetId: Optional[str] = None
    datasetDescription: Optional[str] = None
    clientToken: Optional[str] = None
    tags: Optional[Dict[str, str]] = None


# This class is the output for the 'describe_dataset' function.
class DescribeDatasetResponseTypeDef(BaseValidatorModel):
    datasetId: str
    datasetArn: str
    datasetName: str
    datasetDescription: str
    datasetSource: DatasetSourceTypeDef
    datasetStatus: DatasetStatusTypeDef
    datasetCreationDate: datetime
    datasetLastUpdateDate: datetime
    datasetVersion: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'update_dataset' function.
class UpdateDatasetRequestTypeDef(BaseValidatorModel):
    datasetId: str
    datasetName: str
    datasetSource: DatasetSourceTypeDef
    datasetDescription: Optional[str] = None
    clientToken: Optional[str] = None


class ReferenceTypeDef(BaseValidatorModel):
    dataset: Optional[DataSetReferenceTypeDef] = None


# This class is the output for the 'list_portals' function.
class ListPortalsResponseTypeDef(BaseValidatorModel):
    portalSummaries: List[PortalSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_access_policies' function.
class ListAccessPoliciesResponseTypeDef(BaseValidatorModel):
    accessPolicySummaries: List[AccessPolicySummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class BatchGetAssetPropertyValueHistorySuccessEntryTypeDef(BaseValidatorModel):
    entryId: str
    assetPropertyValueHistory: List[AssetPropertyValueTypeDef]


class BatchGetAssetPropertyValueSuccessEntryTypeDef(BaseValidatorModel):
    entryId: str
    assetPropertyValue: Optional[AssetPropertyValueTypeDef] = None


# This class is the output for the 'get_asset_property_value_history' function.
class GetAssetPropertyValueHistoryResponseTypeDef(BaseValidatorModel):
    assetPropertyValueHistory: List[AssetPropertyValueTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'get_asset_property_value' function.
class GetAssetPropertyValueResponseTypeDef(BaseValidatorModel):
    propertyValue: AssetPropertyValueTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class PutAssetPropertyValueEntryTypeDef(BaseValidatorModel):
    entryId: str
    propertyValues: List[AssetPropertyValueTypeDef]
    assetId: Optional[str] = None
    propertyId: Optional[str] = None
    propertyAlias: Optional[str] = None


# This class is the output for the 'get_interpolated_asset_property_values' function.
class GetInterpolatedAssetPropertyValuesResponseTypeDef(BaseValidatorModel):
    interpolatedAssetPropertyValues: List[InterpolatedAssetPropertyValueTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class PropertyTypeOutputTypeDef(BaseValidatorModel):
    attribute: Optional[AttributeTypeDef] = None
    measurement: Optional[MeasurementTypeDef] = None
    transform: Optional[TransformOutputTypeDef] = None
    metric: Optional[MetricOutputTypeDef] = None


ExpressionVariableUnionTypeDef = Union[ExpressionVariableOutputTypeDef, ExpressionVariableTypeDef]


# This class is the output for the 'list_computation_model_data_binding_usages' function.
class ListComputationModelDataBindingUsagesResponseTypeDef(BaseValidatorModel):
    dataBindingUsageSummaries: List[ComputationModelDataBindingUsageSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the input for the 'create_bulk_import_job' function.
class CreateBulkImportJobRequestTypeDef(BaseValidatorModel):
    jobName: str
    jobRoleArn: str
    files: List[FileTypeDef]
    errorReportLocation: ErrorReportLocationTypeDef
    jobConfiguration: JobConfigurationUnionTypeDef
    adaptiveIngestion: Optional[bool] = None
    deleteFilesAfterImport: Optional[bool] = None


# This class is the output for the 'list_asset_models' function.
class ListAssetModelsResponseTypeDef(BaseValidatorModel):
    assetModelSummaries: List[AssetModelSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_assets' function.
class ListAssetsResponseTypeDef(BaseValidatorModel):
    assetSummaries: List[AssetSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_associated_assets' function.
class ListAssociatedAssetsResponseTypeDef(BaseValidatorModel):
    assetSummaries: List[AssociatedAssetsSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_computation_models' function.
class ListComputationModelsResponseTypeDef(BaseValidatorModel):
    computationModelSummaries: List[ComputationModelSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'list_datasets' function.
class ListDatasetsResponseTypeDef(BaseValidatorModel):
    datasetSummaries: List[DatasetSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class CitationTypeDef(BaseValidatorModel):
    reference: Optional[ReferenceTypeDef] = None
    content: Optional[ContentTypeDef] = None


# This class is the output for the 'batch_get_asset_property_value_history' function.
class BatchGetAssetPropertyValueHistoryResponseTypeDef(BaseValidatorModel):
    errorEntries: List[BatchGetAssetPropertyValueHistoryErrorEntryTypeDef]
    successEntries: List[BatchGetAssetPropertyValueHistorySuccessEntryTypeDef]
    skippedEntries: List[BatchGetAssetPropertyValueHistorySkippedEntryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the output for the 'batch_get_asset_property_value' function.
class BatchGetAssetPropertyValueResponseTypeDef(BaseValidatorModel):
    errorEntries: List[BatchGetAssetPropertyValueErrorEntryTypeDef]
    successEntries: List[BatchGetAssetPropertyValueSuccessEntryTypeDef]
    skippedEntries: List[BatchGetAssetPropertyValueSkippedEntryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


# This class is the input for the 'batch_put_asset_property_value' function.
class BatchPutAssetPropertyValueRequestTypeDef(BaseValidatorModel):
    entries: List[PutAssetPropertyValueEntryTypeDef]
    enablePartialEntryProcessing: Optional[bool] = None


class AssetModelPropertyOutputTypeDef(BaseValidatorModel):
    name: str
    dataType: PropertyDataTypeType
    type: PropertyTypeOutputTypeDef
    id: Optional[str] = None
    externalId: Optional[str] = None
    dataTypeSpec: Optional[str] = None
    unit: Optional[str] = None
    path: Optional[List[AssetModelPropertyPathSegmentTypeDef]] = None


class AssetModelPropertySummaryTypeDef(BaseValidatorModel):
    name: str
    dataType: PropertyDataTypeType
    type: PropertyTypeOutputTypeDef
    id: Optional[str] = None
    externalId: Optional[str] = None
    dataTypeSpec: Optional[str] = None
    unit: Optional[str] = None
    assetModelCompositeModelId: Optional[str] = None
    path: Optional[List[AssetModelPropertyPathSegmentTypeDef]] = None
    interfaceSummaries: Optional[List[InterfaceSummaryTypeDef]] = None


class PropertyTypeDef(BaseValidatorModel):
    id: str
    name: str
    dataType: PropertyDataTypeType
    externalId: Optional[str] = None
    alias: Optional[str] = None
    notification: Optional[PropertyNotificationTypeDef] = None
    unit: Optional[str] = None
    type: Optional[PropertyTypeOutputTypeDef] = None
    path: Optional[List[AssetPropertyPathSegmentTypeDef]] = None


class MetricTypeDef(BaseValidatorModel):
    window: MetricWindowTypeDef
    expression: Optional[str] = None
    variables: Optional[List[ExpressionVariableUnionTypeDef]] = None
    processingConfig: Optional[MetricProcessingConfigTypeDef] = None


class TransformTypeDef(BaseValidatorModel):
    expression: str
    variables: List[ExpressionVariableUnionTypeDef]
    processingConfig: Optional[TransformProcessingConfigTypeDef] = None


class InvocationOutputTypeDef(BaseValidatorModel):
    message: Optional[str] = None
    citations: Optional[List[CitationTypeDef]] = None


class AssetModelCompositeModelOutputTypeDef(BaseValidatorModel):
    name: str
    type: str
    description: Optional[str] = None
    properties: Optional[List[AssetModelPropertyOutputTypeDef]] = None
    id: Optional[str] = None
    externalId: Optional[str] = None


# This class is the output for the 'describe_asset_model_composite_model' function.
class DescribeAssetModelCompositeModelResponseTypeDef(BaseValidatorModel):
    assetModelId: str
    assetModelCompositeModelId: str
    assetModelCompositeModelExternalId: str
    assetModelCompositeModelPath: List[AssetModelCompositeModelPathSegmentTypeDef]
    assetModelCompositeModelName: str
    assetModelCompositeModelDescription: str
    assetModelCompositeModelType: str
    assetModelCompositeModelProperties: List[AssetModelPropertyOutputTypeDef]
    compositionDetails: CompositionDetailsTypeDef
    assetModelCompositeModelSummaries: List[AssetModelCompositeModelSummaryTypeDef]
    actionDefinitions: List[ActionDefinitionTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_asset_model_properties' function.
class ListAssetModelPropertiesResponseTypeDef(BaseValidatorModel):
    assetModelPropertySummaries: List[AssetModelPropertySummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    nextToken: Optional[str] = None


class CompositeModelPropertyTypeDef(BaseValidatorModel):
    name: str
    type: str
    assetProperty: PropertyTypeDef
    id: Optional[str] = None
    externalId: Optional[str] = None


MetricUnionTypeDef = Union[MetricOutputTypeDef, MetricTypeDef]

TransformUnionTypeDef = Union[TransformOutputTypeDef, TransformTypeDef]


class ResponseStreamTypeDef(BaseValidatorModel):
    trace: Optional[TraceTypeDef] = None
    output: Optional[InvocationOutputTypeDef] = None
    accessDeniedException: Optional[AccessDeniedExceptionTypeDef] = None
    conflictingOperationException: Optional[ConflictingOperationExceptionTypeDef] = None
    internalFailureException: Optional[InternalFailureExceptionTypeDef] = None
    invalidRequestException: Optional[InvalidRequestExceptionTypeDef] = None
    limitExceededException: Optional[LimitExceededExceptionTypeDef] = None
    resourceNotFoundException: Optional[ResourceNotFoundExceptionTypeDef] = None
    throttlingException: Optional[ThrottlingExceptionTypeDef] = None


# This class is the output for the 'describe_asset_model' function.
class DescribeAssetModelResponseTypeDef(BaseValidatorModel):
    assetModelId: str
    assetModelExternalId: str
    assetModelArn: str
    assetModelName: str
    assetModelType: AssetModelTypeType
    assetModelDescription: str
    assetModelProperties: List[AssetModelPropertyOutputTypeDef]
    assetModelHierarchies: List[AssetModelHierarchyTypeDef]
    assetModelCompositeModels: List[AssetModelCompositeModelOutputTypeDef]
    assetModelCompositeModelSummaries: List[AssetModelCompositeModelSummaryTypeDef]
    assetModelCreationDate: datetime
    assetModelLastUpdateDate: datetime
    assetModelStatus: AssetModelStatusTypeDef
    assetModelVersion: str
    interfaceDetails: List[InterfaceRelationshipTypeDef]
    eTag: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_asset_property' function.
class DescribeAssetPropertyResponseTypeDef(BaseValidatorModel):
    assetId: str
    assetExternalId: str
    assetName: str
    assetModelId: str
    assetProperty: PropertyTypeDef
    compositeModel: CompositeModelPropertyTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class PropertyTypeTypeDef(BaseValidatorModel):
    attribute: Optional[AttributeTypeDef] = None
    measurement: Optional[MeasurementTypeDef] = None
    transform: Optional[TransformUnionTypeDef] = None
    metric: Optional[MetricUnionTypeDef] = None


# This class is the output for the 'invoke_assistant' function.
class InvokeAssistantResponseTypeDef(EventStream[ResponseStreamTypeDef]):
    pass


PropertyTypeUnionTypeDef = Union[PropertyTypeOutputTypeDef, PropertyTypeTypeDef]


class AssetModelPropertyDefinitionTypeDef(BaseValidatorModel):
    name: str
    dataType: PropertyDataTypeType
    type: PropertyTypeUnionTypeDef
    id: Optional[str] = None
    externalId: Optional[str] = None
    dataTypeSpec: Optional[str] = None
    unit: Optional[str] = None


class AssetModelPropertyTypeDef(BaseValidatorModel):
    name: str
    dataType: PropertyDataTypeType
    type: PropertyTypeUnionTypeDef
    id: Optional[str] = None
    externalId: Optional[str] = None
    dataTypeSpec: Optional[str] = None
    unit: Optional[str] = None
    path: Optional[List[AssetModelPropertyPathSegmentTypeDef]] = None


class AssetModelCompositeModelDefinitionTypeDef(BaseValidatorModel):
    name: str
    type: str
    id: Optional[str] = None
    externalId: Optional[str] = None
    description: Optional[str] = None
    properties: Optional[List[AssetModelPropertyDefinitionTypeDef]] = None


# This class is the input for the 'create_asset_model_composite_model' function.
class CreateAssetModelCompositeModelRequestTypeDef(BaseValidatorModel):
    assetModelId: str
    assetModelCompositeModelName: str
    assetModelCompositeModelType: str
    assetModelCompositeModelExternalId: Optional[str] = None
    parentAssetModelCompositeModelId: Optional[str] = None
    assetModelCompositeModelId: Optional[str] = None
    assetModelCompositeModelDescription: Optional[str] = None
    clientToken: Optional[str] = None
    composedAssetModelId: Optional[str] = None
    assetModelCompositeModelProperties: Optional[List[AssetModelPropertyDefinitionTypeDef]] = None
    ifMatch: Optional[str] = None
    ifNoneMatch: Optional[str] = None
    matchForVersionType: Optional[AssetModelVersionTypeType] = None


AssetModelPropertyUnionTypeDef = Union[AssetModelPropertyOutputTypeDef, AssetModelPropertyTypeDef]


# This class is the input for the 'create_asset_model' function.
class CreateAssetModelRequestTypeDef(BaseValidatorModel):
    assetModelName: str
    assetModelType: Optional[AssetModelTypeType] = None
    assetModelId: Optional[str] = None
    assetModelExternalId: Optional[str] = None
    assetModelDescription: Optional[str] = None
    assetModelProperties: Optional[List[AssetModelPropertyDefinitionTypeDef]] = None
    assetModelHierarchies: Optional[List[AssetModelHierarchyDefinitionTypeDef]] = None
    assetModelCompositeModels: Optional[List[AssetModelCompositeModelDefinitionTypeDef]] = None
    clientToken: Optional[str] = None
    tags: Optional[Dict[str, str]] = None


class AssetModelCompositeModelTypeDef(BaseValidatorModel):
    name: str
    type: str
    description: Optional[str] = None
    properties: Optional[List[AssetModelPropertyUnionTypeDef]] = None
    id: Optional[str] = None
    externalId: Optional[str] = None


# This class is the input for the 'update_asset_model_composite_model' function.
class UpdateAssetModelCompositeModelRequestTypeDef(BaseValidatorModel):
    assetModelId: str
    assetModelCompositeModelId: str
    assetModelCompositeModelName: str
    assetModelCompositeModelExternalId: Optional[str] = None
    assetModelCompositeModelDescription: Optional[str] = None
    clientToken: Optional[str] = None
    assetModelCompositeModelProperties: Optional[List[AssetModelPropertyUnionTypeDef]] = None
    ifMatch: Optional[str] = None
    ifNoneMatch: Optional[str] = None
    matchForVersionType: Optional[AssetModelVersionTypeType] = None


AssetModelCompositeModelUnionTypeDef = Union[AssetModelCompositeModelOutputTypeDef, AssetModelCompositeModelTypeDef]


# This class is the input for the 'update_asset_model' function.
class UpdateAssetModelRequestTypeDef(BaseValidatorModel):
    assetModelId: str
    assetModelName: str
    assetModelExternalId: Optional[str] = None
    assetModelDescription: Optional[str] = None
    assetModelProperties: Optional[List[AssetModelPropertyUnionTypeDef]] = None
    assetModelHierarchies: Optional[List[AssetModelHierarchyTypeDef]] = None
    assetModelCompositeModels: Optional[List[AssetModelCompositeModelUnionTypeDef]] = None
    clientToken: Optional[str] = None
    ifMatch: Optional[str] = None
    ifNoneMatch: Optional[str] = None
    matchForVersionType: Optional[AssetModelVersionTypeType] = None
