# This file is auto-generated by aws_resource_validator.generator.pipeline_b.
# Do not edit manually; run `arv-generate pipeline-b` to refresh it.
from datetime import datetime
from decimal import Decimal
from typing import (
    Annotated,
    Any,
    Callable,
    Dict,
    FrozenSet,
    IO,
    List,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    Union,
)

from botocore.client import BaseClient
from botocore.response import StreamingBody
from pydantic import Field

from aws_resource_validator.core.base_validator_model import BaseValidatorModel, EventStream
from aws_resource_validator.core.pattern_validation import aws_field_pattern as _aws_pattern
from aws_resource_validator.pydantic_models.ds_data.ds_data_constants import *  # noqa: F401,F403

# Optional boto3 symbols — imported lazily so services that don't need them
# aren't forced to pull in boto3 at import time.
try:
    from boto3.dynamodb.conditions import ConditionBase  # noqa: F401
except ImportError:  # pragma: no cover
    ConditionBase = Any  # type: ignore[assignment,misc]
try:
    from boto3.s3.transfer import TransferConfig  # noqa: F401
except ImportError:  # pragma: no cover
    TransferConfig = Any  # type: ignore[assignment,misc]


class AddGroupMemberRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    GroupName: Annotated[str, _aws_pattern("DsData", "GroupName")]
    MemberName: Annotated[str, _aws_pattern("DsData", "MemberName")]
    ClientToken: Optional[Annotated[str, _aws_pattern("DsData", "ClientToken")]] = None
    MemberRealm: Optional[Annotated[str, _aws_pattern("DsData", "Realm")]] = None


class AttributeValueOutputTypeDef(BaseValidatorModel):
    BOOL: Optional[bool] = None
    N: Optional[int] = None
    S: Optional[str] = None
    SS: Optional[List[str]] = None


class AttributeValueTypeDef(BaseValidatorModel):
    BOOL: Optional[bool] = None
    N: Optional[int] = None
    S: Optional[str] = None
    SS: Optional[List[str]] = None


class ResponseMetadataTypeDef(BaseValidatorModel):
    RequestId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, str]
    RetryAttempts: int
    HostId: Optional[str] = None


class DeleteGroupRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "GroupName")]
    ClientToken: Optional[Annotated[str, _aws_pattern("DsData", "ClientToken")]] = None


class DeleteUserRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "UserName")]
    ClientToken: Optional[Annotated[str, _aws_pattern("DsData", "ClientToken")]] = None


# This class is the input for the 'describe_group' function.
class DescribeGroupRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "GroupName")]
    OtherAttributes: Optional[List[Annotated[str, _aws_pattern("DsData", "LdapDisplayName")]]] = None
    Realm: Optional[Annotated[str, _aws_pattern("DsData", "Realm")]] = None


# This class is the input for the 'describe_user' function.
class DescribeUserRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "UserName")]
    OtherAttributes: Optional[List[Annotated[str, _aws_pattern("DsData", "LdapDisplayName")]]] = None
    Realm: Optional[Annotated[str, _aws_pattern("DsData", "Realm")]] = None


class DisableUserRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "UserName")]
    ClientToken: Optional[Annotated[str, _aws_pattern("DsData", "ClientToken")]] = None


class GroupSummaryTypeDef(BaseValidatorModel):
    GroupScope: GroupScopeType
    GroupType: GroupTypeType
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "GroupName")]
    SID: str


class PaginatorConfigTypeDef(BaseValidatorModel):
    MaxItems: Optional[int] = None
    PageSize: Optional[int] = None
    StartingToken: Optional[str] = None


# This class is the input for the 'list_group_members' function.
class ListGroupMembersRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "GroupName")]
    MaxResults: Optional[int] = None
    MemberRealm: Optional[Annotated[str, _aws_pattern("DsData", "Realm")]] = None
    NextToken: Optional[str] = None
    Realm: Optional[Annotated[str, _aws_pattern("DsData", "Realm")]] = None


class MemberTypeDef(BaseValidatorModel):
    MemberType: MemberTypeType
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "MemberName")]
    SID: str


# This class is the input for the 'list_groups_for_member' function.
class ListGroupsForMemberRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "MemberName")]
    MaxResults: Optional[int] = None
    MemberRealm: Optional[Annotated[str, _aws_pattern("DsData", "Realm")]] = None
    NextToken: Optional[str] = None
    Realm: Optional[Annotated[str, _aws_pattern("DsData", "Realm")]] = None


# This class is the input for the 'list_groups' function.
class ListGroupsRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None
    Realm: Optional[Annotated[str, _aws_pattern("DsData", "Realm")]] = None


# This class is the input for the 'list_users' function.
class ListUsersRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None
    Realm: Optional[Annotated[str, _aws_pattern("DsData", "Realm")]] = None


class UserSummaryTypeDef(BaseValidatorModel):
    Enabled: bool
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "UserName")]
    SID: str
    GivenName: Optional[str] = None
    Surname: Optional[str] = None


class RemoveGroupMemberRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    GroupName: Annotated[str, _aws_pattern("DsData", "GroupName")]
    MemberName: Annotated[str, _aws_pattern("DsData", "MemberName")]
    ClientToken: Optional[Annotated[str, _aws_pattern("DsData", "ClientToken")]] = None
    MemberRealm: Optional[Annotated[str, _aws_pattern("DsData", "Realm")]] = None


# This class is the input for the 'search_groups' function.
class SearchGroupsRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SearchAttributes: List[Annotated[str, _aws_pattern("DsData", "LdapDisplayName")]]
    SearchString: str
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None
    Realm: Optional[Annotated[str, _aws_pattern("DsData", "Realm")]] = None


# This class is the input for the 'search_users' function.
class SearchUsersRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SearchAttributes: List[Annotated[str, _aws_pattern("DsData", "LdapDisplayName")]]
    SearchString: str
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None
    Realm: Optional[Annotated[str, _aws_pattern("DsData", "Realm")]] = None


class GroupTypeDef(BaseValidatorModel):
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "GroupName")]
    DistinguishedName: Optional[str] = None
    GroupScope: Optional[GroupScopeType] = None
    GroupType: Optional[GroupTypeType] = None
    OtherAttributes: Optional[Dict[str, AttributeValueOutputTypeDef]] = None
    SID: Optional[str] = None


class UserTypeDef(BaseValidatorModel):
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "UserName")]
    DistinguishedName: Optional[str] = None
    EmailAddress: Optional[str] = None
    Enabled: Optional[bool] = None
    GivenName: Optional[str] = None
    OtherAttributes: Optional[Dict[str, AttributeValueOutputTypeDef]] = None
    SID: Optional[str] = None
    Surname: Optional[str] = None
    UserPrincipalName: Optional[str] = None


AttributeValueUnionTypeDef = Union[AttributeValueOutputTypeDef, AttributeValueTypeDef]


# This class is the output for the 'create_group' function.
class CreateGroupResultTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "GroupName")]
    SID: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_user' function.
class CreateUserResultTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "UserName")]
    SID: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_group' function.
class DescribeGroupResultTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    DistinguishedName: str
    GroupScope: GroupScopeType
    GroupType: GroupTypeType
    OtherAttributes: Dict[str, AttributeValueOutputTypeDef]
    Realm: Annotated[str, _aws_pattern("DsData", "Realm")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "GroupName")]
    SID: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_user' function.
class DescribeUserResultTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    DistinguishedName: str
    EmailAddress: str
    Enabled: bool
    GivenName: str
    OtherAttributes: Dict[str, AttributeValueOutputTypeDef]
    Realm: Annotated[str, _aws_pattern("DsData", "Realm")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "UserName")]
    SID: str
    Surname: str
    UserPrincipalName: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_groups_for_member' function.
class ListGroupsForMemberResultTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    Groups: List[GroupSummaryTypeDef]
    MemberRealm: Annotated[str, _aws_pattern("DsData", "Realm")]
    Realm: Annotated[str, _aws_pattern("DsData", "Realm")]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'list_groups' function.
class ListGroupsResultTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    Groups: List[GroupSummaryTypeDef]
    Realm: Annotated[str, _aws_pattern("DsData", "Realm")]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


class ListGroupMembersRequestPaginateTypeDef(BaseValidatorModel):
    DirectoryId: str
    SAMAccountName: str
    MemberRealm: Optional[str] = None
    Realm: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListGroupsForMemberRequestPaginateTypeDef(BaseValidatorModel):
    DirectoryId: str
    SAMAccountName: str
    MemberRealm: Optional[str] = None
    Realm: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListGroupsRequestPaginateTypeDef(BaseValidatorModel):
    DirectoryId: str
    Realm: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class ListUsersRequestPaginateTypeDef(BaseValidatorModel):
    DirectoryId: str
    Realm: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class SearchGroupsRequestPaginateTypeDef(BaseValidatorModel):
    DirectoryId: str
    SearchAttributes: List[str]
    SearchString: str
    Realm: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


class SearchUsersRequestPaginateTypeDef(BaseValidatorModel):
    DirectoryId: str
    SearchAttributes: List[str]
    SearchString: str
    Realm: Optional[str] = None
    PaginationConfig: Optional[PaginatorConfigTypeDef] = None


# This class is the output for the 'list_group_members' function.
class ListGroupMembersResultTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    MemberRealm: Annotated[str, _aws_pattern("DsData", "Realm")]
    Members: List[MemberTypeDef]
    Realm: Annotated[str, _aws_pattern("DsData", "Realm")]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'list_users' function.
class ListUsersResultTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    Realm: Annotated[str, _aws_pattern("DsData", "Realm")]
    Users: List[UserSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'search_groups' function.
class SearchGroupsResultTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    Groups: List[GroupTypeDef]
    Realm: Annotated[str, _aws_pattern("DsData", "Realm")]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'search_users' function.
class SearchUsersResultTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    Realm: Annotated[str, _aws_pattern("DsData", "Realm")]
    Users: List[UserTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the input for the 'create_group' function.
class CreateGroupRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "GroupName")]
    ClientToken: Optional[Annotated[str, _aws_pattern("DsData", "ClientToken")]] = None
    GroupScope: Optional[GroupScopeType] = None
    GroupType: Optional[GroupTypeType] = None
    OtherAttributes: Optional[Dict[str, AttributeValueUnionTypeDef]] = None


# This class is the input for the 'create_user' function.
class CreateUserRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "UserName")]
    ClientToken: Optional[Annotated[str, _aws_pattern("DsData", "ClientToken")]] = None
    EmailAddress: Optional[str] = None
    GivenName: Optional[str] = None
    OtherAttributes: Optional[Dict[str, AttributeValueUnionTypeDef]] = None
    Surname: Optional[str] = None


class UpdateGroupRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "GroupName")]
    ClientToken: Optional[Annotated[str, _aws_pattern("DsData", "ClientToken")]] = None
    GroupScope: Optional[GroupScopeType] = None
    GroupType: Optional[GroupTypeType] = None
    OtherAttributes: Optional[Dict[str, AttributeValueUnionTypeDef]] = None
    UpdateType: Optional[UpdateTypeType] = None


class UpdateUserRequestTypeDef(BaseValidatorModel):
    DirectoryId: Annotated[str, _aws_pattern("DsData", "DirectoryId")]
    SAMAccountName: Annotated[str, _aws_pattern("DsData", "UserName")]
    ClientToken: Optional[Annotated[str, _aws_pattern("DsData", "ClientToken")]] = None
    EmailAddress: Optional[str] = None
    GivenName: Optional[str] = None
    OtherAttributes: Optional[Dict[str, AttributeValueUnionTypeDef]] = None
    Surname: Optional[str] = None
    UpdateType: Optional[UpdateTypeType] = None
