# This file is auto-generated by aws_resource_validator.generator.pipeline_b.
# Do not edit manually; run `arv-generate pipeline-b` to refresh it.
from datetime import datetime
from decimal import Decimal
from typing import (
    Any,
    Callable,
    Dict,
    FrozenSet,
    IO,
    List,
    Literal,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    Union,
)

from botocore.client import BaseClient
from botocore.response import StreamingBody
from pydantic import Field

from aws_resource_validator.core.base_validator_model import BaseValidatorModel, EventStream
from aws_resource_validator.pydantic_models.apprunner.apprunner_constants import *  # noqa: F401,F403

# Optional boto3 symbols — imported lazily so services that don't need them
# aren't forced to pull in boto3 at import time.
try:
    from boto3.dynamodb.conditions import ConditionBase  # noqa: F401
except ImportError:  # pragma: no cover
    ConditionBase = Any  # type: ignore[assignment,misc]
try:
    from boto3.s3.transfer import TransferConfig  # noqa: F401
except ImportError:  # pragma: no cover
    TransferConfig = Any  # type: ignore[assignment,misc]


# This class is the input for the 'associate_custom_domain' function.
class AssociateCustomDomainRequestTypeDef(BaseValidatorModel):
    ServiceArn: str
    DomainName: str
    EnableWWWSubdomain: Optional[bool] = None


class ResponseMetadataTypeDef(BaseValidatorModel):
    RequestId: str
    HTTPStatusCode: int
    HTTPHeaders: Dict[str, str]
    RetryAttempts: int
    HostId: Optional[str] = None


class VpcDNSTargetTypeDef(BaseValidatorModel):
    VpcIngressConnectionArn: Optional[str] = None
    VpcId: Optional[str] = None
    DomainName: Optional[str] = None


class AuthenticationConfigurationTypeDef(BaseValidatorModel):
    ConnectionArn: Optional[str] = None
    AccessRoleArn: Optional[str] = None


class AutoScalingConfigurationSummaryTypeDef(BaseValidatorModel):
    AutoScalingConfigurationArn: Optional[str] = None
    AutoScalingConfigurationName: Optional[str] = None
    AutoScalingConfigurationRevision: Optional[int] = None
    Status: Optional[AutoScalingConfigurationStatusType] = None
    CreatedAt: Optional[datetime] = None
    HasAssociatedService: Optional[bool] = None
    IsDefault: Optional[bool] = None


class AutoScalingConfigurationTypeDef(BaseValidatorModel):
    AutoScalingConfigurationArn: Optional[str] = None
    AutoScalingConfigurationName: Optional[str] = None
    AutoScalingConfigurationRevision: Optional[int] = None
    Latest: Optional[bool] = None
    Status: Optional[AutoScalingConfigurationStatusType] = None
    MaxConcurrency: Optional[int] = None
    MinSize: Optional[int] = None
    MaxSize: Optional[int] = None
    CreatedAt: Optional[datetime] = None
    DeletedAt: Optional[datetime] = None
    HasAssociatedService: Optional[bool] = None
    IsDefault: Optional[bool] = None


class CertificateValidationRecordTypeDef(BaseValidatorModel):
    Name: Optional[str] = None
    Type: Optional[str] = None
    Value: Optional[str] = None
    Status: Optional[CertificateValidationRecordStatusType] = None


class CodeConfigurationValuesOutputTypeDef(BaseValidatorModel):
    Runtime: RuntimeType
    BuildCommand: Optional[str] = None
    StartCommand: Optional[str] = None
    Port: Optional[str] = None
    RuntimeEnvironmentVariables: Optional[Dict[str, str]] = None
    RuntimeEnvironmentSecrets: Optional[Dict[str, str]] = None


class CodeConfigurationValuesTypeDef(BaseValidatorModel):
    Runtime: RuntimeType
    BuildCommand: Optional[str] = None
    StartCommand: Optional[str] = None
    Port: Optional[str] = None
    RuntimeEnvironmentVariables: Optional[Dict[str, str]] = None
    RuntimeEnvironmentSecrets: Optional[Dict[str, str]] = None


class SourceCodeVersionTypeDef(BaseValidatorModel):
    Type: Literal["BRANCH"]
    Value: str


class ConnectionSummaryTypeDef(BaseValidatorModel):
    ConnectionName: Optional[str] = None
    ConnectionArn: Optional[str] = None
    ProviderType: Optional[ProviderTypeType] = None
    Status: Optional[ConnectionStatusType] = None
    CreatedAt: Optional[datetime] = None


class ConnectionTypeDef(BaseValidatorModel):
    ConnectionName: Optional[str] = None
    ConnectionArn: Optional[str] = None
    ProviderType: Optional[ProviderTypeType] = None
    Status: Optional[ConnectionStatusType] = None
    CreatedAt: Optional[datetime] = None


class TagTypeDef(BaseValidatorModel):
    Key: Optional[str] = None
    Value: Optional[str] = None


class TraceConfigurationTypeDef(BaseValidatorModel):
    Vendor: Literal["AWSXRAY"]


class EncryptionConfigurationTypeDef(BaseValidatorModel):
    KmsKey: str


class HealthCheckConfigurationTypeDef(BaseValidatorModel):
    Protocol: Optional[HealthCheckProtocolType] = None
    Path: Optional[str] = None
    Interval: Optional[int] = None
    Timeout: Optional[int] = None
    HealthyThreshold: Optional[int] = None
    UnhealthyThreshold: Optional[int] = None


class InstanceConfigurationTypeDef(BaseValidatorModel):
    Cpu: Optional[str] = None
    Memory: Optional[str] = None
    InstanceRoleArn: Optional[str] = None


class ServiceObservabilityConfigurationTypeDef(BaseValidatorModel):
    ObservabilityEnabled: bool
    ObservabilityConfigurationArn: Optional[str] = None


class VpcConnectorTypeDef(BaseValidatorModel):
    VpcConnectorName: Optional[str] = None
    VpcConnectorArn: Optional[str] = None
    VpcConnectorRevision: Optional[int] = None
    Subnets: Optional[List[str]] = None
    SecurityGroups: Optional[List[str]] = None
    Status: Optional[VpcConnectorStatusType] = None
    CreatedAt: Optional[datetime] = None
    DeletedAt: Optional[datetime] = None


class IngressVpcConfigurationTypeDef(BaseValidatorModel):
    VpcId: Optional[str] = None
    VpcEndpointId: Optional[str] = None


# This class is the input for the 'delete_auto_scaling_configuration' function.
class DeleteAutoScalingConfigurationRequestTypeDef(BaseValidatorModel):
    AutoScalingConfigurationArn: str
    DeleteAllRevisions: Optional[bool] = None


# This class is the input for the 'delete_connection' function.
class DeleteConnectionRequestTypeDef(BaseValidatorModel):
    ConnectionArn: str


# This class is the input for the 'delete_observability_configuration' function.
class DeleteObservabilityConfigurationRequestTypeDef(BaseValidatorModel):
    ObservabilityConfigurationArn: str


# This class is the input for the 'delete_service' function.
class DeleteServiceRequestTypeDef(BaseValidatorModel):
    ServiceArn: str


# This class is the input for the 'delete_vpc_connector' function.
class DeleteVpcConnectorRequestTypeDef(BaseValidatorModel):
    VpcConnectorArn: str


# This class is the input for the 'delete_vpc_ingress_connection' function.
class DeleteVpcIngressConnectionRequestTypeDef(BaseValidatorModel):
    VpcIngressConnectionArn: str


# This class is the input for the 'describe_auto_scaling_configuration' function.
class DescribeAutoScalingConfigurationRequestTypeDef(BaseValidatorModel):
    AutoScalingConfigurationArn: str


# This class is the input for the 'describe_custom_domains' function.
class DescribeCustomDomainsRequestTypeDef(BaseValidatorModel):
    ServiceArn: str
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


# This class is the input for the 'describe_observability_configuration' function.
class DescribeObservabilityConfigurationRequestTypeDef(BaseValidatorModel):
    ObservabilityConfigurationArn: str


# This class is the input for the 'describe_service' function.
class DescribeServiceRequestTypeDef(BaseValidatorModel):
    ServiceArn: str


# This class is the input for the 'describe_vpc_connector' function.
class DescribeVpcConnectorRequestTypeDef(BaseValidatorModel):
    VpcConnectorArn: str


# This class is the input for the 'describe_vpc_ingress_connection' function.
class DescribeVpcIngressConnectionRequestTypeDef(BaseValidatorModel):
    VpcIngressConnectionArn: str


# This class is the input for the 'disassociate_custom_domain' function.
class DisassociateCustomDomainRequestTypeDef(BaseValidatorModel):
    ServiceArn: str
    DomainName: str


class EgressConfigurationTypeDef(BaseValidatorModel):
    EgressType: Optional[EgressTypeType] = None
    VpcConnectorArn: Optional[str] = None


class ImageConfigurationOutputTypeDef(BaseValidatorModel):
    RuntimeEnvironmentVariables: Optional[Dict[str, str]] = None
    StartCommand: Optional[str] = None
    Port: Optional[str] = None
    RuntimeEnvironmentSecrets: Optional[Dict[str, str]] = None


class ImageConfigurationTypeDef(BaseValidatorModel):
    RuntimeEnvironmentVariables: Optional[Dict[str, str]] = None
    StartCommand: Optional[str] = None
    Port: Optional[str] = None
    RuntimeEnvironmentSecrets: Optional[Dict[str, str]] = None


class IngressConfigurationTypeDef(BaseValidatorModel):
    IsPubliclyAccessible: Optional[bool] = None


# This class is the input for the 'list_auto_scaling_configurations' function.
class ListAutoScalingConfigurationsRequestTypeDef(BaseValidatorModel):
    AutoScalingConfigurationName: Optional[str] = None
    LatestOnly: Optional[bool] = None
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None


# This class is the input for the 'list_connections' function.
class ListConnectionsRequestTypeDef(BaseValidatorModel):
    ConnectionName: Optional[str] = None
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None


# This class is the input for the 'list_observability_configurations' function.
class ListObservabilityConfigurationsRequestTypeDef(BaseValidatorModel):
    ObservabilityConfigurationName: Optional[str] = None
    LatestOnly: Optional[bool] = None
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None


class ObservabilityConfigurationSummaryTypeDef(BaseValidatorModel):
    ObservabilityConfigurationArn: Optional[str] = None
    ObservabilityConfigurationName: Optional[str] = None
    ObservabilityConfigurationRevision: Optional[int] = None


# This class is the input for the 'list_operations' function.
class ListOperationsRequestTypeDef(BaseValidatorModel):
    ServiceArn: str
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


class OperationSummaryTypeDef(BaseValidatorModel):
    Id: Optional[str] = None
    Type: Optional[OperationTypeType] = None
    Status: Optional[OperationStatusType] = None
    TargetArn: Optional[str] = None
    StartedAt: Optional[datetime] = None
    EndedAt: Optional[datetime] = None
    UpdatedAt: Optional[datetime] = None


# This class is the input for the 'list_services_for_auto_scaling_configuration' function.
class ListServicesForAutoScalingConfigurationRequestTypeDef(BaseValidatorModel):
    AutoScalingConfigurationArn: str
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None


# This class is the input for the 'list_services' function.
class ListServicesRequestTypeDef(BaseValidatorModel):
    NextToken: Optional[str] = None
    MaxResults: Optional[int] = None


class ServiceSummaryTypeDef(BaseValidatorModel):
    ServiceName: Optional[str] = None
    ServiceId: Optional[str] = None
    ServiceArn: Optional[str] = None
    ServiceUrl: Optional[str] = None
    CreatedAt: Optional[datetime] = None
    UpdatedAt: Optional[datetime] = None
    Status: Optional[ServiceStatusType] = None


# This class is the input for the 'list_tags_for_resource' function.
class ListTagsForResourceRequestTypeDef(BaseValidatorModel):
    ResourceArn: str


# This class is the input for the 'list_vpc_connectors' function.
class ListVpcConnectorsRequestTypeDef(BaseValidatorModel):
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None


class ListVpcIngressConnectionsFilterTypeDef(BaseValidatorModel):
    ServiceArn: Optional[str] = None
    VpcEndpointId: Optional[str] = None


class VpcIngressConnectionSummaryTypeDef(BaseValidatorModel):
    VpcIngressConnectionArn: Optional[str] = None
    ServiceArn: Optional[str] = None


# This class is the input for the 'pause_service' function.
class PauseServiceRequestTypeDef(BaseValidatorModel):
    ServiceArn: str


# This class is the input for the 'resume_service' function.
class ResumeServiceRequestTypeDef(BaseValidatorModel):
    ServiceArn: str


# This class is the input for the 'start_deployment' function.
class StartDeploymentRequestTypeDef(BaseValidatorModel):
    ServiceArn: str


class UntagResourceRequestTypeDef(BaseValidatorModel):
    ResourceArn: str
    TagKeys: List[str]


# This class is the input for the 'update_default_auto_scaling_configuration' function.
class UpdateDefaultAutoScalingConfigurationRequestTypeDef(BaseValidatorModel):
    AutoScalingConfigurationArn: str


# This class is the output for the 'list_services_for_auto_scaling_configuration' function.
class ListServicesForAutoScalingConfigurationResponseTypeDef(BaseValidatorModel):
    ServiceArnList: List[str]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'start_deployment' function.
class StartDeploymentResponseTypeDef(BaseValidatorModel):
    OperationId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_auto_scaling_configurations' function.
class ListAutoScalingConfigurationsResponseTypeDef(BaseValidatorModel):
    AutoScalingConfigurationSummaryList: List[AutoScalingConfigurationSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'create_auto_scaling_configuration' function.
class CreateAutoScalingConfigurationResponseTypeDef(BaseValidatorModel):
    AutoScalingConfiguration: AutoScalingConfigurationTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_auto_scaling_configuration' function.
class DeleteAutoScalingConfigurationResponseTypeDef(BaseValidatorModel):
    AutoScalingConfiguration: AutoScalingConfigurationTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_auto_scaling_configuration' function.
class DescribeAutoScalingConfigurationResponseTypeDef(BaseValidatorModel):
    AutoScalingConfiguration: AutoScalingConfigurationTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_default_auto_scaling_configuration' function.
class UpdateDefaultAutoScalingConfigurationResponseTypeDef(BaseValidatorModel):
    AutoScalingConfiguration: AutoScalingConfigurationTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class CustomDomainTypeDef(BaseValidatorModel):
    DomainName: str
    EnableWWWSubdomain: bool
    Status: CustomDomainAssociationStatusType
    CertificateValidationRecords: Optional[List[CertificateValidationRecordTypeDef]] = None


class CodeConfigurationOutputTypeDef(BaseValidatorModel):
    ConfigurationSource: ConfigurationSourceType
    CodeConfigurationValues: Optional[CodeConfigurationValuesOutputTypeDef] = None


class CodeConfigurationTypeDef(BaseValidatorModel):
    ConfigurationSource: ConfigurationSourceType
    CodeConfigurationValues: Optional[CodeConfigurationValuesTypeDef] = None


# This class is the output for the 'list_connections' function.
class ListConnectionsResponseTypeDef(BaseValidatorModel):
    ConnectionSummaryList: List[ConnectionSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'create_connection' function.
class CreateConnectionResponseTypeDef(BaseValidatorModel):
    Connection: ConnectionTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_connection' function.
class DeleteConnectionResponseTypeDef(BaseValidatorModel):
    Connection: ConnectionTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'create_auto_scaling_configuration' function.
class CreateAutoScalingConfigurationRequestTypeDef(BaseValidatorModel):
    AutoScalingConfigurationName: str
    MaxConcurrency: Optional[int] = None
    MinSize: Optional[int] = None
    MaxSize: Optional[int] = None
    Tags: Optional[List[TagTypeDef]] = None


# This class is the input for the 'create_connection' function.
class CreateConnectionRequestTypeDef(BaseValidatorModel):
    ConnectionName: str
    ProviderType: ProviderTypeType
    Tags: Optional[List[TagTypeDef]] = None


# This class is the input for the 'create_vpc_connector' function.
class CreateVpcConnectorRequestTypeDef(BaseValidatorModel):
    VpcConnectorName: str
    Subnets: List[str]
    SecurityGroups: Optional[List[str]] = None
    Tags: Optional[List[TagTypeDef]] = None


# This class is the output for the 'list_tags_for_resource' function.
class ListTagsForResourceResponseTypeDef(BaseValidatorModel):
    Tags: List[TagTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class TagResourceRequestTypeDef(BaseValidatorModel):
    ResourceArn: str
    Tags: List[TagTypeDef]


# This class is the input for the 'create_observability_configuration' function.
class CreateObservabilityConfigurationRequestTypeDef(BaseValidatorModel):
    ObservabilityConfigurationName: str
    TraceConfiguration: Optional[TraceConfigurationTypeDef] = None
    Tags: Optional[List[TagTypeDef]] = None


class ObservabilityConfigurationTypeDef(BaseValidatorModel):
    ObservabilityConfigurationArn: Optional[str] = None
    ObservabilityConfigurationName: Optional[str] = None
    TraceConfiguration: Optional[TraceConfigurationTypeDef] = None
    ObservabilityConfigurationRevision: Optional[int] = None
    Latest: Optional[bool] = None
    Status: Optional[ObservabilityConfigurationStatusType] = None
    CreatedAt: Optional[datetime] = None
    DeletedAt: Optional[datetime] = None


# This class is the output for the 'create_vpc_connector' function.
class CreateVpcConnectorResponseTypeDef(BaseValidatorModel):
    VpcConnector: VpcConnectorTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_vpc_connector' function.
class DeleteVpcConnectorResponseTypeDef(BaseValidatorModel):
    VpcConnector: VpcConnectorTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_vpc_connector' function.
class DescribeVpcConnectorResponseTypeDef(BaseValidatorModel):
    VpcConnector: VpcConnectorTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'list_vpc_connectors' function.
class ListVpcConnectorsResponseTypeDef(BaseValidatorModel):
    VpcConnectors: List[VpcConnectorTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the input for the 'create_vpc_ingress_connection' function.
class CreateVpcIngressConnectionRequestTypeDef(BaseValidatorModel):
    ServiceArn: str
    VpcIngressConnectionName: str
    IngressVpcConfiguration: IngressVpcConfigurationTypeDef
    Tags: Optional[List[TagTypeDef]] = None


# This class is the input for the 'update_vpc_ingress_connection' function.
class UpdateVpcIngressConnectionRequestTypeDef(BaseValidatorModel):
    VpcIngressConnectionArn: str
    IngressVpcConfiguration: IngressVpcConfigurationTypeDef


class VpcIngressConnectionTypeDef(BaseValidatorModel):
    VpcIngressConnectionArn: Optional[str] = None
    VpcIngressConnectionName: Optional[str] = None
    ServiceArn: Optional[str] = None
    Status: Optional[VpcIngressConnectionStatusType] = None
    AccountId: Optional[str] = None
    DomainName: Optional[str] = None
    IngressVpcConfiguration: Optional[IngressVpcConfigurationTypeDef] = None
    CreatedAt: Optional[datetime] = None
    DeletedAt: Optional[datetime] = None


class ImageRepositoryOutputTypeDef(BaseValidatorModel):
    ImageIdentifier: str
    ImageRepositoryType: ImageRepositoryTypeType
    ImageConfiguration: Optional[ImageConfigurationOutputTypeDef] = None


class ImageRepositoryTypeDef(BaseValidatorModel):
    ImageIdentifier: str
    ImageRepositoryType: ImageRepositoryTypeType
    ImageConfiguration: Optional[ImageConfigurationTypeDef] = None


class NetworkConfigurationTypeDef(BaseValidatorModel):
    EgressConfiguration: Optional[EgressConfigurationTypeDef] = None
    IngressConfiguration: Optional[IngressConfigurationTypeDef] = None
    IpAddressType: Optional[IpAddressTypeType] = None


# This class is the output for the 'list_observability_configurations' function.
class ListObservabilityConfigurationsResponseTypeDef(BaseValidatorModel):
    ObservabilityConfigurationSummaryList: List[ObservabilityConfigurationSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'list_operations' function.
class ListOperationsResponseTypeDef(BaseValidatorModel):
    OperationSummaryList: List[OperationSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'list_services' function.
class ListServicesResponseTypeDef(BaseValidatorModel):
    ServiceSummaryList: List[ServiceSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the input for the 'list_vpc_ingress_connections' function.
class ListVpcIngressConnectionsRequestTypeDef(BaseValidatorModel):
    Filter: Optional[ListVpcIngressConnectionsFilterTypeDef] = None
    MaxResults: Optional[int] = None
    NextToken: Optional[str] = None


# This class is the output for the 'list_vpc_ingress_connections' function.
class ListVpcIngressConnectionsResponseTypeDef(BaseValidatorModel):
    VpcIngressConnectionSummaryList: List[VpcIngressConnectionSummaryTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'associate_custom_domain' function.
class AssociateCustomDomainResponseTypeDef(BaseValidatorModel):
    DNSTarget: str
    ServiceArn: str
    CustomDomain: CustomDomainTypeDef
    VpcDNSTargets: List[VpcDNSTargetTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_custom_domains' function.
class DescribeCustomDomainsResponseTypeDef(BaseValidatorModel):
    DNSTarget: str
    ServiceArn: str
    CustomDomains: List[CustomDomainTypeDef]
    VpcDNSTargets: List[VpcDNSTargetTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef
    NextToken: Optional[str] = None


# This class is the output for the 'disassociate_custom_domain' function.
class DisassociateCustomDomainResponseTypeDef(BaseValidatorModel):
    DNSTarget: str
    ServiceArn: str
    CustomDomain: CustomDomainTypeDef
    VpcDNSTargets: List[VpcDNSTargetTypeDef]
    ResponseMetadata: ResponseMetadataTypeDef


class CodeRepositoryOutputTypeDef(BaseValidatorModel):
    RepositoryUrl: str
    SourceCodeVersion: SourceCodeVersionTypeDef
    CodeConfiguration: Optional[CodeConfigurationOutputTypeDef] = None
    SourceDirectory: Optional[str] = None


class CodeRepositoryTypeDef(BaseValidatorModel):
    RepositoryUrl: str
    SourceCodeVersion: SourceCodeVersionTypeDef
    CodeConfiguration: Optional[CodeConfigurationTypeDef] = None
    SourceDirectory: Optional[str] = None


# This class is the output for the 'create_observability_configuration' function.
class CreateObservabilityConfigurationResponseTypeDef(BaseValidatorModel):
    ObservabilityConfiguration: ObservabilityConfigurationTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_observability_configuration' function.
class DeleteObservabilityConfigurationResponseTypeDef(BaseValidatorModel):
    ObservabilityConfiguration: ObservabilityConfigurationTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_observability_configuration' function.
class DescribeObservabilityConfigurationResponseTypeDef(BaseValidatorModel):
    ObservabilityConfiguration: ObservabilityConfigurationTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'create_vpc_ingress_connection' function.
class CreateVpcIngressConnectionResponseTypeDef(BaseValidatorModel):
    VpcIngressConnection: VpcIngressConnectionTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_vpc_ingress_connection' function.
class DeleteVpcIngressConnectionResponseTypeDef(BaseValidatorModel):
    VpcIngressConnection: VpcIngressConnectionTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_vpc_ingress_connection' function.
class DescribeVpcIngressConnectionResponseTypeDef(BaseValidatorModel):
    VpcIngressConnection: VpcIngressConnectionTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_vpc_ingress_connection' function.
class UpdateVpcIngressConnectionResponseTypeDef(BaseValidatorModel):
    VpcIngressConnection: VpcIngressConnectionTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


class SourceConfigurationOutputTypeDef(BaseValidatorModel):
    CodeRepository: Optional[CodeRepositoryOutputTypeDef] = None
    ImageRepository: Optional[ImageRepositoryOutputTypeDef] = None
    AutoDeploymentsEnabled: Optional[bool] = None
    AuthenticationConfiguration: Optional[AuthenticationConfigurationTypeDef] = None


class SourceConfigurationTypeDef(BaseValidatorModel):
    CodeRepository: Optional[CodeRepositoryTypeDef] = None
    ImageRepository: Optional[ImageRepositoryTypeDef] = None
    AutoDeploymentsEnabled: Optional[bool] = None
    AuthenticationConfiguration: Optional[AuthenticationConfigurationTypeDef] = None


class ServiceTypeDef(BaseValidatorModel):
    ServiceName: str
    ServiceId: str
    ServiceArn: str
    CreatedAt: datetime
    UpdatedAt: datetime
    Status: ServiceStatusType
    SourceConfiguration: SourceConfigurationOutputTypeDef
    InstanceConfiguration: InstanceConfigurationTypeDef
    AutoScalingConfigurationSummary: AutoScalingConfigurationSummaryTypeDef
    NetworkConfiguration: NetworkConfigurationTypeDef
    ServiceUrl: Optional[str] = None
    DeletedAt: Optional[datetime] = None
    EncryptionConfiguration: Optional[EncryptionConfigurationTypeDef] = None
    HealthCheckConfiguration: Optional[HealthCheckConfigurationTypeDef] = None
    ObservabilityConfiguration: Optional[ServiceObservabilityConfigurationTypeDef] = None


SourceConfigurationUnionTypeDef = Union[SourceConfigurationOutputTypeDef, SourceConfigurationTypeDef]


# This class is the output for the 'create_service' function.
class CreateServiceResponseTypeDef(BaseValidatorModel):
    Service: ServiceTypeDef
    OperationId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'delete_service' function.
class DeleteServiceResponseTypeDef(BaseValidatorModel):
    Service: ServiceTypeDef
    OperationId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'describe_service' function.
class DescribeServiceResponseTypeDef(BaseValidatorModel):
    Service: ServiceTypeDef
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'pause_service' function.
class PauseServiceResponseTypeDef(BaseValidatorModel):
    Service: ServiceTypeDef
    OperationId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'resume_service' function.
class ResumeServiceResponseTypeDef(BaseValidatorModel):
    Service: ServiceTypeDef
    OperationId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the output for the 'update_service' function.
class UpdateServiceResponseTypeDef(BaseValidatorModel):
    Service: ServiceTypeDef
    OperationId: str
    ResponseMetadata: ResponseMetadataTypeDef


# This class is the input for the 'create_service' function.
class CreateServiceRequestTypeDef(BaseValidatorModel):
    ServiceName: str
    SourceConfiguration: SourceConfigurationUnionTypeDef
    InstanceConfiguration: Optional[InstanceConfigurationTypeDef] = None
    Tags: Optional[List[TagTypeDef]] = None
    EncryptionConfiguration: Optional[EncryptionConfigurationTypeDef] = None
    HealthCheckConfiguration: Optional[HealthCheckConfigurationTypeDef] = None
    AutoScalingConfigurationArn: Optional[str] = None
    NetworkConfiguration: Optional[NetworkConfigurationTypeDef] = None
    ObservabilityConfiguration: Optional[ServiceObservabilityConfigurationTypeDef] = None


# This class is the input for the 'update_service' function.
class UpdateServiceRequestTypeDef(BaseValidatorModel):
    ServiceArn: str
    SourceConfiguration: Optional[SourceConfigurationUnionTypeDef] = None
    InstanceConfiguration: Optional[InstanceConfigurationTypeDef] = None
    AutoScalingConfigurationArn: Optional[str] = None
    HealthCheckConfiguration: Optional[HealthCheckConfigurationTypeDef] = None
    NetworkConfiguration: Optional[NetworkConfigurationTypeDef] = None
    ObservabilityConfiguration: Optional[ServiceObservabilityConfigurationTypeDef] = None
