name: Release Package

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched for version comparison

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build package
        run: poetry build -f wheel

#      - name: Publish package
#        uses: pypa/gh-action-pypi-publish@v1.5.1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Generate sub-packages
        run: poetry run scripts/create_subpackages.py

      - name: Build sub-packages to common directory
        run: |
          mkdir -p combined_dist
          # Only iterate through directories with trailing slash
          for pkg_dir in aws_resource_validator/pydantic_models/*/; do
            if [ -d "$pkg_dir" ]; then
              echo "Building package in $pkg_dir"
              cd "$pkg_dir"
              poetry build -f wheel
              cp dist/* "$GITHUB_WORKSPACE/combined_dist/"
              cd "$GITHUB_WORKSPACE"
            fi
          done

      - name: Publish packages individually with delay
        run: |
          for wheel in combined_dist/*.whl; do
            echo "Publishing package: $wheel"
            # Try up to 3 times with increasing delay
            for attempt in {1..3}; do
              echo "Attempt $attempt for $wheel"
              if python -m twine upload --verbose --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} "$wheel"; then
                echo "Successfully uploaded $wheel"
                break
              else
                echo "Upload failed, waiting before retry..."
                sleep $((30 * attempt))  # 30s, 60s, 90s between retries
              fi
            done
            # Wait between packages to avoid rate limiting
            echo "Waiting before next package upload"
            sleep 60
          done
