name: Release Package

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched for version comparison

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build package
        run: poetry build -f wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Generate sub-packages
        run: poetry run scripts/create_subpackages.py

      - name: Build sub-packages to common directory
        run: |
          mkdir -p combined_dist
          # Only iterate through directories with trailing slash
          for pkg_dir in aws_resource_validator/pydantic_models/*/; do
            if [ -d "$pkg_dir" ]; then
              echo "Building package in $pkg_dir"
              cd "$pkg_dir"
              poetry build -f wheel
              cp dist/* "$GITHUB_WORKSPACE/combined_dist/"
              cd "$GITHUB_WORKSPACE"
            fi
          done

      - name: Publish all packages
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: combined_dist
