name: Release Package

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched for version comparison

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Bump version in pyproject.toml
        run: |
          # Bump the version using a patch increment and extract the new version.
          NEW_VERSION=$(poetry version patch 2>&1 | awk '{print $NF}')
          echo "Bumped version to $NEW_VERSION"
          
          git config user.name "github-release"
          git config user.email "github-release@github.com"
          
          git add pyproject.toml
          git commit -m "Bump version to $NEW_VERSION [skip ci]" || echo "No changes to commit."
          git push

      - name: Build package
        run: poetry build -f wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
